// @generated by `cargo xtask sksl gen-lexer` from third_party/skia/src/sksl/SkSLLexer.h.
// Do not edit.

/// `Token::Kind`: the token kinds, in Skia's order (the values the DFA accepts).
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum TokenKind {
    /// `TK_END_OF_FILE`.
    EndOfFile = 0,
    /// `TK_FLOAT_LITERAL`.
    FloatLiteral = 1,
    /// `TK_INT_LITERAL`.
    IntLiteral = 2,
    /// `TK_BAD_OCTAL`.
    BadOctal = 3,
    /// `TK_TRUE_LITERAL`.
    TrueLiteral = 4,
    /// `TK_FALSE_LITERAL`.
    FalseLiteral = 5,
    /// `TK_IF`.
    If = 6,
    /// `TK_ELSE`.
    Else = 7,
    /// `TK_FOR`.
    For = 8,
    /// `TK_WHILE`.
    While = 9,
    /// `TK_DO`.
    Do = 10,
    /// `TK_SWITCH`.
    Switch = 11,
    /// `TK_CASE`.
    Case = 12,
    /// `TK_DEFAULT`.
    Default = 13,
    /// `TK_BREAK`.
    Break = 14,
    /// `TK_CONTINUE`.
    Continue = 15,
    /// `TK_DISCARD`.
    Discard = 16,
    /// `TK_RETURN`.
    Return = 17,
    /// `TK_IN`.
    In = 18,
    /// `TK_OUT`.
    Out = 19,
    /// `TK_INOUT`.
    Inout = 20,
    /// `TK_UNIFORM`.
    Uniform = 21,
    /// `TK_CONST`.
    Const = 22,
    /// `TK_FLAT`.
    Flat = 23,
    /// `TK_NOPERSPECTIVE`.
    Noperspective = 24,
    /// `TK_INLINE`.
    Inline = 25,
    /// `TK_NOINLINE`.
    Noinline = 26,
    /// `TK_PURE`.
    Pure = 27,
    /// `TK_READONLY`.
    Readonly = 28,
    /// `TK_WRITEONLY`.
    Writeonly = 29,
    /// `TK_BUFFER`.
    Buffer = 30,
    /// `TK_STRUCT`.
    Struct = 31,
    /// `TK_LAYOUT`.
    Layout = 32,
    /// `TK_HIGHP`.
    Highp = 33,
    /// `TK_MEDIUMP`.
    Mediump = 34,
    /// `TK_LOWP`.
    Lowp = 35,
    /// `TK_ES3`.
    Es3 = 36,
    /// `TK_EXPORT`.
    Export = 37,
    /// `TK_WORKGROUP`.
    Workgroup = 38,
    /// `TK_PIXELLOCAL`.
    Pixellocal = 39,
    /// `TK_RESERVED`.
    Reserved = 40,
    /// `TK_PRIVATE_IDENTIFIER`.
    PrivateIdentifier = 41,
    /// `TK_IDENTIFIER`.
    Identifier = 42,
    /// `TK_DIRECTIVE`.
    Directive = 43,
    /// `TK_LPAREN`.
    Lparen = 44,
    /// `TK_RPAREN`.
    Rparen = 45,
    /// `TK_LBRACE`.
    Lbrace = 46,
    /// `TK_RBRACE`.
    Rbrace = 47,
    /// `TK_LBRACKET`.
    Lbracket = 48,
    /// `TK_RBRACKET`.
    Rbracket = 49,
    /// `TK_DOT`.
    Dot = 50,
    /// `TK_COMMA`.
    Comma = 51,
    /// `TK_PLUSPLUS`.
    Plusplus = 52,
    /// `TK_MINUSMINUS`.
    Minusminus = 53,
    /// `TK_PLUS`.
    Plus = 54,
    /// `TK_MINUS`.
    Minus = 55,
    /// `TK_STAR`.
    Star = 56,
    /// `TK_SLASH`.
    Slash = 57,
    /// `TK_PERCENT`.
    Percent = 58,
    /// `TK_SHL`.
    Shl = 59,
    /// `TK_SHR`.
    Shr = 60,
    /// `TK_BITWISEOR`.
    Bitwiseor = 61,
    /// `TK_BITWISEXOR`.
    Bitwisexor = 62,
    /// `TK_BITWISEAND`.
    Bitwiseand = 63,
    /// `TK_BITWISENOT`.
    Bitwisenot = 64,
    /// `TK_LOGICALOR`.
    Logicalor = 65,
    /// `TK_LOGICALXOR`.
    Logicalxor = 66,
    /// `TK_LOGICALAND`.
    Logicaland = 67,
    /// `TK_LOGICALNOT`.
    Logicalnot = 68,
    /// `TK_QUESTION`.
    Question = 69,
    /// `TK_COLON`.
    Colon = 70,
    /// `TK_EQ`.
    Eq = 71,
    /// `TK_EQEQ`.
    Eqeq = 72,
    /// `TK_NEQ`.
    Neq = 73,
    /// `TK_GT`.
    Gt = 74,
    /// `TK_LT`.
    Lt = 75,
    /// `TK_GTEQ`.
    Gteq = 76,
    /// `TK_LTEQ`.
    Lteq = 77,
    /// `TK_PLUSEQ`.
    Pluseq = 78,
    /// `TK_MINUSEQ`.
    Minuseq = 79,
    /// `TK_STAREQ`.
    Stareq = 80,
    /// `TK_SLASHEQ`.
    Slasheq = 81,
    /// `TK_PERCENTEQ`.
    Percenteq = 82,
    /// `TK_SHLEQ`.
    Shleq = 83,
    /// `TK_SHREQ`.
    Shreq = 84,
    /// `TK_BITWISEOREQ`.
    Bitwiseoreq = 85,
    /// `TK_BITWISEXOREQ`.
    Bitwisexoreq = 86,
    /// `TK_BITWISEANDEQ`.
    Bitwiseandeq = 87,
    /// `TK_SEMICOLON`.
    Semicolon = 88,
    /// `TK_WHITESPACE`.
    Whitespace = 89,
    /// `TK_LINE_COMMENT`.
    LineComment = 90,
    /// `TK_BLOCK_COMMENT`.
    BlockComment = 91,
    /// `TK_INVALID`.
    Invalid = 92,
    /// `TK_NONE`.
    None = 93,
}

impl TokenKind {
    /// Every kind, in declaration order.
    pub const ALL: [Self; 94] = [
        Self::EndOfFile,
        Self::FloatLiteral,
        Self::IntLiteral,
        Self::BadOctal,
        Self::TrueLiteral,
        Self::FalseLiteral,
        Self::If,
        Self::Else,
        Self::For,
        Self::While,
        Self::Do,
        Self::Switch,
        Self::Case,
        Self::Default,
        Self::Break,
        Self::Continue,
        Self::Discard,
        Self::Return,
        Self::In,
        Self::Out,
        Self::Inout,
        Self::Uniform,
        Self::Const,
        Self::Flat,
        Self::Noperspective,
        Self::Inline,
        Self::Noinline,
        Self::Pure,
        Self::Readonly,
        Self::Writeonly,
        Self::Buffer,
        Self::Struct,
        Self::Layout,
        Self::Highp,
        Self::Mediump,
        Self::Lowp,
        Self::Es3,
        Self::Export,
        Self::Workgroup,
        Self::Pixellocal,
        Self::Reserved,
        Self::PrivateIdentifier,
        Self::Identifier,
        Self::Directive,
        Self::Lparen,
        Self::Rparen,
        Self::Lbrace,
        Self::Rbrace,
        Self::Lbracket,
        Self::Rbracket,
        Self::Dot,
        Self::Comma,
        Self::Plusplus,
        Self::Minusminus,
        Self::Plus,
        Self::Minus,
        Self::Star,
        Self::Slash,
        Self::Percent,
        Self::Shl,
        Self::Shr,
        Self::Bitwiseor,
        Self::Bitwisexor,
        Self::Bitwiseand,
        Self::Bitwisenot,
        Self::Logicalor,
        Self::Logicalxor,
        Self::Logicaland,
        Self::Logicalnot,
        Self::Question,
        Self::Colon,
        Self::Eq,
        Self::Eqeq,
        Self::Neq,
        Self::Gt,
        Self::Lt,
        Self::Gteq,
        Self::Lteq,
        Self::Pluseq,
        Self::Minuseq,
        Self::Stareq,
        Self::Slasheq,
        Self::Percenteq,
        Self::Shleq,
        Self::Shreq,
        Self::Bitwiseoreq,
        Self::Bitwisexoreq,
        Self::Bitwiseandeq,
        Self::Semicolon,
        Self::Whitespace,
        Self::LineComment,
        Self::BlockComment,
        Self::Invalid,
        Self::None,
    ];
}
