// Copyright 2017 Google LLC
// Copyright 2026 The skia-rust Authors
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.
// Ported from Skia: src/sksl/SkSLLexer.{h,cpp} (the driver; the tables are generated by
// `cargo xtask sksl gen-lexer` into `tables.rs` and `kinds.rs`).

//! The `SkSL` lexer: a table-driven DFA over the source bytes, yielding [`Token`]s that record a
//! kind and a byte range.

mod kinds;
// Laid out by `cargo xtask sksl gen-lexer`, not by rustfmt.
#[rustfmt::skip]
mod tables;

pub use kinds::TokenKind;

use tables::{ACCEPTS, COMPACT, FULL, INDICES, INVALID_CHAR, MAPPINGS};

/// `SkSL::Token`: a kind and the byte range `[offset, offset + length)` it covers.
///
/// `kind` is `None` when the DFA stopped in a state that accepts nothing, as in `9e` (an unfinished
/// number). Skia stores the sentinel 255 there, which is not a `Token::Kind` enumerator.
#[doc(alias = "SkSL::Token")]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Token {
    /// `fKind`.
    pub kind: Option<TokenKind>,
    /// `fOffset`: the byte offset of the first character.
    pub offset: i32,
    /// `fLength`: the number of bytes.
    pub length: i32,
}

impl Token {
    /// `Token(Kind kind, int32_t offset, int32_t length)`.
    #[must_use]
    pub fn new(kind: Option<TokenKind>, offset: i32, length: i32) -> Self {
        Self {
            kind,
            offset,
            length,
        }
    }
}

impl Default for Token {
    /// The C++ default: kind `TK_NONE`, offset and length -1.
    fn default() -> Self {
        Self::new(Some(TokenKind::None), -1, -1)
    }
}

/// `SkSL::Lexer`: reads tokens from `text`, one at a time.
#[doc(alias = "SkSL::Lexer")]
#[derive(Clone, Copy, Debug)]
pub struct Lexer<'a> {
    text: &'a [u8],
    offset: i32,
}

/// `Lexer::Checkpoint`: a saved position to rewind to.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Checkpoint {
    offset: i32,
}

impl<'a> Lexer<'a> {
    /// A lexer positioned at the start of `text` (`start`). Offsets are byte offsets.
    #[must_use]
    pub fn new(text: &'a [u8]) -> Self {
        Self { text, offset: 0 }
    }

    /// `start`: restarts on new text.
    pub fn start(&mut self, text: &'a [u8]) {
        self.text = text;
        self.offset = 0;
    }

    /// `getCheckpoint`.
    #[must_use]
    pub fn checkpoint(&self) -> Checkpoint {
        Checkpoint {
            offset: self.offset,
        }
    }

    /// `rewindToCheckpoint`.
    pub fn rewind_to_checkpoint(&mut self, checkpoint: Checkpoint) {
        self.offset = checkpoint.offset;
    }

    /// `Lexer::next`: the next token. At the end of the text this is `TokenKind::EndOfFile`.
    // Port of: src/sksl/SkSLLexer.cpp#L2028-L2103 (`get_transition` and `Lexer::next`).
    #[doc(alias = "Lexer::next")]
    #[must_use]
    pub fn next_token(&mut self) -> Token {
        // Skia's note: a token's proper prefixes are never tokens in SkSL's grammar, so the DFA
        // can stop at the first state without a transition and report what it accepted.
        let start_offset = self.offset;
        let mut state: u16 = 1;
        loop {
            let len = i32::try_from(self.text.len()).unwrap_or(i32::MAX);
            if self.offset >= len {
                if start_offset == len || ACCEPTS[usize::from(state)] == 255 {
                    return Token::new(Some(TokenKind::EndOfFile), start_offset, 0);
                }
                break;
            }
            let mut c = self.text[usize::try_from(self.offset).unwrap_or(0)].wrapping_sub(9);
            if c >= 118 {
                c = INVALID_CHAR;
            }
            let new_state = get_transition(MAPPINGS[usize::from(c)], state);
            if new_state == 0 {
                break;
            }
            state = new_state;
            self.offset += 1;
        }
        let kind = accepted_kind(ACCEPTS[usize::from(state)]);
        Token::new(kind, start_offset, self.offset - start_offset)
    }
}

/// `(Token::Kind)kAccepts[state]`: 255 accepts nothing, and every other value is a kind.
fn accepted_kind(accept: u8) -> Option<TokenKind> {
    if accept == 255 {
        None
    } else {
        TokenKind::ALL.get(usize::from(accept)).copied()
    }
}

/// `get_transition`: the next state for `transition` from `state`, or 0 when there is none.
// Port of: src/sksl/SkSLLexer.cpp#L2028-L2038 (chrome/m156)
fn get_transition(transition: u8, state: u16) -> u16 {
    let index = INDICES[usize::from(state)];
    if index < 0 {
        return FULL[usize::try_from(!index).unwrap_or(0)][usize::from(transition)];
    }
    let (values, data) = COMPACT[usize::try_from(index).unwrap_or(0)];
    let mut v = i32::from(data[usize::from(transition >> 2)]);
    v >>= 2 * (transition & 3);
    v &= 3;
    v *= 10;
    // `(entry.values >> v) & 1023`, with `v` in 0..=30.
    u16::try_from((values >> v) & 1023).unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::{Lexer, TokenKind};

    /// Every token from `text`, up to and including the end of file.
    fn tokens(text: &str) -> Vec<(Option<TokenKind>, i32, i32)> {
        let mut lexer = Lexer::new(text.as_bytes());
        let mut out = Vec::new();
        loop {
            let t = lexer.next_token();
            out.push((t.kind, t.offset, t.length));
            // A token of length 0 that is not the end of file would not advance (Skia's
            // `Lexer::next` has the same behaviour); stop there, as the oracle does.
            if t.kind == Some(TokenKind::EndOfFile) || t.length <= 0 {
                return out;
            }
        }
    }

    #[test]
    fn empty_input_is_end_of_file() {
        assert_eq!(tokens(""), [(Some(TokenKind::EndOfFile), 0, 0)]);
    }

    #[test]
    fn keywords_and_identifiers() {
        assert_eq!(
            tokens("if iffy"),
            [
                (Some(TokenKind::If), 0, 2),
                (Some(TokenKind::Whitespace), 2, 1),
                (Some(TokenKind::Identifier), 3, 4),
                (Some(TokenKind::EndOfFile), 7, 0),
            ]
        );
    }

    #[test]
    fn longest_operator_wins() {
        assert_eq!(
            tokens("+=="),
            [
                (Some(TokenKind::Pluseq), 0, 2),
                (Some(TokenKind::Eq), 2, 1),
                (Some(TokenKind::EndOfFile), 3, 0),
            ]
        );
    }

    /// Token streams from Skia's `SkSLLexer.cpp`, compiled unchanged with a harness that prints
    /// `kind offset length` for every token. Each line of `oracle_cases.txt` is the input as hex,
    /// a tab, then the tokens separated by `;`. The kind is the `Token::Kind` value, or 255 for a
    /// token that the DFA did not accept.
    #[test]
    fn matches_skia_on_the_oracle_corpus() {
        let corpus = include_str!("oracle_cases.txt");
        let mut checked = 0;
        for line in corpus.lines() {
            let (hex, expected) = line.split_once('\t').expect("tab-separated case");
            let bytes: Vec<u8> = (0..hex.len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex"))
                .collect();
            let mut lexer = Lexer::new(&bytes);
            let mut got = Vec::new();
            loop {
                let t = lexer.next_token();
                let kind = t.kind.map_or(255, |k| k as u8);
                got.push(format!("{kind} {} {}", t.offset, t.length));
                if t.kind == Some(TokenKind::EndOfFile) || t.length <= 0 {
                    break;
                }
            }
            assert_eq!(got.join(";"), expected, "input {hex}");
            checked += 1;
        }
        assert!(checked > 100, "the corpus is too small: {checked} cases");
    }
}
