// Copyright 2022 Google LLC
// Copyright 2026 The skia-rust Authors
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.
// Ported from Skia: src/gpu/graphite/ShaderCodeDictionary.cpp

//! The built-in snippet table of the `ShaderCodeDictionary` constructor.
//!
//! GENERATED by `oracle/graphite-snippets/gen_snippet_table.py` from the pinned Skia source.
//! Do not edit by hand: the `SkSL` names and static function names below end up in the generated
//! `SkSL`, so they must be byte-identical to Skia's.

use super::{LiftableExpressionType, ShaderSnippet, SnippetRequirementFlags, TextureAndSampler};
use crate::graphite::attribute::Interpolation;
use crate::graphite::built_in_code_snippet_id::BuiltInCodeSnippetID;
use crate::graphite::uniform::Uniform;
use crate::sksl_type_shared::SkSLType;

/// Fills the slots of the snippets that `ShaderCodeDictionary`'s constructor initializes one
/// by one (all but the fixed-function blends, which it creates in a loop).
// Port of: src/gpu/graphite/ShaderCodeDictionary.cpp#L1134-L1734 (chrome/m156)
#[allow(clippy::too_many_lines)] // mirrors the C++ constructor's table
pub(super) fn fill_built_in_snippets(table: &mut [Option<ShaderSnippet>]) {
    table[BuiltInCodeSnippetID::Error as usize] = Some(ShaderSnippet {
        name: String::from("Error"),
        static_function_name: Some("sk_error"),
        snippet_requirement_flags: SnippetRequirementFlags::NONE,
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::PriorOutput as usize] = Some(ShaderSnippet {
        name: String::from("Passthrough"),
        static_function_name: Some("sk_passthrough"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::SolidColorShader as usize] = Some(ShaderSnippet {
        name: String::from("SolidColor"),
        static_function_name: None,
        snippet_requirement_flags: SnippetRequirementFlags::NONE,
        uniforms: vec![Uniform::new("color", SkSLType::Float4)],
        preamble_generator: Some(super::generate_solid_color_preamble),
        liftable_expression_interpolation: Interpolation::Linear,
        liftable_expression_type: LiftableExpressionType::PriorStageOutput,
        liftable_expression_generator: Some(super::generate_solid_color_expression),
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::RGBPaintColor as usize] = Some(ShaderSnippet {
        name: String::from("RGBPaintColor"),
        static_function_name: Some("sk_rgb_opaque"),
        snippet_requirement_flags: SnippetRequirementFlags::NONE,
        uniforms: vec![Uniform::paint_color()],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::AlphaOnlyPaintColor as usize] = Some(ShaderSnippet {
        name: String::from("AlphaOnlyPaintColor"),
        static_function_name: Some("sk_alpha_only"),
        snippet_requirement_flags: SnippetRequirementFlags::NONE,
        uniforms: vec![Uniform::paint_color()],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::LinearGradientShader4 as usize] = Some(ShaderSnippet {
        name: String::from("LinearGradient4"),
        static_function_name: Some("sk_linear_grad_4_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new_array("colors", SkSLType::Float4, 4),
            Uniform::new("offsets", SkSLType::Float4),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::LinearGradientShader8 as usize] = Some(ShaderSnippet {
        name: String::from("LinearGradient8"),
        static_function_name: Some("sk_linear_grad_8_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new_array("colors", SkSLType::Float4, 8),
            Uniform::new_array("offsets", SkSLType::Float4, 2),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::LinearGradientShaderTexture as usize] = Some(ShaderSnippet {
        name: String::from("LinearGradientTexture"),
        static_function_name: Some("sk_linear_grad_tex_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("numStops", SkSLType::Int),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        textures_and_samplers: vec![TextureAndSampler::new("colorAndOffsetSampler")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::LinearGradientShaderBuffer as usize] = Some(ShaderSnippet {
        name: String::from("LinearGradientBuffer"),
        static_function_name: Some("sk_linear_grad_buf_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS
            | SnippetRequirementFlags::STORAGE_BUFFER,
        uniforms: vec![
            Uniform::new("numStops", SkSLType::Int),
            Uniform::new("bufferOffset", SkSLType::Int),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::RadialGradientShader4 as usize] = Some(ShaderSnippet {
        name: String::from("RadialGradient4"),
        static_function_name: Some("sk_radial_grad_4_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new_array("colors", SkSLType::Float4, 4),
            Uniform::new("offsets", SkSLType::Float4),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::RadialGradientShader8 as usize] = Some(ShaderSnippet {
        name: String::from("RadialGradient8"),
        static_function_name: Some("sk_radial_grad_8_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new_array("colors", SkSLType::Float4, 8),
            Uniform::new_array("offsets", SkSLType::Float4, 2),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::RadialGradientShaderTexture as usize] = Some(ShaderSnippet {
        name: String::from("RadialGradientTexture"),
        static_function_name: Some("sk_radial_grad_tex_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("numStops", SkSLType::Int),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        textures_and_samplers: vec![TextureAndSampler::new("colorAndOffsetSampler")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::RadialGradientShaderBuffer as usize] = Some(ShaderSnippet {
        name: String::from("RadialGradientBuffer"),
        static_function_name: Some("sk_radial_grad_buf_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS
            | SnippetRequirementFlags::STORAGE_BUFFER,
        uniforms: vec![
            Uniform::new("numStops", SkSLType::Int),
            Uniform::new("bufferOffset", SkSLType::Int),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::SweepGradientShader4 as usize] = Some(ShaderSnippet {
        name: String::from("SweepGradient4"),
        static_function_name: Some("sk_sweep_grad_4_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new_array("colors", SkSLType::Float4, 4),
            Uniform::new("offsets", SkSLType::Float4),
            Uniform::new("bias", SkSLType::Float),
            Uniform::new("scale", SkSLType::Float),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::SweepGradientShader8 as usize] = Some(ShaderSnippet {
        name: String::from("SweepGradient8"),
        static_function_name: Some("sk_sweep_grad_8_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new_array("colors", SkSLType::Float4, 8),
            Uniform::new_array("offsets", SkSLType::Float4, 2),
            Uniform::new("bias", SkSLType::Float),
            Uniform::new("scale", SkSLType::Float),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::SweepGradientShaderTexture as usize] = Some(ShaderSnippet {
        name: String::from("SweepGradientTexture"),
        static_function_name: Some("sk_sweep_grad_tex_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("bias", SkSLType::Float),
            Uniform::new("scale", SkSLType::Float),
            Uniform::new("numStops", SkSLType::Int),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        textures_and_samplers: vec![TextureAndSampler::new("colorAndOffsetSampler")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::SweepGradientShaderBuffer as usize] = Some(ShaderSnippet {
        name: String::from("SweepGradientBuffer"),
        static_function_name: Some("sk_sweep_grad_buf_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS
            | SnippetRequirementFlags::STORAGE_BUFFER,
        uniforms: vec![
            Uniform::new("bias", SkSLType::Float),
            Uniform::new("scale", SkSLType::Float),
            Uniform::new("numStops", SkSLType::Int),
            Uniform::new("bufferOffset", SkSLType::Int),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::ConicalGradientShader4 as usize] = Some(ShaderSnippet {
        name: String::from("ConicalGradient4"),
        static_function_name: Some("sk_conical_grad_4_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new_array("colors", SkSLType::Float4, 4),
            Uniform::new("offsets", SkSLType::Float4),
            Uniform::new("radius0", SkSLType::Float),
            Uniform::new("dRadius", SkSLType::Float),
            Uniform::new("a", SkSLType::Float),
            Uniform::new("invA", SkSLType::Float),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::ConicalGradientShader8 as usize] = Some(ShaderSnippet {
        name: String::from("ConicalGradient8"),
        static_function_name: Some("sk_conical_grad_8_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new_array("colors", SkSLType::Float4, 8),
            Uniform::new_array("offsets", SkSLType::Float4, 2),
            Uniform::new("radius0", SkSLType::Float),
            Uniform::new("dRadius", SkSLType::Float),
            Uniform::new("a", SkSLType::Float),
            Uniform::new("invA", SkSLType::Float),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::ConicalGradientShaderTexture as usize] = Some(ShaderSnippet {
        name: String::from("ConicalGradientTexture"),
        static_function_name: Some("sk_conical_grad_tex_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("radius0", SkSLType::Float),
            Uniform::new("dRadius", SkSLType::Float),
            Uniform::new("a", SkSLType::Float),
            Uniform::new("invA", SkSLType::Float),
            Uniform::new("numStops", SkSLType::Int),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        textures_and_samplers: vec![TextureAndSampler::new("colorAndOffsetSampler")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::ConicalGradientShaderBuffer as usize] = Some(ShaderSnippet {
        name: String::from("ConicalGradientBuffer"),
        static_function_name: Some("sk_conical_grad_buf_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS
            | SnippetRequirementFlags::STORAGE_BUFFER,
        uniforms: vec![
            Uniform::new("radius0", SkSLType::Float),
            Uniform::new("dRadius", SkSLType::Float),
            Uniform::new("a", SkSLType::Float),
            Uniform::new("invA", SkSLType::Float),
            Uniform::new("numStops", SkSLType::Int),
            Uniform::new("bufferOffset", SkSLType::Int),
            Uniform::new("tilemode", SkSLType::Int),
            Uniform::new("colorSpace", SkSLType::Int),
            Uniform::new("doUnPremul", SkSLType::Int),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::LocalMatrixShader as usize] = Some(ShaderSnippet {
        name: String::from("LocalMatrix"),
        static_function_name: None,
        snippet_requirement_flags: SnippetRequirementFlags::NONE,
        uniforms: vec![
            Uniform::new("upper2x2", SkSLType::Float4),
            Uniform::new("translation", SkSLType::Float2),
        ],
        num_children: super::NUM_COORDINATE_MANIPULATE_CHILDREN,
        preamble_generator: Some(super::generate_coord_manipulation_preamble),
        liftable_expression_type: LiftableExpressionType::LocalCoords,
        liftable_expression_generator: Some(super::generate_local_matrix_expression),
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::LocalMatrixShaderPersp as usize] = Some(ShaderSnippet {
        name: String::from("LocalMatrixShaderPersp"),
        static_function_name: None,
        snippet_requirement_flags: SnippetRequirementFlags::NONE,
        uniforms: vec![Uniform::new("localMatrix", SkSLType::Float3x3)],
        num_children: super::NUM_COORDINATE_MANIPULATE_CHILDREN,
        preamble_generator: Some(super::generate_coord_manipulation_preamble),
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::ImageShader as usize] = Some(ShaderSnippet {
        name: String::from("Image"),
        static_function_name: Some("sk_image_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS
            | SnippetRequirementFlags::STORES_SAMPLER_DESC_DATA,
        uniforms: vec![
            Uniform::new("invImgSize", SkSLType::Float2),
            Uniform::new("subset", SkSLType::Float4),
            Uniform::new("tilemodeX", SkSLType::Int),
            Uniform::new("tilemodeY", SkSLType::Int),
            Uniform::new("filterMode", SkSLType::Int),
        ],
        textures_and_samplers: vec![TextureAndSampler::new("image")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CubicImageShader as usize] = Some(ShaderSnippet {
        name: String::from("CubicImage"),
        static_function_name: Some("sk_cubic_image_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS
            | SnippetRequirementFlags::STORES_SAMPLER_DESC_DATA,
        uniforms: vec![
            Uniform::new("invImgSize", SkSLType::Float2),
            Uniform::new("subset", SkSLType::Float4),
            Uniform::new("tilemodeX", SkSLType::Int),
            Uniform::new("tilemodeY", SkSLType::Int),
            Uniform::new("cubicCoeffs", SkSLType::Half4x4),
        ],
        textures_and_samplers: vec![TextureAndSampler::new("image")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::HWImageShader as usize] = Some(ShaderSnippet {
        name: String::from("HardwareImage"),
        static_function_name: Some("sk_hw_image_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS
            | SnippetRequirementFlags::STORES_SAMPLER_DESC_DATA,
        textures_and_samplers: vec![TextureAndSampler::new("image")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::ImageShaderClamp as usize] = Some(ShaderSnippet {
        name: String::from("ImageShaderClamp"),
        static_function_name: Some("sk_image_shader_clamp"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS
            | SnippetRequirementFlags::STORES_SAMPLER_DESC_DATA,
        uniforms: vec![
            Uniform::new("invImgSize", SkSLType::Float2),
            Uniform::new("subsetInsetClamp", SkSLType::Float4),
        ],
        textures_and_samplers: vec![TextureAndSampler::new("image")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::YUVImageShader as usize] = Some(ShaderSnippet {
        name: String::from("YUVImage"),
        static_function_name: Some("sk_yuv_image_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("invImgSizeY", SkSLType::Float2),
            Uniform::new("invImgSizeUV", SkSLType::Float2),
            Uniform::new("subset", SkSLType::Float4),
            Uniform::new("linearFilterUVInset", SkSLType::Float2),
            Uniform::new("tilemodeX", SkSLType::Int),
            Uniform::new("tilemodeY", SkSLType::Int),
            Uniform::new("filterModeY", SkSLType::Int),
            Uniform::new("filterModeUV", SkSLType::Int),
            Uniform::new("channelSelectY", SkSLType::Half4),
            Uniform::new("channelSelectU", SkSLType::Half4),
            Uniform::new("channelSelectV", SkSLType::Half4),
            Uniform::new("channelSelectA", SkSLType::Half4),
            Uniform::new("yuvToRGBMatrix", SkSLType::Half3x3),
            Uniform::new("yuvToRGBTranslate", SkSLType::Half3),
        ],
        textures_and_samplers: vec![
            TextureAndSampler::new("samplerY"),
            TextureAndSampler::new("samplerU"),
            TextureAndSampler::new("samplerV"),
            TextureAndSampler::new("samplerA"),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CubicYUVImageShader as usize] = Some(ShaderSnippet {
        name: String::from("CubicYUVImage"),
        static_function_name: Some("sk_cubic_yuv_image_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("invImgSizeY", SkSLType::Float2),
            Uniform::new("invImgSizeUV", SkSLType::Float2),
            Uniform::new("subset", SkSLType::Float4),
            Uniform::new("tilemodeX", SkSLType::Int),
            Uniform::new("tilemodeY", SkSLType::Int),
            Uniform::new("cubicCoeffs", SkSLType::Half4x4),
            Uniform::new("channelSelectY", SkSLType::Half4),
            Uniform::new("channelSelectU", SkSLType::Half4),
            Uniform::new("channelSelectV", SkSLType::Half4),
            Uniform::new("channelSelectA", SkSLType::Half4),
            Uniform::new("yuvToRGBMatrix", SkSLType::Half3x3),
            Uniform::new("yuvToRGBTranslate", SkSLType::Half3),
        ],
        textures_and_samplers: vec![
            TextureAndSampler::new("samplerY"),
            TextureAndSampler::new("samplerU"),
            TextureAndSampler::new("samplerV"),
            TextureAndSampler::new("samplerA"),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::HWYUVImageShader as usize] = Some(ShaderSnippet {
        name: String::from("HWYUVImage"),
        static_function_name: Some("sk_hw_yuv_image_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("invImgSizeY", SkSLType::Float2),
            Uniform::new("invImgSizeUV", SkSLType::Float2),
            Uniform::new("subset", SkSLType::Float4),
            Uniform::new("linearFilterUVInset", SkSLType::Float2),
            Uniform::new("channelSelectY", SkSLType::Half4),
            Uniform::new("channelSelectU", SkSLType::Half4),
            Uniform::new("channelSelectV", SkSLType::Half4),
            Uniform::new("channelSelectA", SkSLType::Half4),
            Uniform::new("yuvToRGBMatrix", SkSLType::Half3x3),
            Uniform::new("yuvToRGBTranslate", SkSLType::Half3),
        ],
        textures_and_samplers: vec![
            TextureAndSampler::new("samplerY"),
            TextureAndSampler::new("samplerU"),
            TextureAndSampler::new("samplerV"),
            TextureAndSampler::new("samplerA"),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::HWYUVNoSwizzleImageShader as usize] = Some(ShaderSnippet {
        name: String::from("HWYUVImageNoSwizzle"),
        static_function_name: Some("sk_hw_yuv_no_swizzle_image_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("invImgSizeY", SkSLType::Float2),
            Uniform::new("invImgSizeUV", SkSLType::Float2),
            Uniform::new("subset", SkSLType::Float4),
            Uniform::new("linearFilterUVInset", SkSLType::Float2),
            Uniform::new("yuvToRGBMatrix", SkSLType::Half3x3),
            Uniform::new("yuvToRGBXlateAlphaParams", SkSLType::Half4),
        ],
        textures_and_samplers: vec![
            TextureAndSampler::new("samplerY"),
            TextureAndSampler::new("samplerU"),
            TextureAndSampler::new("samplerV"),
            TextureAndSampler::new("samplerA"),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CoordNormalizeShader as usize] = Some(ShaderSnippet {
        name: String::from("CoordNormalize"),
        static_function_name: None,
        snippet_requirement_flags: SnippetRequirementFlags::NONE,
        uniforms: vec![Uniform::new("invDimensions", SkSLType::Float2)],
        num_children: super::NUM_COORDINATE_MANIPULATE_CHILDREN,
        preamble_generator: Some(super::generate_coord_manipulation_preamble),
        liftable_expression_type: LiftableExpressionType::LocalCoords,
        liftable_expression_generator: Some(super::generate_coord_normalize_expression),
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CoordClampShader as usize] = Some(ShaderSnippet {
        name: String::from("CoordClamp"),
        static_function_name: None,
        snippet_requirement_flags: SnippetRequirementFlags::NONE,
        uniforms: vec![Uniform::new("subset", SkSLType::Float4)],
        num_children: super::NUM_COORDINATE_MANIPULATE_CHILDREN,
        preamble_generator: Some(super::generate_coord_manipulation_preamble),
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::DitherShader as usize] = Some(ShaderSnippet {
        name: String::from("Dither"),
        static_function_name: Some("sk_dither"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![Uniform::new("range", SkSLType::Half)],
        textures_and_samplers: vec![TextureAndSampler::new("ditherLUT")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::PerlinNoiseShader as usize] = Some(ShaderSnippet {
        name: String::from("PerlinNoise"),
        static_function_name: Some("sk_perlin_noise_shader"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("baseFrequency", SkSLType::Float2),
            Uniform::new("stitchData", SkSLType::Float2),
            Uniform::new("noiseType", SkSLType::Int),
            Uniform::new("numOctaves", SkSLType::Int),
            Uniform::new("stitching", SkSLType::Int),
        ],
        textures_and_samplers: vec![
            TextureAndSampler::new("permutationsSampler"),
            TextureAndSampler::new("noiseSampler"),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::MatrixColorFilter as usize] = Some(ShaderSnippet {
        name: String::from("MatrixColorFilter"),
        static_function_name: Some("sk_matrix_colorfilter"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![
            Uniform::new("colorMatrix", SkSLType::Half4x4),
            Uniform::new("colorTranslate", SkSLType::Half4),
            Uniform::new("minMaxRGB", SkSLType::Half2),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::HSLMatrixColorFilter as usize] = Some(ShaderSnippet {
        name: String::from("HSLMatrixColorFilter"),
        static_function_name: Some("sk_hsl_matrix_colorfilter"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![
            Uniform::new("colorMatrix", SkSLType::Half4x4),
            Uniform::new("colorTranslate", SkSLType::Half4),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::TableColorFilter as usize] = Some(ShaderSnippet {
        name: String::from("TableColorFilter"),
        static_function_name: Some("sk_table_colorfilter"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        textures_and_samplers: vec![TextureAndSampler::new("table")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::GaussianColorFilter as usize] = Some(ShaderSnippet {
        name: String::from("GaussianColorFilter"),
        static_function_name: Some("sk_gaussian_colorfilter"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformAlphaOnly as usize] = Some(ShaderSnippet {
        name: String::from("AlphaOnly"),
        static_function_name: Some("sk_csxform_alphaonly"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![Uniform::new("mode", SkSLType::Half)],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformPreAlpha as usize] = Some(ShaderSnippet {
        name: String::from("PreAlpha"),
        static_function_name: Some("sk_csxform_prealpha"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![Uniform::new("mode", SkSLType::Half)],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformUnpremul as usize] = Some(ShaderSnippet {
        name: String::from("Unpremul"),
        static_function_name: Some("unpremul"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformForceOpaque as usize] = Some(ShaderSnippet {
        name: String::from("ForceOpaque"),
        static_function_name: Some("sk_rgb_opaque"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformsRGB as usize] = Some(ShaderSnippet {
        name: String::from("sRGB"),
        static_function_name: Some("sk_csxform_srgb"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![
            Uniform::new("gabc", SkSLType::Float4),
            Uniform::new("def", SkSLType::Float3),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformPQ as usize] = Some(ShaderSnippet {
        name: String::from("PQ"),
        static_function_name: Some("sk_csxform_pq"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![
            Uniform::new("abc", SkSLType::Float3),
            Uniform::new("def", SkSLType::Float3),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformHLG as usize] = Some(ShaderSnippet {
        name: String::from("HLG"),
        static_function_name: Some("sk_csxform_hlg"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![
            Uniform::new("ootf", SkSLType::Float4),
            Uniform::new("abc", SkSLType::Float3),
            Uniform::new("def", SkSLType::Float3),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformHLGInv as usize] = Some(ShaderSnippet {
        name: String::from("HLG^-1"),
        static_function_name: Some("sk_csxform_hlginv"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![
            Uniform::new("ootf", SkSLType::Float4),
            Uniform::new("abc", SkSLType::Float3),
            Uniform::new("def", SkSLType::Float3),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformGamut as usize] = Some(ShaderSnippet {
        name: String::from("Gamut"),
        static_function_name: Some("sk_csxform_gamut"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![Uniform::new("gamut", SkSLType::Half3x3)],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformPostAlpha as usize] = Some(ShaderSnippet {
        name: String::from("PostAlpha"),
        static_function_name: Some("sk_csxform_postalpha"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        uniforms: vec![Uniform::new("mode", SkSLType::Half)],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::CSXformPremul as usize] = Some(ShaderSnippet {
        name: String::from("Premul"),
        static_function_name: Some("premul"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT,
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::PrimitiveColor as usize] = Some(ShaderSnippet {
        name: String::from("PrimitiveColor"),
        static_function_name: Some("sk_passthrough"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIMITIVE_COLOR,
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::AnalyticClip as usize] = Some(ShaderSnippet {
        name: String::from("AnalyticClip"),
        static_function_name: Some("sk_analytic_clip"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("xform", SkSLType::Float4),
            Uniform::new("rect", SkSLType::Float4),
            Uniform::new("radiiWithInverse", SkSLType::Float4),
        ],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::AnalyticAndAtlasClip as usize] = Some(ShaderSnippet {
        name: String::from("AnalyticAndAtlasClip"),
        static_function_name: Some("sk_analytic_and_atlas_clip"),
        snippet_requirement_flags: SnippetRequirementFlags::LOCAL_COORDS,
        uniforms: vec![
            Uniform::new("xform", SkSLType::Float4),
            Uniform::new("rect", SkSLType::Float4),
            Uniform::new("radiiWithInverse", SkSLType::Float4),
            Uniform::new("maskBounds", SkSLType::Float4),
            Uniform::new("texCoordOffset", SkSLType::Float2),
            Uniform::new("invAtlasSize", SkSLType::Float2),
        ],
        textures_and_samplers: vec![TextureAndSampler::new("atlasSampler")],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::Compose as usize] = Some(ShaderSnippet {
        name: String::from("Compose"),
        static_function_name: None,
        snippet_requirement_flags: SnippetRequirementFlags::PASSTHROUGH_LOCAL_COORDS,
        num_children: 2,
        preamble_generator: Some(super::generate_compose_preamble),
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::BlendCompose as usize] = Some(ShaderSnippet {
        name: String::from("BlendCompose"),
        static_function_name: None,
        snippet_requirement_flags: SnippetRequirementFlags::PASSTHROUGH_LOCAL_COORDS,
        num_children: 3,
        preamble_generator: Some(super::generate_compose_preamble),
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::PorterDuffBlender as usize] = Some(ShaderSnippet {
        name: String::from("PorterDuffBlender"),
        static_function_name: Some("sk_porter_duff_blend"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT
            | SnippetRequirementFlags::BLENDER_DST_COLOR,
        uniforms: vec![Uniform::new("coeffs", SkSLType::Half4)],
        ..ShaderSnippet::default()
    });
    table[BuiltInCodeSnippetID::HSLCBlender as usize] = Some(ShaderSnippet {
        name: String::from("HSLCBlender"),
        static_function_name: Some("sk_hslc_blend"),
        snippet_requirement_flags: SnippetRequirementFlags::PRIOR_STAGE_OUTPUT
            | SnippetRequirementFlags::BLENDER_DST_COLOR,
        uniforms: vec![Uniform::new("flipSat", SkSLType::Half2)],
        ..ShaderSnippet::default()
    });
}
