// Copyright 2010 Google Inc.
// Copyright 2026 The skia-rust Authors
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.
// Ported from Skia: include/core/SkImageInfo.h, src/core/SkImageInfo.cpp

//! [`ColorInfo`] and [`ImageInfo`]: pixel dimensions and encoding.

use crate::alpha_type::AlphaType;
use crate::color_space::ColorSpace;
use crate::color_type::ColorType;
use crate::image_info_priv::{
    alpha_type_is_valid, color_type_compute_offset, color_type_is_valid, color_type_shift_per_pixel,
};
use crate::point::IPoint;
use crate::rect::IRect;
use crate::safe_math::SafeMath;
use crate::size::ISize;
use crate::t_fits_in::t_fits_in;

/// Describes color range of YUV pixels. The color mapping from YUV to RGB varies depending on the
/// source. YUV pixels may be generated by JPEG images, standard video streams, or high definition
/// video streams. Each has its own mapping from YUV to RGB.
///
/// JPEG YUV values encode the full range of 0 to 255 for all three components. Video YUV values
/// often range from 16 to 235 for Y and from 16 to 240 for U and V (limited). Details of encoding
/// and conversion to RGB are described in YCbCr color space.
///
/// The identity colorspace exists to provide a utility mapping from Y to R, U to G and V to B. It
/// can be used to visualize the YUV planes or to explicitly post process the YUV channels.
// Port of: include/core/SkImageInfo.h#L68-L106 (chrome/m156)
#[doc(alias = "SkYUVColorSpace")]
#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
#[allow(non_camel_case_types)] // keeps the underscore of Skia's `kYCgCo_8bit_*` names
pub enum YUVColorSpace {
    /// describes full range
    #[doc(alias = "kJPEG_Full_SkYUVColorSpace")]
    JPEGFull = 0,
    /// describes SDTV range
    #[doc(alias = "kRec601_Limited_SkYUVColorSpace")]
    Rec601Limited = 1,
    /// describes HDTV range
    #[doc(alias = "kRec709_Full_SkYUVColorSpace")]
    Rec709Full = 2,
    #[doc(alias = "kRec709_Limited_SkYUVColorSpace")]
    Rec709Limited = 3,
    /// describes UHDTV range, non-constant-luminance
    #[doc(alias = "kBT2020_8bit_Full_SkYUVColorSpace")]
    BT2020_8BitFull = 4,
    #[doc(alias = "kBT2020_8bit_Limited_SkYUVColorSpace")]
    BT2020_8BitLimited = 5,
    #[doc(alias = "kBT2020_10bit_Full_SkYUVColorSpace")]
    BT2020_10BitFull = 6,
    #[doc(alias = "kBT2020_10bit_Limited_SkYUVColorSpace")]
    BT2020_10BitLimited = 7,
    #[doc(alias = "kBT2020_12bit_Full_SkYUVColorSpace")]
    BT2020_12BitFull = 8,
    #[doc(alias = "kBT2020_12bit_Limited_SkYUVColorSpace")]
    BT2020_12BitLimited = 9,
    #[doc(alias = "kBT2020_16bit_Full_SkYUVColorSpace")]
    BT2020_16BitFull = 10,
    #[doc(alias = "kBT2020_16bit_Limited_SkYUVColorSpace")]
    BT2020_16BitLimited = 11,
    /// describes FCC range
    #[doc(alias = "kFCC_Full_SkYUVColorSpace")]
    FCCFull = 12,
    #[doc(alias = "kFCC_Limited_SkYUVColorSpace")]
    FCCLimited = 13,
    /// describes SMPTE240M range
    #[doc(alias = "kSMPTE240_Full_SkYUVColorSpace")]
    SMPTE240Full = 14,
    #[doc(alias = "kSMPTE240_Limited_SkYUVColorSpace")]
    SMPTE240Limited = 15,
    /// describes YDZDX range
    #[doc(alias = "kYDZDX_Full_SkYUVColorSpace")]
    YDZDXFull = 16,
    #[doc(alias = "kYDZDX_Limited_SkYUVColorSpace")]
    YDZDXLimited = 17,
    /// describes GBR range
    #[doc(alias = "kGBR_Full_SkYUVColorSpace")]
    GBRFull = 18,
    #[doc(alias = "kGBR_Limited_SkYUVColorSpace")]
    GBRLimited = 19,
    /// describes `YCgCo` matrix
    #[doc(alias = "kYCgCo_8bit_Full_SkYUVColorSpace")]
    YCgCo_8BitFull = 20,
    #[doc(alias = "kYCgCo_8bit_Limited_SkYUVColorSpace")]
    YCgCo_8BitLimited = 21,
    #[doc(alias = "kYCgCo_10bit_Full_SkYUVColorSpace")]
    YCgCo_10BitFull = 22,
    #[doc(alias = "kYCgCo_10bit_Limited_SkYUVColorSpace")]
    YCgCo_10BitLimited = 23,
    #[doc(alias = "kYCgCo_12bit_Full_SkYUVColorSpace")]
    YCgCo_12BitFull = 24,
    #[doc(alias = "kYCgCo_12bit_Limited_SkYUVColorSpace")]
    YCgCo_12BitLimited = 25,
    #[doc(alias = "kYCgCo_16bit_Full_SkYUVColorSpace")]
    YCgCo_16BitFull = 26,
    #[doc(alias = "kYCgCo_16bit_Limited_SkYUVColorSpace")]
    YCgCo_16BitLimited = 27,
    /// maps Y->R, U->G, V->B
    #[doc(alias = "kIdentity_SkYUVColorSpace")]
    Identity = 28,
}

impl YUVColorSpace {
    /// The last valid value.
    #[doc(alias = "kLastEnum_SkYUVColorSpace")]
    pub const LAST_ENUM: Self = Self::Identity;
    #[doc(alias = "kJPEG_SkYUVColorSpace")]
    pub const JPEG: Self = Self::JPEGFull;
    #[doc(alias = "kRec601_SkYUVColorSpace")]
    pub const REC601: Self = Self::Rec601Limited;
    #[doc(alias = "kRec709_SkYUVColorSpace")]
    pub const REC709: Self = Self::Rec709Limited;
    #[doc(alias = "kBT2020_SkYUVColorSpace")]
    pub const BT2020: Self = Self::BT2020_8BitLimited;

    /// Returns true if the color space uses the limited (video) range.
    // Port of: src/core/SkImageInfo.cpp#L57-L96 (chrome/m156)
    #[doc(alias = "SkYUVColorSpaceIsLimitedRange")]
    #[must_use]
    pub fn is_limited_range(self) -> bool {
        match self {
            Self::Rec601Limited
            | Self::Rec709Limited
            | Self::BT2020_8BitLimited
            | Self::BT2020_10BitLimited
            | Self::BT2020_12BitLimited
            | Self::BT2020_16BitLimited
            | Self::FCCLimited
            | Self::SMPTE240Limited
            | Self::YDZDXLimited
            | Self::GBRLimited
            | Self::YCgCo_8BitLimited
            | Self::YCgCo_10BitLimited
            | Self::YCgCo_12BitLimited
            | Self::YCgCo_16BitLimited => true,

            Self::JPEGFull
            | Self::Rec709Full
            | Self::BT2020_8BitFull
            | Self::BT2020_10BitFull
            | Self::BT2020_12BitFull
            | Self::BT2020_16BitFull
            | Self::FCCFull
            | Self::SMPTE240Full
            | Self::YDZDXFull
            | Self::GBRFull
            | Self::YCgCo_8BitFull
            | Self::YCgCo_10BitFull
            | Self::YCgCo_12BitFull
            | Self::YCgCo_16BitFull
            | Self::Identity => false,
        }
    }
}

/// Describes pixel encoding: a color type, an alpha type and an optional color space. An
/// [`ImageInfo`] can be created from a [`ColorInfo`] by providing dimensions.
///
/// It encodes how pixel bits describe alpha, transparency; color components red, blue, and green;
/// and [`ColorSpace`], the range and linearity of colors.
// Port of: include/core/SkImageInfo.h#L117-L204 (chrome/m156)
#[doc(alias = "SkColorInfo")]
#[derive(Clone, Debug, Default)]
pub struct ColorInfo {
    color_space: Option<ColorSpace>,
    color_type: ColorType,
    alpha_type: AlphaType,
}

/// `SkColorInfo::operator==`: color type, alpha type and color space (by
/// [`ColorSpace::equals`]) are equivalent.
// Port of: src/core/SkImageInfo.cpp#L114-L119 (chrome/m156)
impl PartialEq for ColorInfo {
    fn eq(&self, other: &Self) -> bool {
        self.color_type == other.color_type
            && self.alpha_type == other.alpha_type
            && ColorSpace::equals(self.color_space.as_ref(), other.color_space.as_ref())
    }
}

impl ColorInfo {
    /// Creates [`ColorInfo`] from [`ColorType`] `ct`, [`AlphaType`] `at`, and optionally
    /// [`ColorSpace`] `cs`.
    ///
    /// If `cs` is `None` and the [`ColorInfo`] is part of a drawing source: [`ColorSpace`]
    /// defaults to sRGB, mapping into the surface [`ColorSpace`].
    ///
    /// Parameters are not validated to see if their values are legal, or that the combination is
    /// supported.
    // Port of: src/core/SkImageInfo.cpp#L104-L106 (chrome/m156)
    #[must_use]
    pub fn new(ct: ColorType, at: AlphaType, cs: impl Into<Option<ColorSpace>>) -> Self {
        Self {
            color_space: cs.into(),
            color_type: ct,
            alpha_type: at,
        }
    }

    /// The color space, or `None`.
    // Port of: src/core/SkImageInfo.cpp#L111-L112 (chrome/m156)
    #[doc(alias = "colorSpace")]
    #[doc(alias = "refColorSpace")]
    #[must_use]
    pub fn color_space(&self) -> Option<ColorSpace> {
        self.color_space.clone()
    }

    /// Borrows the color space, if any.
    ///
    /// skia-rust: `SkColorInfo::colorSpace()` returns a raw pointer; this returns a reference.
    #[must_use]
    pub fn color_space_ref(&self) -> Option<&ColorSpace> {
        self.color_space.as_ref()
    }

    /// The color type.
    // Port of: include/core/SkImageInfo.h#L147 (chrome/m156)
    #[doc(alias = "colorType")]
    #[must_use]
    pub fn color_type(&self) -> ColorType {
        self.color_type
    }

    /// The alpha type.
    // Port of: include/core/SkImageInfo.h#L148 (chrome/m156)
    #[doc(alias = "alphaType")]
    #[must_use]
    pub fn alpha_type(&self) -> AlphaType {
        self.alpha_type
    }

    /// Returns true if the alpha type is [`AlphaType::Opaque`], or the color type is always
    /// opaque.
    // Port of: include/core/SkImageInfo.h#L149-L152 (chrome/m156)
    #[doc(alias = "isOpaque")]
    #[must_use]
    pub fn is_opaque(&self) -> bool {
        self.alpha_type.is_opaque() || self.color_type.is_always_opaque()
    }

    /// Returns true if the color space gamma is approximately the same as sRGB.
    // Port of: src/core/SkImageInfo.cpp#L135-L137 (chrome/m156)
    #[doc(alias = "gammaCloseToSRGB")]
    #[must_use]
    pub fn is_gamma_close_to_srgb(&self) -> bool {
        self.color_space
            .as_ref()
            .is_some_and(ColorSpace::gamma_close_to_srgb)
    }

    /// Creates a [`ColorInfo`] with the same [`ColorType`] and [`ColorSpace`], with the alpha type
    /// set to `new_alpha_type`.
    // Port of: src/core/SkImageInfo.cpp#L121-L123 (chrome/m156)
    #[doc(alias = "makeAlphaType")]
    #[must_use]
    pub fn with_alpha_type(&self, new_alpha_type: AlphaType) -> Self {
        Self::new(self.color_type, new_alpha_type, self.color_space.clone())
    }

    /// Creates a [`ColorInfo`] with the same [`AlphaType`] and [`ColorSpace`], with the color type
    /// set to `new_color_type`.
    // Port of: src/core/SkImageInfo.cpp#L125-L127 (chrome/m156)
    #[doc(alias = "makeColorType")]
    #[must_use]
    pub fn with_color_type(&self, new_color_type: ColorType) -> Self {
        Self::new(new_color_type, self.alpha_type, self.color_space.clone())
    }

    /// Creates a [`ColorInfo`] with the same [`ColorType`] and [`AlphaType`], with the color space
    /// set to `cs`. `cs` may be `None`.
    // Port of: src/core/SkImageInfo.cpp#L129-L131 (chrome/m156)
    #[doc(alias = "makeColorSpace")]
    #[must_use]
    pub fn with_color_space(&self, cs: impl Into<Option<ColorSpace>>) -> Self {
        Self::new(self.color_type, self.alpha_type, cs)
    }

    /// Returns the number of bytes per pixel required by the color type. Returns zero if the color
    /// type is [`ColorType::Unknown`].
    // Port of: src/core/SkImageInfo.cpp#L133 (chrome/m156)
    #[doc(alias = "bytesPerPixel")]
    #[must_use]
    pub fn bytes_per_pixel(&self) -> usize {
        self.color_type.bytes_per_pixel()
    }

    /// Returns the bit shift converting row bytes to row pixels. Returns zero for
    /// [`ColorType::Unknown`].
    // Port of: src/core/SkImageInfo.cpp#L139 (chrome/m156)
    #[doc(alias = "shiftPerPixel")]
    #[must_use]
    pub fn shift_per_pixel(&self) -> usize {
        color_type_shift_per_pixel(self.color_type)
    }
}

/// Describes pixel dimensions and encoding. [`Bitmap`](crate::bitmap::Bitmap), `Image`,
/// [`Pixmap`](crate::pixmap::Pixmap), and `Surface` can be created from [`ImageInfo`].
/// [`ImageInfo`] can be retrieved from `Bitmap` and `Pixmap`, but not from `Image` and `Surface`.
/// For example, `Image` and `Surface` implementations may defer pixel depth, so may not
/// completely specify [`ImageInfo`].
///
/// [`ImageInfo`] contains dimensions, the pixel integral width and height. It encodes how pixel
/// bits describe alpha, transparency; color components red, blue, and green; and [`ColorSpace`],
/// the range and linearity of colors.
// Port of: include/core/SkImageInfo.h#L214-L627 (chrome/m156)
#[doc(alias = "SkImageInfo")]
#[derive(Clone, Debug, Default)]
pub struct ImageInfo {
    color_info: ColorInfo,
    dimensions: ISize,
}

/// `SkImageInfo::operator==`: dimensions, color type, alpha type and color space are equivalent.
// Port of: include/core/SkImageInfo.h#L551-L553 (chrome/m156)
impl PartialEq for ImageInfo {
    fn eq(&self, other: &Self) -> bool {
        self.dimensions == other.dimensions && self.color_info == other.color_info
    }
}

impl ImageInfo {
    /// Creates [`ImageInfo`] from integral dimensions, [`ColorType`] `ct`, [`AlphaType`] `at`, and
    /// optionally [`ColorSpace`] `cs`.
    ///
    /// If `cs` is `None` and [`ImageInfo`] is part of a drawing source: [`ColorSpace`] defaults to
    /// sRGB, mapping into the surface [`ColorSpace`]. Parameters are not validated to see if
    /// their values are legal, or that the combination is supported.
    // Port of: src/core/SkImageInfo.cpp#L172-L189 (chrome/m156)
    #[doc(alias = "Make")]
    #[must_use]
    pub fn new(
        dimensions: impl Into<ISize>,
        ct: ColorType,
        at: AlphaType,
        cs: impl Into<Option<ColorSpace>>,
    ) -> Self {
        Self {
            color_info: ColorInfo::new(ct, at, cs),
            dimensions: dimensions.into(),
        }
    }

    /// Creates [`ImageInfo`] from integral dimensions and [`ColorInfo`]. Parameters are not
    /// validated to see if their values are legal, or that the combination is supported.
    // Port of: include/core/SkImageInfo.h#L255-L260 (chrome/m156)
    #[doc(alias = "Make")]
    #[must_use]
    pub fn from_color_info(dimensions: impl Into<ISize>, color_info: ColorInfo) -> Self {
        Self {
            color_info,
            dimensions: dimensions.into(),
        }
    }

    /// Creates [`ImageInfo`] from integral dimensions, an N32 color type, `at`, and optionally
    /// [`ColorSpace`] `cs`. N32 will equal either BGRA 8888 or RGBA 8888, whichever is optimal.
    // Port of: src/core/SkImageInfo.cpp#L190-L196 (chrome/m156)
    #[doc(alias = "MakeN32")]
    #[must_use]
    pub fn new_n32(
        dimensions: impl Into<ISize>,
        at: AlphaType,
        cs: impl Into<Option<ColorSpace>>,
    ) -> Self {
        Self::new(dimensions, ColorType::N32, at, cs)
    }

    /// Creates [`ImageInfo`] from integral dimensions, an N32 color type, and `at`, with sRGB
    /// [`ColorSpace`].
    // Port of: src/core/SkImageInfo.cpp#L198-L200 (chrome/m156)
    #[doc(alias = "MakeS32")]
    #[must_use]
    pub fn new_s32(dimensions: impl Into<ISize>, at: AlphaType) -> Self {
        Self::new(dimensions, ColorType::N32, at, ColorSpace::new_srgb())
    }

    /// Creates [`ImageInfo`] from integral dimensions, an N32 color type, premultiplied alpha,
    /// and optionally [`ColorSpace`] `cs`.
    // Port of: src/core/SkImageInfo.cpp#L202-L216 (chrome/m156)
    #[doc(alias = "MakeN32Premul")]
    #[must_use]
    pub fn new_n32_premul(dimensions: impl Into<ISize>, cs: impl Into<Option<ColorSpace>>) -> Self {
        Self::new(dimensions, ColorType::N32, AlphaType::Premul, cs)
    }

    /// Creates [`ImageInfo`] from integral dimensions, an alpha-only color type, premultiplied
    /// alpha, and no [`ColorSpace`].
    // Port of: src/core/SkImageInfo.cpp#L218-L224 (chrome/m156)
    #[doc(alias = "MakeA8")]
    #[must_use]
    pub fn new_a8(dimensions: impl Into<ISize>) -> Self {
        Self::new(dimensions, ColorType::Alpha8, AlphaType::Premul, None)
    }

    /// Creates [`ImageInfo`] from integral dimensions, an unknown color type, unknown alpha type,
    /// and no [`ColorSpace`]. An [`ImageInfo`] used as a source does not draw, and one used as a
    /// destination cannot be drawn to. `None` dimensions are `(0, 0)`.
    // Port of: src/core/SkImageInfo.cpp#L226-L229 (chrome/m156)
    #[doc(alias = "MakeUnknown")]
    #[must_use]
    pub fn new_unknown(dimensions: Option<ISize>) -> Self {
        Self::new(
            dimensions.unwrap_or_default(),
            ColorType::Unknown,
            AlphaType::Unknown,
            None,
        )
    }

    /// Returns the pixel count in each row.
    // Port of: include/core/SkImageInfo.h#L367 (chrome/m156)
    #[must_use]
    pub fn width(&self) -> i32 {
        self.dimensions.width
    }

    /// Returns the pixel row count.
    // Port of: include/core/SkImageInfo.h#L372 (chrome/m156)
    #[must_use]
    pub fn height(&self) -> i32 {
        self.dimensions.height
    }

    /// The color type.
    // Port of: include/core/SkImageInfo.h#L374 (chrome/m156)
    #[doc(alias = "colorType")]
    #[must_use]
    pub fn color_type(&self) -> ColorType {
        self.color_info.color_type()
    }

    /// The alpha type.
    // Port of: include/core/SkImageInfo.h#L376 (chrome/m156)
    #[doc(alias = "alphaType")]
    #[must_use]
    pub fn alpha_type(&self) -> AlphaType {
        self.color_info.alpha_type()
    }

    /// The color space, or `None`.
    // Port of: src/core/SkImageInfo.cpp#L164-L166 (chrome/m156)
    #[doc(alias = "colorSpace")]
    #[doc(alias = "refColorSpace")]
    #[must_use]
    pub fn color_space(&self) -> Option<ColorSpace> {
        self.color_info.color_space()
    }

    /// Returns true if either dimension is zero or smaller.
    // Port of: include/core/SkImageInfo.h#L408 (chrome/m156)
    #[doc(alias = "isEmpty")]
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.dimensions.is_empty()
    }

    /// Returns the [`ColorInfo`]: the color type, alpha type, and color space of this
    /// [`ImageInfo`].
    // Port of: include/core/SkImageInfo.h#L413 (chrome/m156)
    #[doc(alias = "colorInfo")]
    #[must_use]
    pub fn color_info(&self) -> &ColorInfo {
        &self.color_info
    }

    /// Returns true if the alpha type is [`AlphaType::Opaque`] or the color type is always
    /// opaque.
    // Port of: include/core/SkImageInfo.h#L424 (chrome/m156)
    #[doc(alias = "isOpaque")]
    #[must_use]
    pub fn is_opaque(&self) -> bool {
        self.color_info.is_opaque()
    }

    /// Returns the integral size of [`Self::width()`] and [`Self::height()`].
    // Port of: include/core/SkImageInfo.h#L429 (chrome/m156)
    #[must_use]
    pub fn dimensions(&self) -> ISize {
        self.dimensions
    }

    /// Returns the integral rectangle from the origin to [`Self::width()`] and
    /// [`Self::height()`].
    // Port of: include/core/SkImageInfo.h#L434 (chrome/m156)
    #[must_use]
    pub fn bounds(&self) -> IRect {
        IRect::from_wh(self.dimensions.width, self.dimensions.height)
    }

    /// Returns true if the color space gamma is approximately the same as sRGB.
    // Port of: include/core/SkImageInfo.h#L444 (chrome/m156)
    #[doc(alias = "gammaCloseToSRGB")]
    #[must_use]
    pub fn is_gamma_close_to_srgb(&self) -> bool {
        self.color_info.is_gamma_close_to_srgb()
    }

    /// Creates an [`ImageInfo`] with the same [`ColorType`], [`ColorSpace`], and [`AlphaType`],
    /// with dimensions set to `new_width` and `new_height`.
    // Port of: include/core/SkImageInfo.h#L450-L452 (chrome/m156)
    #[doc(alias = "makeWH")]
    #[must_use]
    pub fn with_wh(&self, new_width: i32, new_height: i32) -> Self {
        Self::from_color_info((new_width, new_height), self.color_info.clone())
    }

    /// Creates an [`ImageInfo`] with the same [`ColorType`], [`ColorSpace`], and [`AlphaType`],
    /// with dimensions set to `new_dimensions`.
    // Port of: include/core/SkImageInfo.h#L460-L462 (chrome/m156)
    #[doc(alias = "makeDimensions")]
    #[must_use]
    pub fn with_dimensions(&self, new_dimensions: impl Into<ISize>) -> Self {
        Self::from_color_info(new_dimensions, self.color_info.clone())
    }

    /// Creates an [`ImageInfo`] with the same [`ColorType`], [`ColorSpace`], width, and height,
    /// with the alpha type set to `new_alpha_type`.
    // Port of: include/core/SkImageInfo.h#L472-L474 (chrome/m156)
    #[doc(alias = "makeAlphaType")]
    #[must_use]
    pub fn with_alpha_type(&self, new_alpha_type: AlphaType) -> Self {
        Self::from_color_info(
            self.dimensions,
            self.color_info.with_alpha_type(new_alpha_type),
        )
    }

    /// Creates an [`ImageInfo`] with the same [`AlphaType`], [`ColorSpace`], width, and height,
    /// with the color type set to `new_color_type`.
    // Port of: include/core/SkImageInfo.h#L481-L483 (chrome/m156)
    #[doc(alias = "makeColorType")]
    #[must_use]
    pub fn with_color_type(&self, new_color_type: ColorType) -> Self {
        Self::from_color_info(
            self.dimensions,
            self.color_info.with_color_type(new_color_type),
        )
    }

    /// Creates an [`ImageInfo`] with the same [`AlphaType`], [`ColorType`], width, and height,
    /// with the color space set to `new_color_space`. `new_color_space` may be `None`.
    // Port of: src/core/SkImageInfo.cpp#L168-L170 (chrome/m156)
    #[doc(alias = "makeColorSpace")]
    #[must_use]
    pub fn with_color_space(&self, new_color_space: impl Into<Option<ColorSpace>>) -> Self {
        Self::from_color_info(
            self.dimensions,
            self.color_info.with_color_space(new_color_space),
        )
    }

    /// Returns the number of bytes per pixel required by the color type. Returns zero if the color
    /// type is [`ColorType::Unknown`].
    // Port of: include/core/SkImageInfo.h#L500 (chrome/m156)
    #[doc(alias = "bytesPerPixel")]
    #[must_use]
    pub fn bytes_per_pixel(&self) -> usize {
        self.color_info.bytes_per_pixel()
    }

    /// Returns the bit shift converting row bytes to row pixels. Returns zero for
    /// [`ColorType::Unknown`]. One of: 0, 1, 2, 3, 4; left shift to convert pixels to bytes.
    // Port of: include/core/SkImageInfo.h#L507 (chrome/m156)
    #[doc(alias = "shiftPerPixel")]
    #[must_use]
    pub fn shift_per_pixel(&self) -> usize {
        self.color_info.shift_per_pixel()
    }

    /// Returns the minimum bytes per row, computed from the pixel width and the color type, which
    /// specifies bytes per pixel. A bitmap's maximum value for row bytes must fit in 31 bits.
    // Port of: include/core/SkImageInfo.h#L513-L515 (chrome/m156)
    #[doc(alias = "minRowBytes64")]
    #[must_use]
    pub fn min_row_bytes64(&self) -> u64 {
        // sk_64_mul(width, bytesPerPixel): the 64-bit product of two 32-bit ints.
        // bytes_per_pixel() is at most 16.
        (i64::from(self.width()) * i64::try_from(self.bytes_per_pixel()).unwrap_or(0))
            .cast_unsigned()
    }

    /// Returns the minimum bytes per row, computed from the pixel width and the color type, which
    /// specifies bytes per pixel. Returns zero if the result does not fit in 31 bits.
    // Port of: include/core/SkImageInfo.h#L523-L529 (chrome/m156)
    #[doc(alias = "minRowBytes")]
    #[must_use]
    #[allow(clippy::cast_possible_truncation)] // the value was just checked to fit in an i32
    pub fn min_row_bytes(&self) -> usize {
        let min_row_bytes = self.min_row_bytes64();
        if !t_fits_in::<i32, u64>(min_row_bytes) {
            return 0;
        }
        min_row_bytes as usize
    }

    /// Returns the byte offset of pixel (`x`, `y`) from the pixel base address.
    ///
    /// Asserts in debug builds if `x` or `y` is outside of bounds. Does not assert if `row_bytes`
    /// is smaller than [`Self::min_row_bytes()`], even though the result may be incorrect.
    // Port of: src/core/SkImageInfo.cpp#L143-L147 (chrome/m156)
    #[doc(alias = "computeOffset")]
    #[must_use]
    pub fn compute_offset(&self, point: impl Into<IPoint>, row_bytes: usize) -> usize {
        let IPoint { x, y } = point.into();
        debug_assert!(x >= 0 && x < self.width(), "x={x}; width={}", self.width());
        debug_assert!(
            y >= 0 && y < self.height(),
            "y={y}; height={}",
            self.height()
        );
        color_type_compute_offset(self.color_type(), x, y, row_bytes)
    }

    /// Returns the storage required by the pixel array, given the dimensions, color type, and
    /// `row_bytes`. `row_bytes` is assumed to be at least [`Self::min_row_bytes()`].
    ///
    /// Returns zero if the height is zero. Returns `usize::MAX` if the answer exceeds the range
    /// of `usize` (or of a signed 32-bit offset).
    // Port of: src/core/SkImageInfo.cpp#L149-L162 (chrome/m156)
    #[doc(alias = "computeByteSize")]
    #[must_use]
    #[allow(clippy::cast_sign_loss)] // mirrors the int -> size_t conversions of the C++
    pub fn compute_byte_size(&self, row_bytes: usize) -> usize {
        // constexpr size_t kMaxSigned32BitSize = SK_MaxS32;
        const MAX_SIGNED_32_BIT_SIZE: usize = i32::MAX as usize;
        if 0 == self.height() {
            return 0;
        }
        let mut safe = SafeMath::new();
        let h_minus_1 = safe.add_int(self.height(), -1);
        let a = safe.mul(h_minus_1 as usize, row_bytes);
        let b = safe.mul(self.width() as usize, self.bytes_per_pixel());
        let bytes = safe.add(a, b);

        // The CPU backend implements some memory operations on images using instructions that
        // take a signed 32-bit offset from the base. If we ever make an image larger than that,
        // overflow can cause us to read/write memory that starts 2GB *before* the buffer.
        // (crbug.com/1264705)
        if safe.ok() && bytes <= MAX_SIGNED_32_BIT_SIZE {
            bytes
        } else {
            usize::MAX
        }
    }

    /// Returns the least storage required by the pixel buffer, using [`Self::min_row_bytes()`] to
    /// compute the bytes for each pixel row.
    // Port of: include/core/SkImageInfo.h#L584-L586 (chrome/m156)
    #[doc(alias = "computeMinByteSize")]
    #[must_use]
    pub fn compute_min_byte_size(&self) -> usize {
        self.compute_byte_size(self.min_row_bytes())
    }

    /// Returns true if `byte_size` is the overflow sentinel returned by
    /// [`Self::compute_byte_size()`] and [`Self::compute_min_byte_size()`].
    // Port of: include/core/SkImageInfo.h#L594-L596 (chrome/m156)
    #[doc(alias = "ByteSizeOverflowed")]
    #[must_use]
    pub fn byte_size_overflowed(byte_size: usize) -> bool {
        usize::MAX == byte_size
    }

    /// Returns true if `row_bytes` is large enough to contain a pixel row and is properly
    /// aligned.
    // Port of: include/core/SkImageInfo.h#L604-L612 (chrome/m156)
    #[doc(alias = "validRowBytes")]
    #[must_use]
    pub fn valid_row_bytes(&self, row_bytes: usize) -> bool {
        if (row_bytes as u64) < self.min_row_bytes64() {
            return false;
        }
        let shift = self.shift_per_pixel();
        let aligned_row_bytes = row_bytes >> shift << shift;
        aligned_row_bytes == row_bytes
    }

    /// Creates an empty [`ImageInfo`] with [`ColorType::Unknown`], [`AlphaType::Unknown`], a width
    /// and height of zero, and no [`ColorSpace`].
    // Port of: include/core/SkImageInfo.h#L617 (chrome/m156)
    pub fn reset(&mut self) -> &mut Self {
        *self = Self::default();
        self
    }

    /// Asserts if internal values are illegal or inconsistent (debug builds only).
    // Port of: src/core/SkImageInfo.cpp#L231-L237 (chrome/m156)
    pub fn validate(&self) {
        debug_assert!(self.dimensions.width >= 0);
        debug_assert!(self.dimensions.height >= 0);
        debug_assert!(color_type_is_valid(self.color_type() as u32));
        debug_assert!(alpha_type_is_valid(self.alpha_type() as u32));
    }
}
