// Skia side of the CPU draw layer tests (task D5: skcpu::Draw / SkBitmapDevice): runs the case
// script crates/skia-rust-raster/src/draw_tests/cases.txt (generated by oracle/draw/gen_cases.py)
// through a real SkBitmapDevice (and, for `devmask` / `pathcov`, a directly built skcpu::Draw)
// and prints hashes of the pixels. The Rust test interprets the same script and must print the
// same lines.
//
// Build and run (Windows): oracle/draw/build.ps1 (one dump per CPU code path).
//
// SCRIPT GRAMMAR. Line oriented; blank lines and lines starting with '#' are ignored; tokens are
// separated by single spaces; floats are decimal text parsed with strtof; ints are decimal;
// colors are 8 hex digits AARRGGBB meaning an SkColor (unpremultiplied).
//
//   case NAME          start a case; state reset (no device, identity ctm, default SkPaint,
//                      fresh clip stack)
//   device W H CT AT CS [PAD]
//       CT: n32 a8 gray8 rgb565 argb4444 rgbaf16 rgbaf32 rgba1010102 (n32 = kN32_SkColorType)
//       AT: premul|opaque|unpremul; for color types that are always opaque (gray8, rgb565) the
//           alpha type is forced to opaque, as SkBitmapDevice::Create does. The SkBitmap then
//           canonicalises the alpha type (SkColorTypeValidateAlphaType, e.g. a8 unpremul ->
//           premul).
//       CS: srgb|linear|none (SkColorSpace::MakeSRGB / MakeSRGBLinear / nullptr)
//       PAD: extra pixels of row padding (default 0); rowBytes = (W + PAD) * bytesPerPixel.
//       The storage is zero-initialised and installed with SkBitmap::installPixels; the device is
//       `SkBitmapDevice(bitmap, SkSurfaceProps())`. If installPixels fails, prints `NAME skip`
//       and ignores the lines up to the next `case`.
//   erase AARRGGBB     bitmap.eraseColor(SkColor)
//   noise SEED         for every pixel (x, y) of the W x H area, k = y*W + x:
//                      bitmap.erase(SkColorSetARGB(R(SEED,3k)&255, R(SEED,3k+1)&255,
//                      R(SEED,3k+2)&255, (R(SEED,3k)>>8)&255), SkIRect::MakeXYWH(x, y, 1, 1))
//   save | restore     device->pushClipStack() / popClipStack() (restore without save: ignored)
//   ctm id | ctm M00 M01 M02 M10 M11 M12 M20 M21 M22
//                      device->setLocalToDevice(SkM44(SkMatrix::MakeAll(...)))
//   cliprect L T R B OP AA                       OP intersect|diff, AA 0|1
//   cliprrect L T R B RX RY OP AA                SkRRect::MakeRectXY
//   cliprrect4 L T R B X0 Y0 X1 Y1 X2 Y2 X3 Y3 OP AA   setRectRadii (UL UR LR LL)
//   clippath OP AA PATH
//   clipregion OP N L T R B ...                  union (SkRegion::op kUnion) of N int rects
//   replaceclip L T R B                          device->replaceClip(SkIRect)
//   paint KEY=VALUE ...    the current paint becomes a fresh SkPaint with the keys applied in
//                          order. Keys: color=AARRGGBB aa=0|1 dither=0|1
//                          style=fill|stroke|strokefill width=F cap=butt|round|square
//                          join=miter|round|bevel miter=F blend=N (SkBlendMode 0..28)
//                          shader=solid:AARRGGBB (SkShaders::Color)
//                          pe=dash:I0,I1,...@PHASE (SkDashPathEffect::Make)
//                          pe=corner:R (SkCornerPathEffect::Make)
//                          pe=sum_dash_corner:ON,OFF@PHASE:R  (MakeSum(dash, corner))
//                          pe=compose_corner_dash:ON,OFF@PHASE:R (MakeCompose(corner, dash))
//   drawpaint
//   rect L T R B | oval L T R B | rrect L T R B RX RY
//   rrect4 L T R B X0 Y0 X1 Y1 X2 Y2 X3 Y3
//   drrect oL oT oR oB oRX oRY iL iT iR iB iRX iRY   (both MakeRectXY) device->drawDRRect
//   region N L T R B ...                         device->drawRegion(union of N int rects)
//   path PATH                                    device->drawPath
//   points MODE N X Y ...                        MODE points|lines|polygon
//   devmask CLIP FMT ML MT MR MB SEED
//       skcpu::Draw on the device's pixels (accessPixels), fCTM = &device->localToDevice(),
//       fRC = SkRasterClip from CLIP, fProps = nullptr; draw.drawDevMask(mask, paint, nullptr).
//       CLIP: rect:L,T,R,B (ints, SkRasterClip(SkIRect)) or oval:L,T,R,B (floats,
//       SkRasterClip(SkPath::Oval(rect), SkIRect(0,0,W,H), true)).
//       FMT a8|bw|lcd16; bounds (ML,MT,MR,MB); rowBytes = a8: align4(w), bw: align4((w+7)>>3),
//       lcd16: align4(w*2); byte i of the image (i < rowBytes*h) = R(SEED, i) & 0xFF (lcd16
//       values are little-endian pairs of these bytes).
//   pathcov CLIP PATH  same Draw; draw.drawPathCoverage(path, paint) (a8 devices only)
//   hash LABEL         prints `NAME LABEL HASH`
//   query LABEL        prints `NAME LABEL q empty=E rect=R aa=A wide=W bounds=L,T,R,B`
//                      (isClipEmpty, isClipRect, isClipAntiAliased, isClipWideOpen,
//                      devClipBounds)
//   readpixels LABEL X Y W H CT AT CS
//       dst pixmap (rowBytes = W*bpp, bytes initialised to 0xA5), ok = device->readPixels(dst,
//       X, Y); prints `NAME LABEL rp ok=0|1 HASH` (HASH of the dst, also when !ok)
//   writepixels LABEL X Y W H CT AT CS SEED
//       src bitmap (zeroed storage, rowBytes = W*bpp, then `noise SEED` on it), ok =
//       device->writePixels(src.pixmap(), X, Y); prints `NAME LABEL wp ok=0|1`
//   end                prints `NAME end HASH`
//
// PATH = FILL VERB...: FILL w|e|iw|ie (winding, evenodd, inverse winding, inverse evenodd), verbs
// `M x y`, `L x y`, `Q x1 y1 x y`, `K x1 y1 x y w` (conic), `C x1 y1 x2 y2 x y`, `Z`; built with
// SkPathBuilder (setFillType, the verbs, detach()).
//
// HASH: FNV-1a 64 (offset 0xcbf29ce484222325, prime 0x100000001b3) over the W x H pixels row by
// row, without row padding, printed as 16 lowercase hex digits. n32 pixels contribute the bytes
// A, R, G, B (SkGetPackedA32/R32/G32/B32), so the hash does not depend on the N32 byte order;
// other color types contribute their stored bytes (little endian).
//
// R(seed, k) = hash32(seed * 0x9E3779B1 + k * 0x85EBCA77 + 0x165667B1) (uint32 wrap-around),
// hash32 as in oracle/rp-builder/d4_blitters.cpp.

#include "include/core/SkAlphaType.h"
#include "include/core/SkBitmap.h"
#include "include/core/SkBlendMode.h"
#include "include/core/SkClipOp.h"
#include "include/core/SkColor.h"
#include "include/core/SkColorSpace.h"
#include "include/core/SkColorType.h"
#include "include/core/SkGraphics.h"
#include "include/core/SkImageInfo.h"
#include "include/core/SkM44.h"
#include "include/core/SkMatrix.h"
#include "include/core/SkPaint.h"
#include "include/core/SkPath.h"
#include "include/core/SkPathBuilder.h"
#include "include/core/SkPathEffect.h"
#include "include/core/SkPixmap.h"
#include "include/core/SkRRect.h"
#include "include/core/SkRect.h"
#include "include/core/SkRegion.h"
#include "include/core/SkShader.h"
#include "include/core/SkSurfaceProps.h"
#include "include/effects/SkCornerPathEffect.h"
#include "include/effects/SkDashPathEffect.h"
#include "src/core/SkBitmapDevice.h"
#include "src/core/SkColorPriv.h"
#include "src/core/SkDraw.h"
#include "src/core/SkMask.h"
#include "src/core/SkRasterClip.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

#if defined(_WIN32)
#include <fcntl.h>
#include <io.h>
#endif

// ---- deterministic inputs ------------------------------------------------------------------

static uint32_t hash32(uint32_t i) {
    i ^= i >> 16;
    i *= 0x7feb352du;
    i ^= i >> 15;
    i *= 0x846ca68bu;
    i ^= i >> 16;
    return i;
}
static uint32_t R(uint32_t seed, uint32_t k) {
    return hash32(seed * 0x9E3779B1u + k * 0x85EBCA77u + 0x165667B1u);
}

// ---- errors --------------------------------------------------------------------------------

static int gLine = 0;
[[noreturn]] static void fail(const std::string& msg) {
    fprintf(stderr, "draw: line %d: %s\n", gLine, msg.c_str());
    fflush(stdout);
    exit(2);
}

// ---- tokens --------------------------------------------------------------------------------

struct Toks {
    std::vector<std::string> t;
    size_t i = 0;
    bool done() const { return i >= t.size(); }
    const std::string& word() {
        if (i >= t.size()) fail("missing token");
        return t[i++];
    }
    float f() { return strtof(word().c_str(), nullptr); }
    int n() { return (int)strtol(word().c_str(), nullptr, 10); }
    uint32_t u() { return (uint32_t)strtoul(word().c_str(), nullptr, 10); }
    SkColor color() { return (SkColor)strtoul(word().c_str(), nullptr, 16); }
    SkRect rect() {
        float l = f(), t_ = f(), r = f(), b = f();
        return SkRect::MakeLTRB(l, t_, r, b);
    }
    SkIRect irect() {
        int l = n(), t_ = n(), r = n(), b = n();
        return SkIRect::MakeLTRB(l, t_, r, b);
    }
    SkClipOp op() {
        const std::string& w = word();
        if (w == "intersect") return SkClipOp::kIntersect;
        if (w == "diff") return SkClipOp::kDifference;
        fail("bad clip op " + w);
    }
    bool flag() { return n() != 0; }
};

static std::vector<std::string> split(const std::string& s, char sep) {
    std::vector<std::string> out;
    std::string cur;
    for (char c : s) {
        if (c == sep) {
            out.push_back(cur);
            cur.clear();
        } else {
            cur += c;
        }
    }
    out.push_back(cur);
    return out;
}

static SkColorType parseCT(const std::string& s) {
    if (s == "n32") return kN32_SkColorType;
    if (s == "a8") return kAlpha_8_SkColorType;
    if (s == "gray8") return kGray_8_SkColorType;
    if (s == "rgb565") return kRGB_565_SkColorType;
    if (s == "argb4444") return kARGB_4444_SkColorType;
    if (s == "rgbaf16") return kRGBA_F16_SkColorType;
    if (s == "rgbaf32") return kRGBA_F32_SkColorType;
    if (s == "rgba1010102") return kRGBA_1010102_SkColorType;
    fail("bad color type " + s);
}
static SkAlphaType parseAT(const std::string& s) {
    if (s == "premul") return kPremul_SkAlphaType;
    if (s == "opaque") return kOpaque_SkAlphaType;
    if (s == "unpremul") return kUnpremul_SkAlphaType;
    fail("bad alpha type " + s);
}
static sk_sp<SkColorSpace> parseCS(const std::string& s) {
    if (s == "srgb") return SkColorSpace::MakeSRGB();
    if (s == "linear") return SkColorSpace::MakeSRGBLinear();
    if (s == "none") return nullptr;
    fail("bad color space " + s);
}

// PATH = FILL VERB... (the rest of the tokens).
static SkPath parsePath(Toks& in) {
    SkPathBuilder b;
    const std::string& fill = in.word();
    if (fill == "w") b.setFillType(SkPathFillType::kWinding);
    else if (fill == "e") b.setFillType(SkPathFillType::kEvenOdd);
    else if (fill == "iw") b.setFillType(SkPathFillType::kInverseWinding);
    else if (fill == "ie") b.setFillType(SkPathFillType::kInverseEvenOdd);
    else fail("bad fill type " + fill);
    while (!in.done()) {
        const std::string v = in.word();
        if (v == "M") {
            float x = in.f(), y = in.f();
            b.moveTo(x, y);
        } else if (v == "L") {
            float x = in.f(), y = in.f();
            b.lineTo(x, y);
        } else if (v == "Q") {
            float x1 = in.f(), y1 = in.f(), x = in.f(), y = in.f();
            b.quadTo(x1, y1, x, y);
        } else if (v == "K") {
            float x1 = in.f(), y1 = in.f(), x = in.f(), y = in.f(), w = in.f();
            b.conicTo(x1, y1, x, y, w);
        } else if (v == "C") {
            float x1 = in.f(), y1 = in.f(), x2 = in.f(), y2 = in.f(), x = in.f(), y = in.f();
            b.cubicTo(x1, y1, x2, y2, x, y);
        } else if (v == "Z") {
            b.close();
        } else {
            fail("bad verb " + v);
        }
    }
    return b.detach();
}

static SkRegion parseRegion(Toks& in) {
    int n = in.n();
    SkRegion rgn;
    for (int i = 0; i < n; ++i) {
        rgn.op(in.irect(), SkRegion::kUnion_Op);
    }
    return rgn;
}

static SkRRect rrect4(Toks& in) {
    SkRect r = in.rect();
    SkVector radii[4];
    for (SkVector& v : radii) {
        float x = in.f(), y = in.f();
        v = {x, y};
    }
    SkRRect rr;
    rr.setRectRadii(r, radii);
    return rr;
}

static SkRRect rrectXY(Toks& in) {
    SkRect r = in.rect();
    float rx = in.f(), ry = in.f();
    return SkRRect::MakeRectXY(r, rx, ry);
}

// "on,off,...@phase"
static sk_sp<SkPathEffect> dash(const std::string& spec) {
    auto at = split(spec, '@');
    if (at.size() != 2) fail("bad dash " + spec);
    std::vector<float> iv;
    for (const std::string& s : split(at[0], ',')) iv.push_back(strtof(s.c_str(), nullptr));
    return SkDashPathEffect::Make(SkSpan<const SkScalar>(iv.data(), iv.size()),
                                  strtof(at[1].c_str(), nullptr));
}

static SkPaint parsePaint(Toks& in) {
    SkPaint p;
    while (!in.done()) {
        const std::string kv = in.word();
        size_t eq = kv.find('=');
        if (eq == std::string::npos) fail("bad paint key " + kv);
        std::string k = kv.substr(0, eq), v = kv.substr(eq + 1);
        if (k == "color") {
            p.setColor((SkColor)strtoul(v.c_str(), nullptr, 16));
        } else if (k == "aa") {
            p.setAntiAlias(v != "0");
        } else if (k == "dither") {
            p.setDither(v != "0");
        } else if (k == "style") {
            if (v == "fill") p.setStyle(SkPaint::kFill_Style);
            else if (v == "stroke") p.setStyle(SkPaint::kStroke_Style);
            else if (v == "strokefill") p.setStyle(SkPaint::kStrokeAndFill_Style);
            else fail("bad style " + v);
        } else if (k == "width") {
            p.setStrokeWidth(strtof(v.c_str(), nullptr));
        } else if (k == "cap") {
            if (v == "butt") p.setStrokeCap(SkPaint::kButt_Cap);
            else if (v == "round") p.setStrokeCap(SkPaint::kRound_Cap);
            else if (v == "square") p.setStrokeCap(SkPaint::kSquare_Cap);
            else fail("bad cap " + v);
        } else if (k == "join") {
            if (v == "miter") p.setStrokeJoin(SkPaint::kMiter_Join);
            else if (v == "round") p.setStrokeJoin(SkPaint::kRound_Join);
            else if (v == "bevel") p.setStrokeJoin(SkPaint::kBevel_Join);
            else fail("bad join " + v);
        } else if (k == "miter") {
            p.setStrokeMiter(strtof(v.c_str(), nullptr));
        } else if (k == "blend") {
            int m = atoi(v.c_str());
            if (m < 0 || m > (int)SkBlendMode::kLastMode) fail("bad blend " + v);
            p.setBlendMode(static_cast<SkBlendMode>(m));
        } else if (k == "shader") {
            if (v.rfind("solid:", 0) != 0) fail("bad shader " + v);
            p.setShader(SkShaders::Color((SkColor)strtoul(v.c_str() + 6, nullptr, 16)));
        } else if (k == "pe") {
            size_t c = v.find(':');
            if (c == std::string::npos) fail("bad pe " + v);
            std::string kind = v.substr(0, c), rest = v.substr(c + 1);
            if (kind == "dash") {
                p.setPathEffect(dash(rest));
            } else if (kind == "corner") {
                p.setPathEffect(SkCornerPathEffect::Make(strtof(rest.c_str(), nullptr)));
            } else if (kind == "sum_dash_corner" || kind == "compose_corner_dash") {
                size_t c2 = rest.rfind(':');
                if (c2 == std::string::npos) fail("bad pe " + v);
                auto d = dash(rest.substr(0, c2));
                auto corner = SkCornerPathEffect::Make(strtof(rest.c_str() + c2 + 1, nullptr));
                if (kind == "sum_dash_corner") {
                    p.setPathEffect(SkPathEffect::MakeSum(d, corner));
                } else {
                    p.setPathEffect(SkPathEffect::MakeCompose(corner, d));
                }
            } else {
                fail("bad pe " + v);
            }
        } else {
            fail("bad paint key " + kv);
        }
    }
    return p;
}

// ---- hashing -------------------------------------------------------------------------------

static uint64_t hashPixels(const SkPixmap& pm) {
    uint64_t h = 0xcbf29ce484222325ull;
    // Debugging aid: DRAW_PIXELS=1 also prints the hashed bytes (hex, to stderr).
    static const bool dumpPixels = getenv("DRAW_PIXELS") != nullptr;
    auto byte = [&h](uint8_t b) {
        h ^= b;
        h *= 0x100000001b3ull;
        if (dumpPixels) fprintf(stderr, "%02x", b);
    };
    const int bpp = pm.info().bytesPerPixel();
    const bool n32 = pm.colorType() == kN32_SkColorType;
    for (int y = 0; y < pm.height(); ++y) {
        const uint8_t* row = (const uint8_t*)pm.addr() + (size_t)y * pm.rowBytes();
        if (n32) {
            for (int x = 0; x < pm.width(); ++x) {
                uint32_t c;
                memcpy(&c, row + (size_t)x * 4, 4);
                byte(SkGetPackedA32(c));
                byte(SkGetPackedR32(c));
                byte(SkGetPackedG32(c));
                byte(SkGetPackedB32(c));
            }
        } else {
            for (size_t i = 0; i < (size_t)pm.width() * bpp; ++i) byte(row[i]);
        }
    }
    return h;
}

static void noise(const SkBitmap& bm, uint32_t seed) {
    const int w = bm.width(), h = bm.height();
    for (int y = 0; y < h; ++y) {
        for (int x = 0; x < w; ++x) {
            uint32_t k = (uint32_t)(y * w + x);
            uint32_t r0 = R(seed, 3 * k);
            SkColor c = SkColorSetARGB(r0 & 0xFF, R(seed, 3 * k + 1) & 0xFF,
                                       R(seed, 3 * k + 2) & 0xFF, (r0 >> 8) & 0xFF);
            bm.erase(c, SkIRect::MakeXYWH(x, y, 1, 1));
        }
    }
}

// ---- case state ----------------------------------------------------------------------------

struct Case {
    std::string name;
    bool skipping = false;
    std::vector<uint8_t> storage;
    SkBitmap bitmap;
    sk_sp<SkBitmapDevice> device;
    SkPaint paint;
    int saves = 0;

    void reset() {
        device.reset();
        bitmap.reset();
        storage.clear();
        storage.shrink_to_fit();
        paint = SkPaint();
        saves = 0;
        skipping = false;
    }
    SkPixmap pixmap() const { return bitmap.pixmap(); }
};

static std::unique_ptr<SkRasterClip> parseDrawClip(const std::string& spec, const Case& c) {
    size_t colon = spec.find(':');
    if (colon == std::string::npos) fail("bad clip " + spec);
    std::string kind = spec.substr(0, colon);
    auto parts = split(spec.substr(colon + 1), ',');
    if (parts.size() != 4) fail("bad clip " + spec);
    if (kind == "rect") {
        int v[4];
        for (int i = 0; i < 4; ++i) v[i] = (int)strtol(parts[i].c_str(), nullptr, 10);
        return std::make_unique<SkRasterClip>(SkIRect::MakeLTRB(v[0], v[1], v[2], v[3]));
    }
    if (kind == "oval") {
        float v[4];
        for (int i = 0; i < 4; ++i) v[i] = strtof(parts[i].c_str(), nullptr);
        return std::make_unique<SkRasterClip>(SkPath::Oval(SkRect::MakeLTRB(v[0], v[1], v[2], v[3])),
                            SkIRect::MakeWH(c.bitmap.width(), c.bitmap.height()), true);
    }
    fail("bad clip " + spec);
}

static size_t align4(size_t v) { return (v + 3) & ~(size_t)3; }

int main(int argc, char** argv) {
    SkGraphics::Init();  // applies SKIA_ORACLE_CPU_CAP
#if defined(_WIN32)
    _setmode(_fileno(stdout), _O_BINARY);  // LF line endings
#endif
    static char outBuf[1 << 16];
    setvbuf(stdout, outBuf, _IOFBF, sizeof(outBuf));
    if (argc < 2) {
        fprintf(stderr, "usage: draw <cases.txt>\n");
        return 1;
    }
    std::ifstream file(argv[1], std::ios::binary);
    if (!file) {
        fprintf(stderr, "draw: cannot open %s\n", argv[1]);
        return 1;
    }
    Case c;
    bool inCase = false;
    std::string line;
    while (std::getline(file, line)) {
        ++gLine;
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty() || line[0] == '#') continue;
        Toks in;
        {
            std::istringstream ss(line);
            std::string w;
            while (ss >> w) in.t.push_back(w);
        }
        if (in.t.empty()) continue;
        const std::string cmd = in.word();

        if (cmd == "case") {
            c.reset();
            c.name = in.word();
            inCase = true;
            // Debugging aid: DRAW_ONLY=<case name> runs a single case.
            static const char* only = getenv("DRAW_ONLY");
            if (only && c.name != only) c.skipping = true;
            continue;
        }
        if (!inCase) fail("command outside a case: " + cmd);
        if (c.skipping) {
            if (cmd == "end") inCase = false;
            continue;
        }
        if (cmd == "device") {
            int w = in.n(), h = in.n();
            SkColorType ct = parseCT(in.word());
            SkAlphaType at = parseAT(in.word());
            sk_sp<SkColorSpace> cs = parseCS(in.word());
            int pad = in.done() ? 0 : in.n();
            if (SkColorTypeIsAlwaysOpaque(ct)) at = kOpaque_SkAlphaType;
            SkImageInfo info = SkImageInfo::Make(w, h, ct, at, std::move(cs));
            size_t rb = (size_t)(w + pad) * info.bytesPerPixel();
            c.device.reset();
            c.bitmap.reset();
            c.storage.assign(std::max<size_t>(1, rb * (size_t)std::max(h, 0)), 0);
            if (w <= 0 || h <= 0 || pad < 0 ||
                !c.bitmap.installPixels(info, c.storage.data(), rb)) {
                printf("%s skip\n", c.name.c_str());
                c.skipping = true;
                continue;
            }
            c.device = sk_make_sp<SkBitmapDevice>(c.bitmap, SkSurfaceProps());
            continue;
        }
        if (!c.device) fail("no device for " + cmd);
        SkBitmapDevice* dev = c.device.get();

        if (cmd == "end") {
            printf("%s end %016llx\n", c.name.c_str(), (unsigned long long)hashPixels(c.pixmap()));
            while (c.saves > 0) {
                dev->popClipStack();
                --c.saves;
            }
            c.reset();
            inCase = false;
        } else if (cmd == "erase") {
            c.bitmap.eraseColor(in.color());
        } else if (cmd == "noise") {
            noise(c.bitmap, in.u());
        } else if (cmd == "save") {
            dev->pushClipStack();
            ++c.saves;
        } else if (cmd == "restore") {
            if (c.saves > 0) {
                dev->popClipStack();
                --c.saves;
            }
        } else if (cmd == "ctm") {
            if (in.t.size() == 2 && in.t[1] == "id") {
                dev->setLocalToDevice(SkM44());
            } else {
                float v[9];
                for (float& f : v) f = in.f();
                dev->setLocalToDevice(
                        SkM44(SkMatrix::MakeAll(v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7], v[8])));
            }
        } else if (cmd == "cliprect") {
            SkRect r = in.rect();
            SkClipOp op = in.op();
            dev->clipRect(r, op, in.flag());
        } else if (cmd == "cliprrect") {
            SkRRect rr = rrectXY(in);
            SkClipOp op = in.op();
            dev->clipRRect(rr, op, in.flag());
        } else if (cmd == "cliprrect4") {
            SkRRect rr = rrect4(in);
            SkClipOp op = in.op();
            dev->clipRRect(rr, op, in.flag());
        } else if (cmd == "clippath") {
            SkClipOp op = in.op();
            bool aa = in.flag();
            dev->clipPath(parsePath(in), op, aa);
        } else if (cmd == "clipregion") {
            SkClipOp op = in.op();
            dev->clipRegion(parseRegion(in), op);
        } else if (cmd == "replaceclip") {
            dev->replaceClip(in.irect());
        } else if (cmd == "paint") {
            c.paint = parsePaint(in);
        } else if (cmd == "drawpaint") {
            dev->drawPaint(c.paint);
        } else if (cmd == "rect") {
            dev->drawRect(in.rect(), c.paint);
        } else if (cmd == "oval") {
            dev->drawOval(in.rect(), c.paint);
        } else if (cmd == "rrect") {
            dev->drawRRect(rrectXY(in), c.paint);
        } else if (cmd == "rrect4") {
            dev->drawRRect(rrect4(in), c.paint);
        } else if (cmd == "drrect") {
            SkRRect outer = rrectXY(in);
            SkRRect inner = rrectXY(in);
            dev->drawDRRect(outer, inner, c.paint);
        } else if (cmd == "region") {
            dev->drawRegion(parseRegion(in), c.paint);
        } else if (cmd == "path") {
            dev->drawPath(parsePath(in), c.paint);
        } else if (cmd == "points") {
            const std::string m = in.word();
            SkCanvas::PointMode mode;
            if (m == "points") mode = SkCanvas::kPoints_PointMode;
            else if (m == "lines") mode = SkCanvas::kLines_PointMode;
            else if (m == "polygon") mode = SkCanvas::kPolygon_PointMode;
            else fail("bad point mode " + m);
            int n = in.n();
            std::vector<SkPoint> pts(n);
            for (SkPoint& p : pts) {
                float x = in.f(), y = in.f();
                p = {x, y};
            }
            dev->drawPoints(mode, SkSpan<const SkPoint>(pts.data(), pts.size()), c.paint);
        } else if (cmd == "devmask" || cmd == "pathcov") {
            std::unique_ptr<SkRasterClip> rc = parseDrawClip(in.word(), c);
            SkPixmap pm;
            if (!dev->accessPixels(&pm)) fail("accessPixels failed");
            skcpu::Draw draw;
            draw.fDst = pm;
            draw.fCTM = &dev->localToDevice();
            draw.fRC = rc.get();
            draw.fProps = nullptr;
            if (cmd == "devmask") {
                const std::string fmt = in.word();
                SkIRect b = in.irect();
                uint32_t seed = in.u();
                SkMask::Format f;
                size_t rb;
                const size_t w = (size_t)std::max(0, b.width());
                if (fmt == "a8") {
                    f = SkMask::kA8_Format;
                    rb = align4(w);
                } else if (fmt == "bw") {
                    f = SkMask::kBW_Format;
                    rb = align4((w + 7) >> 3);
                } else if (fmt == "lcd16") {
                    f = SkMask::kLCD16_Format;
                    rb = align4(w * 2);
                } else {
                    fail("bad mask format " + fmt);
                }
                size_t size = rb * (size_t)std::max(0, b.height());
                std::vector<uint8_t> img(std::max<size_t>(size, 4));
                for (size_t i = 0; i < size; ++i) img[i] = R(seed, (uint32_t)i) & 0xFF;
                SkMask mask(img.data(), b, rb, f);
                draw.drawDevMask(mask, c.paint, nullptr);
            } else {
                draw.drawPathCoverage(parsePath(in), c.paint);
            }
        } else if (cmd == "hash") {
            const std::string label = in.word();
            printf("%s %s %016llx\n", c.name.c_str(), label.c_str(),
                   (unsigned long long)hashPixels(c.pixmap()));
        } else if (cmd == "query") {
            const std::string label = in.word();
            SkIRect b = dev->devClipBounds();
            printf("%s %s q empty=%d rect=%d aa=%d wide=%d bounds=%d,%d,%d,%d\n", c.name.c_str(),
                   label.c_str(), dev->isClipEmpty(), dev->isClipRect(), dev->isClipAntiAliased(),
                   dev->isClipWideOpen(), b.fLeft, b.fTop, b.fRight, b.fBottom);
        } else if (cmd == "readpixels" || cmd == "writepixels") {
            const std::string label = in.word();
            int x = in.n(), y = in.n(), w = in.n(), h = in.n();
            SkColorType ct = parseCT(in.word());
            SkAlphaType at = parseAT(in.word());
            sk_sp<SkColorSpace> cs = parseCS(in.word());
            if (w <= 0 || h <= 0) fail("bad pixels size");
            SkImageInfo info = SkImageInfo::Make(w, h, ct, at, std::move(cs));
            size_t rb = (size_t)w * info.bytesPerPixel();
            if (cmd == "readpixels") {
                std::vector<uint8_t> px(rb * h, 0xA5);
                SkPixmap dst(info, px.data(), rb);
                bool ok = dev->readPixels(dst, x, y);
                printf("%s %s rp ok=%d %016llx\n", c.name.c_str(), label.c_str(), ok ? 1 : 0,
                       (unsigned long long)hashPixels(dst));
            } else {
                uint32_t seed = in.u();
                std::vector<uint8_t> px(rb * h, 0);
                SkBitmap src;
                if (!src.installPixels(info, px.data(), rb)) fail("bad writepixels source");
                noise(src, seed);
                bool ok = dev->writePixels(src.pixmap(), x, y);
                printf("%s %s wp ok=%d\n", c.name.c_str(), label.c_str(), ok ? 1 : 0);
            }
        } else {
            fail("unknown command " + cmd);
        }
    }
    fflush(stdout);
    return 0;
}
