// Copyright 2014 Google Inc.
// Copyright 2026 The skia-rust Authors
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.
// Port of: gm/concavepaths.cpp (chrome/m156)

use crate::prelude::*;
use skia_rust_core::paint::{Paint, Style};
use skia_rust_core::path::Path;
use skia_rust_core::path_builder::PathBuilder;
use skia_rust_core::path_types::PathFillType;
use skia_rust_core::point::Point;

fn p(x: f32, y: f32) -> Point {
    Point::new(x, y)
}

// Concave test
// Port of: gm/concavepaths.cpp#L24-L28 (chrome/m156)
fn test_concave(canvas: &Canvas, paint: &Paint) {
    canvas.translate((0.0, 0.0));
    canvas.draw_path(
        &Path::polygon(
            &[p(20.0, 20.0), p(80.0, 20.0), p(30.0, 30.0), p(20.0, 80.0)],
            false,
            None,
            None,
        ),
        paint,
    );
}

// Reverse concave test
// Port of: gm/concavepaths.cpp#L31-L37 (chrome/m156)
fn test_reverse_concave(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((100.0, 0.0));
    canvas.draw_path(
        &Path::polygon(
            &[p(20.0, 20.0), p(20.0, 80.0), p(30.0, 30.0), p(80.0, 20.0)],
            false,
            None,
            None,
        ),
        paint,
    );
    canvas.restore();
}

// Bowtie (intersection)
// Port of: gm/concavepaths.cpp#L40-L46 (chrome/m156)
fn test_bowtie(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((200.0, 0.0));
    canvas.draw_path(
        &Path::polygon(
            &[p(20.0, 20.0), p(80.0, 80.0), p(80.0, 20.0), p(20.0, 80.0)],
            false,
            None,
            None,
        ),
        paint,
    );
    canvas.restore();
}

// "fake" bowtie (concave, but no intersection)
// Port of: gm/concavepaths.cpp#L49-L55 (chrome/m156)
fn test_fake_bowtie(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((300.0, 0.0));
    canvas.draw_path(
        &Path::polygon(
            &[
                p(20.0, 20.0),
                p(50.0, 40.0),
                p(80.0, 20.0),
                p(80.0, 80.0),
                p(50.0, 60.0),
                p(20.0, 80.0),
            ],
            false,
            None,
            None,
        ),
        paint,
    );
    canvas.restore();
}

// Bowtie with a smaller right hand lobe. The outer vertex of the left hand
// lobe intrudes into the interior of the right hand lobe.
// Port of: gm/concavepaths.cpp#L59-L66 (chrome/m156)
fn test_intruding_vertex(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((400.0, 0.0));
    canvas.draw_path(
        &Path::polygon(
            &[
                p(20.0, 20.0),
                p(50.0, 50.0),
                p(68.0, 20.0),
                p(68.0, 80.0),
                p(50.0, 50.0),
                p(20.0, 80.0),
            ],
            false,
            PathFillType::Winding,
            true,
        ),
        paint,
    );
    canvas.restore();
}

// A shape with an edge that becomes inverted on AA stroking and that also contains
// a repeated start/end vertex.
// Port of: gm/concavepaths.cpp#L70-L79 (chrome/m156)
fn test_inversion_repeat_vertex(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((400.0, 100.0));
    let pts = [
        p(80.0, 50.0),
        p(40.0, 80.0),
        p(60.0, 20.0),
        p(20.0, 20.0),
        p(39.99, 80.0),
        p(80.0, 50.0),
    ];
    canvas.draw_path(
        &Path::polygon(&pts, false, PathFillType::Winding, true),
        paint,
    );
    canvas.restore();
}

// Fish test (intersection/concave)
// Port of: gm/concavepaths.cpp#L82-L88 (chrome/m156)
fn test_fish(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((0.0, 100.0));
    canvas.draw_path(
        &Path::polygon(
            &[
                p(20.0, 20.0),
                p(80.0, 80.0),
                p(70.0, 50.0),
                p(80.0, 20.0),
                p(20.0, 80.0),
                p(0.0, 50.0),
            ],
            false,
            PathFillType::Winding,
            true,
        ),
        paint,
    );
    canvas.restore();
}

// Overlapping "Fast-forward" icon: tests coincidence of inner and outer
// vertices generated by intersection.
// Port of: gm/concavepaths.cpp#L92-L100 (chrome/m156)
fn test_fast_forward(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((100.0, 100.0));
    let path = PathBuilder::new()
        .add_polygon(&[p(20.0, 20.0), p(60.0, 50.0), p(20.0, 80.0)], false)
        .add_polygon(&[p(40.0, 20.0), p(40.0, 80.0), p(80.0, 50.0)], false)
        .detach();
    canvas.draw_path(&path, paint);
    canvas.restore();
}

// Square polygon with a square hole.
// Port of: gm/concavepaths.cpp#L103-L111 (chrome/m156)
fn test_hole(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((200.0, 100.0));
    let path = PathBuilder::new()
        .add_polygon(
            &[p(20.0, 20.0), p(80.0, 20.0), p(80.0, 80.0), p(20.0, 80.0)],
            false,
        )
        .add_polygon(
            &[p(30.0, 30.0), p(30.0, 70.0), p(70.0, 70.0), p(70.0, 30.0)],
            false,
        )
        .detach();
    canvas.draw_path(&path, paint);
    canvas.restore();
}

// Star test (self-intersecting)
// Port of: gm/concavepaths.cpp#L114-L121 (chrome/m156)
fn test_star(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((300.0, 100.0));
    canvas.draw_path(
        &Path::polygon(
            &[
                p(30.0, 20.0),
                p(50.0, 80.0),
                p(70.0, 20.0),
                p(20.0, 57.0),
                p(80.0, 57.0),
            ],
            false,
            None,
            None,
        ),
        paint,
    );
    canvas.restore();
}

// Exercise a case where the intersection is below a bottom edge.
// Port of: gm/concavepaths.cpp#L124-L136 (chrome/m156)
#[allow(clippy::excessive_precision)] // the C++ literals, digit for digit
fn test_twist(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((420.0, 220.0));
    canvas.scale((10.0, 10.0));
    let pts = [
        p(0.5, 6.0),
        p(5.807_039_260_864_257_812_5, 6.461_266_040_802_001_953_1),
        p(-2.918_688_535_690_307_617_2, 2.811_046_600_341_796_875),
        p(0.499_999_940_395_355_224_61, -1.412_403_821_945_190_429_7),
    ];
    canvas.draw_path(&Path::polygon(&pts, false, None, None), paint);
    canvas.restore();
}

// Stairstep with repeated vert (intersection)
// Port of: gm/concavepaths.cpp#L139-L146 (chrome/m156)
fn test_stairstep(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((0.0, 200.0));
    canvas.draw_path(
        &Path::polygon(
            &[
                p(50.0, 50.0),
                p(50.0, 20.0),
                p(80.0, 20.0),
                p(50.0, 50.0),
                p(20.0, 50.0),
                p(20.0, 80.0),
            ],
            false,
            None,
            None,
        ),
        paint,
    );
    canvas.restore();
}

// Port of: gm/concavepaths.cpp#L148-L154 (chrome/m156)
fn test_stairstep2(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((100.0, 200.0));
    canvas.draw_path(
        &Path::polygon(
            &[
                p(20.0, 60.0),
                p(35.0, 80.0),
                p(50.0, 60.0),
                p(65.0, 80.0),
                p(80.0, 60.0),
            ],
            false,
            None,
            None,
        ),
        paint,
    );
    canvas.restore();
}

// Overlapping segments
// Port of: gm/concavepaths.cpp#L157-L163 (chrome/m156)
fn test_overlapping(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((200.0, 200.0));
    canvas.draw_path(
        &Path::polygon(
            &[p(20.0, 80.0), p(80.0, 80.0), p(80.0, 20.0), p(80.0, 30.0)],
            false,
            None,
            None,
        ),
        paint,
    );
    canvas.restore();
}

// Two "island" triangles inside a containing rect.
// This exercises the partnering code in the tessellator.
// Port of: gm/concavepaths.cpp#L167-L176 (chrome/m156)
fn test_partners(canvas: &Canvas, paint: &Paint) {
    canvas.save();
    canvas.translate((300.0, 200.0));
    let path = PathBuilder::new()
        .add_polygon(
            &[p(20.0, 80.0), p(80.0, 80.0), p(80.0, 20.0), p(20.0, 20.0)],
            false,
        )
        .add_polygon(&[p(30.0, 30.0), p(45.0, 50.0), p(30.0, 70.0)], false)
        .add_polygon(&[p(70.0, 30.0), p(70.0, 70.0), p(55.0, 50.0)], false)
        .detach();
    canvas.draw_path(&path, paint);
    canvas.restore();
}

// A split edge causes one half to be merged to zero winding (destroyed).
// Test that the other half of the split doesn't also get zero winding.
// Port of: gm/concavepaths.cpp#L180-L194 (chrome/m156)
fn test_winding_merged_to_zero(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((400.0, 350.0));
    path.move_to((20.0, 80.0));
    path.move_to((70.0, -0.000_001));
    path.line_to((70.0, 0.0));
    path.line_to((60.0, -30.0));
    path.line_to((40.0, 20.0));
    path.move_to((50.0, 50.0));
    path.line_to((50.0, -50.0));
    path.line_to((10.0, 50.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Monotone test 1 (point in the middle)
// Port of: gm/concavepaths.cpp#L197-L206 (chrome/m156)
fn test_monotone_1(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((0.0, 300.0));
    path.move_to((20.0, 20.0));
    path.quad_to((20.0, 50.0), (80.0, 50.0));
    path.quad_to((20.0, 50.0), (20.0, 80.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Monotone test 2 (point at the top)
// Port of: gm/concavepaths.cpp#L209-L218 (chrome/m156)
fn test_monotone_2(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((100.0, 300.0));
    path.move_to((20.0, 20.0));
    path.line_to((80.0, 30.0));
    path.quad_to((20.0, 20.0), (20.0, 80.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Monotone test 3 (point at the bottom)
// Port of: gm/concavepaths.cpp#L221-L230 (chrome/m156)
fn test_monotone_3(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((200.0, 300.0));
    path.move_to((20.0, 80.0));
    path.line_to((80.0, 70.0));
    path.quad_to((20.0, 80.0), (20.0, 20.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Monotone test 4 (merging of two monotones)
// Port of: gm/concavepaths.cpp#L233-L245 (chrome/m156)
fn test_monotone_4(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((300.0, 300.0));
    path.move_to((80.0, 25.0));
    path.line_to((50.0, 39.0));
    path.line_to((20.0, 25.0));
    path.line_to((40.0, 45.0));
    path.line_to((70.0, 50.0));
    path.line_to((80.0, 80.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Monotone test 5 (aborted merging of two monotones)
// Port of: gm/concavepaths.cpp#L248-L258 (chrome/m156)
fn test_monotone_5(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((0.0, 400.0));
    path.move_to((50.0, 20.0));
    path.line_to((80.0, 80.0));
    path.line_to((50.0, 50.0));
    path.line_to((20.0, 80.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Degenerate intersection test
// Port of: gm/concavepaths.cpp#L260-L273 (chrome/m156)
fn test_degenerate(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((100.0, 400.0));
    path.move_to((50.0, 20.0));
    path.line_to((70.0, 30.0));
    path.line_to((20.0, 50.0));
    path.move_to((50.0, 20.0));
    path.line_to((80.0, 80.0));
    path.line_to((50.0, 80.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Two triangles with a coincident edge.
// Port of: gm/concavepaths.cpp#L275-L292 (chrome/m156)
fn test_coincident_edge(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((200.0, 400.0));

    path.move_to((80.0, 20.0));
    path.line_to((80.0, 80.0));
    path.line_to((20.0, 80.0));

    path.move_to((20.0, 20.0));
    path.line_to((80.0, 80.0));
    path.line_to((20.0, 80.0));

    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Bowtie with a coincident triangle (one triangle vertex coincident with the
// bowtie's intersection).
// Port of: gm/concavepaths.cpp#L296-L309 (chrome/m156)
fn test_bowtie_coincident_triangle(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((300.0, 400.0));
    path.move_to((20.0, 20.0));
    path.line_to((80.0, 80.0));
    path.line_to((80.0, 20.0));
    path.line_to((20.0, 80.0));
    path.move_to((50.0, 50.0));
    path.line_to((80.0, 20.0));
    path.line_to((80.0, 80.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Collinear outer boundary edges. In the edge-AA codepath, this creates an overlap region
// which contains a boundary edge. It can't be removed, but it must have the correct winding.
// Port of: gm/concavepaths.cpp#L313-L326 (chrome/m156)
fn test_collinear_outer_boundary_edge(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((400.0, 400.0));
    path.move_to((20.0, 20.0));
    path.line_to((20.0, 50.0));
    path.line_to((50.0, 50.0));
    path.move_to((80.0, 50.0));
    path.line_to((50.0, 50.0));
    path.line_to((80.0, 20.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Coincident edges (big ones first, coincident vert on top).
// Port of: gm/concavepaths.cpp#L329-L341 (chrome/m156)
fn test_coincident_edges_1(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((0.0, 500.0));
    path.move_to((20.0, 20.0));
    path.line_to((80.0, 80.0));
    path.line_to((20.0, 80.0));
    path.move_to((20.0, 20.0));
    path.line_to((50.0, 50.0));
    path.line_to((20.0, 50.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Coincident edges (small ones first, coincident vert on top).
// Port of: gm/concavepaths.cpp#L343-L355 (chrome/m156)
fn test_coincident_edges_2(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((100.0, 500.0));
    path.move_to((20.0, 20.0));
    path.line_to((50.0, 50.0));
    path.line_to((20.0, 50.0));
    path.move_to((20.0, 20.0));
    path.line_to((80.0, 80.0));
    path.line_to((20.0, 80.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Coincident edges (small ones first, coincident vert on bottom).
// Port of: gm/concavepaths.cpp#L357-L369 (chrome/m156)
fn test_coincident_edges_3(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((200.0, 500.0));
    path.move_to((20.0, 80.0));
    path.line_to((20.0, 50.0));
    path.line_to((50.0, 50.0));
    path.move_to((20.0, 80.0));
    path.line_to((20.0, 20.0));
    path.line_to((80.0, 20.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Coincident edges (big ones first, coincident vert on bottom).
// Port of: gm/concavepaths.cpp#L371-L383 (chrome/m156)
fn test_coincident_edges_4(canvas: &Canvas, paint: &Paint) {
    let mut path = PathBuilder::new();
    canvas.save();
    canvas.translate((300.0, 500.0));
    path.move_to((20.0, 80.0));
    path.line_to((20.0, 20.0));
    path.line_to((80.0, 20.0));
    path.move_to((20.0, 80.0));
    path.line_to((20.0, 50.0));
    path.line_to((50.0, 50.0));
    canvas.draw_path(&path.detach(), paint);
    canvas.restore();
}

// Port of: gm/concavepaths.cpp#L387-L422 (chrome/m156)
crate::def_simple_gm!(concavepaths, canvas, 500, 600, {
    let mut paint = Paint::default();

    paint.set_anti_alias(true);
    paint.set_style(Style::Fill);

    test_concave(canvas, &paint);
    test_reverse_concave(canvas, &paint);
    test_bowtie(canvas, &paint);
    test_fake_bowtie(canvas, &paint);
    test_intruding_vertex(canvas, &paint);
    test_fish(canvas, &paint);
    test_fast_forward(canvas, &paint);
    test_hole(canvas, &paint);
    test_star(canvas, &paint);
    test_twist(canvas, &paint);
    test_inversion_repeat_vertex(canvas, &paint);
    test_stairstep(canvas, &paint);
    test_stairstep2(canvas, &paint);
    test_overlapping(canvas, &paint);
    test_partners(canvas, &paint);
    test_winding_merged_to_zero(canvas, &paint);
    test_monotone_1(canvas, &paint);
    test_monotone_2(canvas, &paint);
    test_monotone_3(canvas, &paint);
    test_monotone_4(canvas, &paint);
    test_monotone_5(canvas, &paint);
    test_degenerate(canvas, &paint);
    test_coincident_edge(canvas, &paint);
    test_bowtie_coincident_triangle(canvas, &paint);
    test_collinear_outer_boundary_edge(canvas, &paint);
    test_coincident_edges_1(canvas, &paint);
    test_coincident_edges_2(canvas, &paint);
    test_coincident_edges_3(canvas, &paint);
    test_coincident_edges_4(canvas, &paint);
});
