// Skia side of the SkAAClip / SkRasterClip port tests: runs the case script
// crates/skia-rust-raster/src/aa_clip_tests/cases.txt (generated by oracle/aaclip/gen_cases.py)
// through Skia's real SkAAClip, SkRasterClip, SkAAClipBlitter and the SkScan entry points taking
// an SkRasterClip, and prints a text dump that the Rust runner reproduces byte for byte.
//
// CASE FORMAT (line oriented, `#` comments, blank lines ignored). A script is a list of
// `case <name>` ... `end` blocks. State per case: AAClip slots `aa`, `aa2` (initially empty), one
// SkRasterClip `rc` (initially default constructed) and one path builder. Numbers are decimal;
// floats are parsed with strtof.
//
// Path building (same syntax as oracle/scan-aaa cases.txt), accumulating into one SkPathBuilder:
//   path winding|evenodd|invwinding|invevenodd   resets the builder with that fill type
//   M x y | L x y | Q x1 y1 x2 y2 | C x1 y1 x2 y2 x3 y3 | K x1 y1 x2 y2 w | Z
//   circle cx cy r | circleccw cx cy r | oval l t r b | rrect l t r b rx ry | rect l t r b
// Commands needing "the path" use builder.snapshot() at that moment.
//
// <spec> = (union|xor) l t r b [+ l t r b ...]: empty SkRegion, each rect applied with
//          kUnion_Op / kXOR_Op.   <op> = intersect|diff.   <aa> = aa|bw (doAA true/false).
// <mat>  = I | M9 a b c d e f g h i (row-major, SkMatrix::MakeAll).
//
// AAClip commands (<S> is aa or aa2):
//   <S> empty | rect l t r b | region <spec> | path <aa> l t r b | pathbounds <aa>
//   <S> opi l t r b <op> | opf l t r b <op> <aa> | opaa <S2> <op>
//   <S> translate dx dy (into itself) | translateto <S2> dx dy (this->translate(dx,dy,&S2))
//   <S> copy <S2> | qc l t r b
// RasterClip commands:
//   rc new empty | new irect l t r b | new region <spec> | new path <aa> l t r b
//   rc setempty | setrect l t r b | opi l t r b <op> | opregion <spec> <op>
//   rc oprect l t r b <mat> <op> <aa> | oprrect l t r b rx ry <mat> <op> <aa>
//   rc oppath <mat> <op> <aa> | translate dx dy
// Blits through SkAAClipBlitter(DumpBlitter, aa) (`skip empty` if aa is empty):
//   blit h x y w | antih x y a:n ... | v x y h alpha | rect x y w h
//   blit mask a8|bw x y w h cl ct cr cb <hex bytes>
// Scan entry points through rc, blitter = fresh DumpBlitter:
//   scan fillpath | antifillpath | fillirect l t r b | fillxrect l t r b (16.16) | fillrect |
//   antifillrect | antifillxrect | filltriangle x0 y0 x1 y1 x2 y2 | hairline x0 y0 x1 y1 ... |
//   antihairline ... | hairrect l t r b | antihairrect | hairpath | antihairpath |
//   hairsquarepath | antihairsquarepath | hairroundpath | antihairroundpath |
//   framerect l t r b sx sy | antiframerect l t r b sx sy
//
// OUTPUT: `== <name>` per case, then per command: aa commands `ret n`, `clip <isEmpty> <isRect>
// l t r b`, mask rows; `qc n`; rc commands `ret n`, `rc <isBW> <isEmpty> <isRect> <isComplex>
// l t r b`, mask rows; blit/scan commands the DumpBlitter lines. Mask rows are `row <y>: xx ..`
// (A8, lowercase hex) when non-empty and w*h <= 65536, else `mask skipped`.
//
// Build and run (Windows): oracle/aaclip/build.ps1.

#include "include/core/SkClipOp.h"
#include "include/core/SkMatrix.h"
#include "include/core/SkPath.h"
#include "include/core/SkPathBuilder.h"
#include "include/core/SkRRect.h"
#include "include/core/SkRect.h"
#include "include/core/SkRegion.h"
#include "src/core/SkAAClip.h"
#include "src/core/SkBlitter.h"
#include "src/core/SkMask.h"
#include "src/core/SkPathPriv.h"
#include "src/core/SkPathRaw.h"
#include "src/core/SkRasterClip.h"
#include "src/core/SkScan.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

class DumpBlitter final : public SkBlitter {
public:
    void blitH(int x, int y, int width) override { printf("blitH %d %d %d\n", x, y, width); }
    void blitAntiH(int x, int y, const SkAlpha aa[], const int16_t runs[]) override {
        printf("blitAntiH %d %d", x, y);
        for (int i = 0; runs[i] > 0; i += runs[i]) {
            printf(" %d:%d", aa[i], runs[i]);
        }
        printf("\n");
    }
    void blitV(int x, int y, int height, SkAlpha alpha) override {
        printf("blitV %d %d %d %d\n", x, y, height, alpha);
    }
    void blitRect(int x, int y, int width, int height) override {
        printf("blitRect %d %d %d %d\n", x, y, width, height);
    }
    void blitAntiRect(int x, int y, int width, int height, SkAlpha l, SkAlpha r) override {
        printf("blitAntiRect %d %d %d %d %d %d\n", x, y, width, height, l, r);
    }
    void blitMask(const SkMask& mask, const SkIRect& clip) override {
        static const char* kNames[] = {"BW", "A8", "3D", "ARGB32", "LCD16", "SDF"};
        const SkIRect& b = mask.fBounds;
        printf("blitMask %s %d %d %d %d clip %d %d %d %d\n", kNames[mask.fFormat], b.fLeft,
               b.fTop, b.fRight, b.fBottom, clip.fLeft, clip.fTop, clip.fRight, clip.fBottom);
        if (mask.fFormat == SkMask::kA8_Format) {
            for (int y = b.fTop; y < b.fBottom; ++y) {
                printf(" row %d:", y);
                const uint8_t* row = mask.fImage + (y - b.fTop) * mask.fRowBytes;
                for (int x = 0; x < b.width(); ++x) {
                    printf(" %02x", row[x]);
                }
                printf("\n");
            }
        }
    }
    void blitAntiH2(int x, int y, U8CPU a0, U8CPU a1) override {
        printf("blitAntiH2 %d %d %u %u\n", x, y, a0, a1);
    }
    void blitAntiV2(int x, int y, U8CPU a0, U8CPU a1) override {
        printf("blitAntiV2 %d %d %u %u\n", x, y, a0, a1);
    }
};

static float F(std::istringstream& in) {
    std::string s;
    in >> s;
    return strtof(s.c_str(), nullptr);
}
static int I(std::istringstream& in) {
    int v = 0;
    in >> v;
    return v;
}
static std::string W(std::istringstream& in) {
    std::string s;
    in >> s;
    return s;
}
static SkClipOp Op(std::istringstream& in) {
    return W(in) == "diff" ? SkClipOp::kDifference : SkClipOp::kIntersect;
}
static bool AA(std::istringstream& in) { return W(in) == "aa"; }
static SkIRect IR(std::istringstream& in) {
    int l = I(in), t = I(in), r = I(in), b = I(in);
    return SkIRect::MakeLTRB(l, t, r, b);
}
static SkRect FR(std::istringstream& in) {
    float l = F(in), t = F(in), r = F(in), b = F(in);
    return SkRect::MakeLTRB(l, t, r, b);
}
static SkMatrix Mat(std::istringstream& in) {
    std::string k = W(in);
    if (k == "I") {
        return SkMatrix::I();
    }
    float v[9];
    for (float& f : v) {
        f = F(in);
    }
    return SkMatrix::MakeAll(v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7], v[8]);
}
// Parses `<union|xor> l t r b [+ l t r b ...]`. `next` receives the token following the spec
// (empty if none).
static SkRegion Spec(std::istringstream& in, std::string* next) {
    SkRegion rgn;
    SkRegion::Op op = W(in) == "xor" ? SkRegion::kXOR_Op : SkRegion::kUnion_Op;
    for (;;) {
        rgn.op(IR(in), op);
        std::string plus;
        if (!(in >> plus)) {
            if (next) next->clear();
            break;
        }
        if (plus != "+") {
            if (next) *next = plus;
            break;
        }
    }
    return rgn;
}

static void PrintRows(const uint8_t* img, const SkIRect& b, size_t rowBytes) {
    int64_t w = (int64_t)b.fRight - b.fLeft, h = (int64_t)b.fBottom - b.fTop;
    for (int y = 0; y < h; ++y) {
        printf("row %d:", b.fTop + y);
        for (int x = 0; x < w; ++x) {
            printf(" %02x", img[y * rowBytes + x]);
        }
        printf("\n");
    }
}

static void PrintAAMask(const SkAAClip& aa) {
    if (aa.isEmpty()) {
        return;
    }
    const SkIRect& b = aa.getBounds();
    int64_t w = (int64_t)b.fRight - b.fLeft, h = (int64_t)b.fBottom - b.fTop;
    if (w * h > 65536) {
        printf("mask skipped\n");
        return;
    }
    SkMaskBuilder mask;
    aa.copyToMask(&mask);
    PrintRows(mask.image(), mask.fBounds, mask.fRowBytes);
    SkMaskBuilder::FreeImage(mask.image());
}

static void PrintAA(const SkAAClip& aa, bool ret) {
    printf("ret %d\n", ret ? 1 : 0);
    const SkIRect& b = aa.getBounds();
    printf("clip %d %d %d %d %d %d\n", aa.isEmpty(), aa.isRect(), b.fLeft, b.fTop, b.fRight,
           b.fBottom);
    PrintAAMask(aa);
}

static void PrintRC(const SkRasterClip& rc, bool ret) {
    printf("ret %d\n", ret ? 1 : 0);
    const SkIRect& b = rc.getBounds();
    printf("rc %d %d %d %d %d %d %d %d\n", rc.isBW(), rc.isEmpty(), rc.isRect(), rc.isComplex(),
           b.fLeft, b.fTop, b.fRight, b.fBottom);
    if (rc.isEmpty()) {
        return;
    }
    if (rc.isAA()) {
        PrintAAMask(rc.aaRgn());
        return;
    }
    const SkRegion& rgn = rc.bwRgn();
    int64_t w = (int64_t)b.fRight - b.fLeft, h = (int64_t)b.fBottom - b.fTop;
    if (w * h > 65536) {
        printf("mask skipped\n");
        return;
    }
    std::vector<uint8_t> img((size_t)(w * h), 0);
    for (SkRegion::Iterator it(rgn); !it.done(); it.next()) {
        const SkIRect& r = it.rect();
        for (int y = r.fTop; y < r.fBottom; ++y) {
            for (int x = r.fLeft; x < r.fRight; ++x) {
                img[(size_t)((y - b.fTop) * w + (x - b.fLeft))] = 0xFF;
            }
        }
    }
    PrintRows(img.data(), b, (size_t)w);
}

int main(int argc, char** argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: aaclip <cases.txt>\n");
        return 1;
    }
    std::ifstream file(argv[1]);
    std::string line, name;
    SkAAClip aaSlots[2];
    SkRasterClip rc;
    SkPathBuilder builder;
    auto slot = [&](const std::string& s) -> SkAAClip& {
        return s == "aa2" ? aaSlots[1] : aaSlots[0];
    };
    while (std::getline(file, line)) {
        if (!line.empty() && line.back() == '\r') {
            line.pop_back();
        }
        std::istringstream in(line);
        std::string cmd;
        if (!(in >> cmd) || cmd[0] == '#') {
            continue;
        }
        if (cmd == "case") {
            in >> name;
            aaSlots[0].setEmpty();
            aaSlots[1].setEmpty();
            rc = SkRasterClip();
            builder.reset();
            printf("== %s\n", name.c_str());
        } else if (cmd == "end") {
        } else if (cmd == "path") {
            std::string f = W(in);
            builder.reset();
            builder.setFillType(f == "winding"      ? SkPathFillType::kWinding
                                : f == "evenodd"    ? SkPathFillType::kEvenOdd
                                : f == "invwinding" ? SkPathFillType::kInverseWinding
                                                    : SkPathFillType::kInverseEvenOdd);
        } else if (cmd == "M") {
            float x = F(in), y = F(in);
            builder.moveTo(x, y);
        } else if (cmd == "L") {
            float x = F(in), y = F(in);
            builder.lineTo(x, y);
        } else if (cmd == "Q") {
            float a = F(in), b = F(in), c = F(in), d = F(in);
            builder.quadTo(a, b, c, d);
        } else if (cmd == "C") {
            float a = F(in), b = F(in), c = F(in), d = F(in), e = F(in), f = F(in);
            builder.cubicTo(a, b, c, d, e, f);
        } else if (cmd == "K") {
            float a = F(in), b = F(in), c = F(in), d = F(in), w = F(in);
            builder.conicTo(a, b, c, d, w);
        } else if (cmd == "Z") {
            builder.close();
        } else if (cmd == "circle" || cmd == "circleccw") {
            float x = F(in), y = F(in), r = F(in);
            builder.addCircle(x, y, r,
                              cmd == "circle" ? SkPathDirection::kCW : SkPathDirection::kCCW);
        } else if (cmd == "oval") {
            builder.addOval(FR(in));
        } else if (cmd == "rrect") {
            SkRect r = FR(in);
            float rx = F(in), ry = F(in);
            builder.addRRect(SkRRect::MakeRectXY(r, rx, ry));
        } else if (cmd == "rect") {
            builder.addRect(FR(in));
        } else if (cmd == "aa" || cmd == "aa2") {
            SkAAClip& c = slot(cmd);
            std::string sub = W(in);
            bool ret = true;
            if (sub == "qc") {
                printf("qc %d\n", c.quickContains(IR(in)) ? 1 : 0);
                continue;
            } else if (sub == "empty") {
                ret = c.setEmpty();
            } else if (sub == "rect") {
                ret = c.setRect(IR(in));
            } else if (sub == "region") {
                ret = c.setRegion(Spec(in, nullptr));
            } else if (sub == "path") {
                bool aa = AA(in);
                SkIRect b = IR(in);
                ret = c.setPath(builder.snapshot(), b, aa);
            } else if (sub == "pathbounds") {
                bool aa = AA(in);
                SkPath p = builder.snapshot();
                ret = c.setPath(p, p.getBounds().roundOut(), aa);
            } else if (sub == "opi") {
                SkIRect r = IR(in);
                ret = c.op(r, Op(in));
            } else if (sub == "opf") {
                SkRect r = FR(in);
                SkClipOp op = Op(in);
                ret = c.op(r, op, AA(in));
            } else if (sub == "opaa") {
                SkAAClip& o = slot(W(in));
                SkClipOp op = Op(in);
                ret = c.op(o, op);
            } else if (sub == "translate") {
                int dx = I(in), dy = I(in);
                ret = c.translate(dx, dy, &c);
            } else if (sub == "translateto") {
                SkAAClip& o = slot(W(in));
                int dx = I(in), dy = I(in);
                ret = c.translate(dx, dy, &o);
                PrintAA(o, ret);
                continue;
            } else if (sub == "copy") {
                SkAAClip& o = slot(W(in));
                c = o;
            } else {
                fprintf(stderr, "bad aa command: %s\n", line.c_str());
                return 2;
            }
            PrintAA(c, ret);
        } else if (cmd == "rc") {
            std::string sub = W(in);
            bool ret = true;
            if (sub == "new") {
                std::string k = W(in);
                if (k == "empty") {
                    rc = SkRasterClip();
                } else if (k == "irect") {
                    rc = SkRasterClip(IR(in));
                } else if (k == "region") {
                    rc = SkRasterClip(Spec(in, nullptr));
                } else {
                    bool aa = AA(in);
                    SkIRect b = IR(in);
                    rc = SkRasterClip(builder.snapshot(), b, aa);
                }
            } else if (sub == "setempty") {
                ret = rc.setEmpty();
            } else if (sub == "setrect") {
                ret = rc.setRect(IR(in));
            } else if (sub == "opi") {
                SkIRect r = IR(in);
                ret = rc.op(r, Op(in));
            } else if (sub == "opregion") {
                std::string next;
                SkRegion r = Spec(in, &next);
                ret = rc.op(r, next == "diff" ? SkClipOp::kDifference : SkClipOp::kIntersect);
            } else if (sub == "oprect") {
                SkRect r = FR(in);
                SkMatrix m = Mat(in);
                SkClipOp op = Op(in);
                ret = rc.op(r, m, op, AA(in));
            } else if (sub == "oprrect") {
                SkRect r = FR(in);
                float rx = F(in), ry = F(in);
                SkMatrix m = Mat(in);
                SkClipOp op = Op(in);
                ret = rc.op(SkRRect::MakeRectXY(r, rx, ry), m, op, AA(in));
            } else if (sub == "oppath") {
                SkMatrix m = Mat(in);
                SkClipOp op = Op(in);
                ret = rc.op(builder.snapshot(), m, op, AA(in));
            } else if (sub == "translate") {
                int dx = I(in), dy = I(in);
                SkRasterClip tmp;
                rc.translate(dx, dy, &tmp);
                rc = tmp;
            } else {
                fprintf(stderr, "bad rc command: %s\n", line.c_str());
                return 2;
            }
            PrintRC(rc, ret);
        } else if (cmd == "blit") {
            SkAAClip& c = aaSlots[0];
            std::string sub = W(in);
            if (c.isEmpty()) {
                printf("skip empty\n");
                continue;
            }
            DumpBlitter dump;
            SkAAClipBlitter blitter;
            blitter.init(&dump, &c);
            if (sub == "h") {
                int x = I(in), y = I(in), w = I(in);
                blitter.blitH(x, y, w);
            } else if (sub == "antih") {
                int x = I(in), y = I(in);
                std::vector<SkAlpha> alphas;
                std::vector<int> counts;
                std::string tok;
                int total = 0;
                while (in >> tok) {
                    size_t colon = tok.find(':');
                    alphas.push_back((SkAlpha)atoi(tok.substr(0, colon).c_str()));
                    counts.push_back(atoi(tok.substr(colon + 1).c_str()));
                    total += counts.back();
                }
                std::vector<SkAlpha> aa(total + 1, 0);
                std::vector<int16_t> runs(total + 1, 0);
                int pos = 0;
                for (size_t i = 0; i < alphas.size(); ++i) {
                    runs[pos] = (int16_t)counts[i];
                    aa[pos] = alphas[i];
                    pos += counts[i];
                }
                runs[total] = 0;
                blitter.blitAntiH(x, y, aa.data(), runs.data());
            } else if (sub == "v") {
                int x = I(in), y = I(in), h = I(in), a = I(in);
                blitter.blitV(x, y, h, (SkAlpha)a);
            } else if (sub == "rect") {
                int x = I(in), y = I(in), w = I(in), h = I(in);
                blitter.blitRect(x, y, w, h);
            } else if (sub == "mask") {
                bool a8 = W(in) == "a8";
                int x = I(in), y = I(in), w = I(in), h = I(in);
                SkIRect clip = IR(in);
                std::vector<uint8_t> img;
                std::string tok;
                while (in >> tok) {
                    img.push_back((uint8_t)strtoul(tok.c_str(), nullptr, 16));
                }
                uint32_t rowBytes = a8 ? w : (w + 7) / 8;
                img.resize((size_t)rowBytes * h, 0);
                SkMaskBuilder mask(img.data(), SkIRect::MakeXYWH(x, y, w, h), rowBytes,
                                   a8 ? SkMask::kA8_Format : SkMask::kBW_Format);
                blitter.blitMask(mask, clip);
            } else {
                fprintf(stderr, "bad blit command: %s\n", line.c_str());
                return 2;
            }
        } else if (cmd == "scan") {
            std::string sub = W(in);
            DumpBlitter dump;
            SkPath path;
            bool isPath = sub.find("path") != std::string::npos;
            std::optional<SkPathRaw> raw;
            if (isPath) {
                path = builder.snapshot();
                raw = SkPathPriv::Raw(path, SkResolveConvexity::kYes);
                if (!raw) {
                    raw = SkPathRaw::Empty();
                }
            }
            if (sub == "fillpath") {
                SkScan::FillPath(*raw, rc, &dump);
            } else if (sub == "antifillpath") {
                SkScan::AntiFillPath(*raw, rc, &dump);
            } else if (sub == "fillirect") {
                SkScan::FillIRect(IR(in), rc, &dump);
            } else if (sub == "fillxrect") {
                SkScan::FillXRect(IR(in), rc, &dump);
            } else if (sub == "fillrect") {
                SkScan::FillRect(FR(in), rc, &dump);
            } else if (sub == "antifillrect") {
                SkScan::AntiFillRect(FR(in), rc, &dump);
            } else if (sub == "antifillxrect") {
                SkScan::AntiFillXRect(IR(in), rc, &dump);
            } else if (sub == "filltriangle") {
                SkPoint pts[3];
                for (SkPoint& p : pts) {
                    float x = F(in), y = F(in);
                    p.set(x, y);
                }
                SkScan::FillTriangle(pts, rc, &dump);
            } else if (sub == "hairline" || sub == "antihairline") {
                std::vector<SkPoint> pts;
                std::string tok;
                while (in >> tok) {
                    float x = strtof(tok.c_str(), nullptr);
                    float y = F(in);
                    pts.push_back({x, y});
                }
                SkSpan<const SkPoint> span(pts.data(), pts.size());
                if (sub == "hairline") {
                    SkScan::HairLine(span, rc, &dump);
                } else {
                    SkScan::AntiHairLine(span, rc, &dump);
                }
            } else if (sub == "hairrect") {
                SkScan::HairRect(FR(in), rc, &dump);
            } else if (sub == "antihairrect") {
                SkScan::AntiHairRect(FR(in), rc, &dump);
            } else if (sub == "hairpath") {
                SkScan::HairPath(*raw, rc, &dump);
            } else if (sub == "antihairpath") {
                SkScan::AntiHairPath(*raw, rc, &dump);
            } else if (sub == "hairsquarepath") {
                SkScan::HairSquarePath(*raw, rc, &dump);
            } else if (sub == "antihairsquarepath") {
                SkScan::AntiHairSquarePath(*raw, rc, &dump);
            } else if (sub == "hairroundpath") {
                SkScan::HairRoundPath(*raw, rc, &dump);
            } else if (sub == "antihairroundpath") {
                SkScan::AntiHairRoundPath(*raw, rc, &dump);
            } else if (sub == "framerect" || sub == "antiframerect") {
                SkRect r = FR(in);
                float sx = F(in), sy = F(in);
                if (sub == "framerect") {
                    SkScan::FrameRect(r, {sx, sy}, rc, &dump);
                } else {
                    SkScan::AntiFrameRect(r, {sx, sy}, rc, &dump);
                }
            } else {
                fprintf(stderr, "bad scan command: %s\n", line.c_str());
                return 2;
            }
        } else {
            fprintf(stderr, "bad command: %s\n", line.c_str());
            return 2;
        }
        fflush(stdout);
    }
    return 0;
}
