[package]
name = "skia-rust-pdf"
description = "Skia's PDF backend (src/pdf, include/docs/SkPDFDocument.h) for skia-rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
skia-rust-core.workspace = true
skia-rust-raster.workspace = true
skia-rust-pathops.workspace = true
skia-rust-codec.workspace = true
skia-rust-zlib.workspace = true
skia-rust-skcms.workspace = true
skia-rust-effects.workspace = true

[lints]
workspace = true
