// Copyright 2022 Google LLC
// Copyright 2026 The skia-rust Authors
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.
// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp (chrome/m156)

#![cfg(test)]

use std::cell::RefCell;
use std::sync::Arc;

use skia_rust_core::alpha_type::AlphaType;
use skia_rust_core::blend_mode::BlendMode;
use skia_rust_core::color_space::ColorSpace;
use skia_rust_core::color_type::ColorType;
use skia_rust_core::image_info::ColorInfo;
use skia_rust_core::runtime_effect::RuntimeEffect;
use skia_rust_effects::gradient::Interpolation;
use skia_rust_gpu::graphite::draw_types::DrawTypeFlags;
use skia_rust_gpu::graphite::key_context::KeyContext;
use skia_rust_gpu::graphite::paint_params_key::PaintParamsKeyBuilder;
use skia_rust_gpu::graphite::pipeline_data::PipelineDataGatherer;
use skia_rust_gpu::graphite::precompile::blender::PrecompileBlenders;
use skia_rust_gpu::graphite::precompile::color_filter::{
    PrecompileColorFilter, PrecompileColorFilters,
};
use skia_rust_gpu::graphite::precompile::paint_options::PaintOptions;
use skia_rust_gpu::graphite::precompile::runtime_effect::{
    PrecompileBaseHandle, PrecompileRuntimeEffects,
};
use skia_rust_gpu::graphite::precompile::shader::{
    GradientShaderFlags, PrecompileShader, PrecompileShaders,
};
use skia_rust_gpu::graphite::precompile::shader_image::{ALL_TILE_MODES, ImageShaderFlags};
use skia_rust_gpu::graphite::render_pass_desc::RenderPassDesc;
use skia_rust_gpu::graphite::render_step::Coverage;
use skia_rust_gpu::graphite::resource_types::Layout;
use skia_rust_gpu::graphite::runtime_effect_dictionary::RuntimeEffectDictionary;
use skia_rust_gpu::graphite::unique_paint_params_id::UniquePaintParamsID;

use crate::{Reporter, def_graphite_test_for_all_contexts, reporter_assert};

// colorfilters
const EXPECTED_BLEND_CF_COMBOS: i32 = 15;
const EXPECTED_COLOR_SPACE_CF_COMBOS: i32 = 1;
const EXPECTED_HIGH_CONTRAST_CF_COMBOS: i32 = 1;
const EXPECTED_LUMA_CF_COMBOS: i32 = 1;
const EXPECTED_MATRIX_CF_COMBOS: i32 = 2; // alpha-preserving and not
const EXPECTED_LIGHTING_CF_COMBOS: i32 = EXPECTED_MATRIX_CF_COMBOS; // Maps to ::Matrix
const EXPECTED_OVERDRAW_CF_COMBOS: i32 = 1;
const EXPECTED_TABLE_CF_COMBOS: i32 = 1;

// shaders
const EXPECTED_GRADIENT_COMBOS: i32 = 6;
const EXPECTED_IMAGE_COMBOS: i32 = 24;
const EXPECTED_PERLIN_NOISE_COMBOS: i32 = 1;
const EXPECTED_PICTURE_COMBOS: i32 = 48;
const EXPECTED_RAW_IMAGE_COMBOS: i32 = 10;
const EXPECTED_SOLID_COLOR_COMBOS: i32 = 2;

/// The IDs `buildCombinations` reports, in order (the test's `precompileIDs` vector).
fn collect_precompile_ids(
    paint_options: &PaintOptions,
    key_context: &KeyContext<'_>,
    render_pass_desc: &RenderPassDesc,
) -> Vec<UniquePaintParamsID> {
    let precompile_ids = RefCell::new(Vec::new());
    paint_options.build_combinations(
        key_context,
        DrawTypeFlags::NONE,
        /* with_primitive_blender= */ false,
        Coverage::None,
        render_pass_desc,
        &|id, _, _, _, _| precompile_ids.borrow_mut().push(id),
    );
    precompile_ids.into_inner()
}

/// `SkASSERT(precompileIDs.size() == expected)`.
fn assert_count(precompile_ids: &[UniquePaintParamsID], expected: i32) {
    assert_eq!(i32::try_from(precompile_ids.len()).unwrap_or(-1), expected);
}

// A default kSrcOver blend mode will be supplied if no other blend options are added
// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L43-L63 (chrome/m156)
fn no_blend_mode_option_test(
    key_context: &KeyContext<'_>,
    render_pass_desc: &RenderPassDesc,
    _reporter: &mut Reporter,
) {
    let mut paint_options = PaintOptions::new();
    paint_options.set_shaders(&[PrecompileShaders::color()]);

    assert_eq!(
        paint_options.num_combinations(),
        EXPECTED_SOLID_COLOR_COMBOS
    );

    let precompile_ids = collect_precompile_ids(&paint_options, key_context, render_pass_desc);
    assert_count(&precompile_ids, EXPECTED_SOLID_COLOR_COMBOS);
}

// This test checks that the 'PaintOptions::numCombinations' method and the number actually
// generated by 'buildCombinations' agree with the expected number of combinations.
// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L65-L94 (chrome/m156)
fn run_test(
    key_context: &KeyContext<'_>,
    render_pass_desc: &RenderPassDesc,
    reporter: &mut Reporter,
    paint_options: &PaintOptions,
    expected_num_options: i32,
) {
    reporter_assert!(
        reporter,
        paint_options.num_combinations() == expected_num_options,
        "expected {}, but was {}",
        expected_num_options,
        paint_options.num_combinations()
    );

    // Some combinations produced may result in the same UniquePaintParamsID since the
    // combinatorics introduce opaque vs. non-opaque branches. Depending on how that recombines
    // in the final paint key, key-impacting decisions may or may not be made. In most cases, the
    // number of unique paint IDs will be lower than the raw number of combinations. Since we
    // don't de-dupe when adding to `precompileIDs` here, we can assert the total is
    // `expectedNumOptions`.
    let precompile_ids = collect_precompile_ids(paint_options, key_context, render_pass_desc);
    assert_count(&precompile_ids, expected_num_options);
}

// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L96-L165 (chrome/m156)
fn big_test(
    key_context: &KeyContext<'_>,
    render_pass_desc: &RenderPassDesc,
    reporter: &mut Reporter,
) {
    const NUM_EXPECTED: i32 = 6360;
    // paintOptions (6360 = 4*1590)
    //  |- (1590 = 6+1584) sweepGrad_0 (3*2) |
    //  |                blendShader_0 (1584 = 1*8*198)
    //  |                 |- 0: (1)       kSrc (1)
    //  |                 |- 1: (8=6+2)   (dsts) linearGrad_0 (3*2) | solid_0 (2)
    //  |                 |- 2: (198=6+192) (srcs) linearGrad_1 (3*2) |
    //  |                                        blendShader_1 (192=1*8*24)
    //  |                                         |- 0: (1) kDst (1)
    //  |                                         |- 1: (8=6+2) (dsts) radGrad_0 (3*2) | solid_1 (2)
    //  |                                         |- 2: (24) (srcs) imageShader_0 (24)
    //  |
    //  |- (4) 4-built-in-blend-modes

    let mut paint_options = PaintOptions::new();

    // first, shaders. First top-level option (sweepGrad_0)
    let sweep_grad_0 =
        PrecompileShaders::sweep_gradient(GradientShaderFlags::ALL, Interpolation::default());

    let block_modes = [BlendMode::Src];

    let more_blend_modes = [BlendMode::Dst];

    // Second top-level option (blendShader_0)
    let blend_shader_0 = PrecompileShaders::blend_modes(
        &block_modes,
        &[
            PrecompileShaders::linear_gradient(GradientShaderFlags::ALL, Interpolation::default()),
            PrecompileShaders::color(),
        ],
        &[
            PrecompileShaders::linear_gradient(GradientShaderFlags::ALL, Interpolation::default()),
            PrecompileShaders::blend_modes(
                &more_blend_modes,
                &[
                    PrecompileShaders::radial_gradient(
                        GradientShaderFlags::ALL,
                        Interpolation::default(),
                    ),
                    PrecompileShaders::color(),
                ],
                &[PrecompileShaders::image(
                    ImageShaderFlags::ALL,
                    &[],
                    &ALL_TILE_MODES,
                )],
            ),
        ],
    );
    paint_options.set_shaders(&[sweep_grad_0, blend_shader_0]);

    let even_more_blend_modes = [
        BlendMode::SrcOver,
        BlendMode::Src,
        BlendMode::DstOver,
        BlendMode::Dst,
    ];

    // now, blend modes
    paint_options.set_blend_modes(&even_more_blend_modes); // c array
    reporter_assert!(
        reporter,
        paint_options.num_combinations() == NUM_EXPECTED,
        "Actual # of combinations {}, expected {}",
        paint_options.num_combinations(),
        NUM_EXPECTED
    );

    let precompile_ids = collect_precompile_ids(&paint_options, key_context, render_pass_desc);
    assert_count(&precompile_ids, NUM_EXPECTED);
}

// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L214-L252 (chrome/m156)
#[allow(clippy::too_many_arguments)] // mirrors the C++ template's parameters
fn create_runtime_combos<T: Clone>(
    reporter: &mut Reporter,
    effect_factory: impl Fn(&str) -> Result<RuntimeEffect, String>,
    precompile_factory: impl Fn(RuntimeEffect, &[Vec<Option<PrecompileBaseHandle>>]) -> Option<T>,
    wrap: fn(T) -> PrecompileBaseHandle,
    red_code: &str,
    green_code: &str,
    blue_code: &str,
    combine_code: &str,
) -> Option<T> {
    let red_effect = effect_factory(red_code);
    reporter_assert!(
        reporter,
        red_effect.is_ok(),
        "{}",
        red_effect.as_ref().err().map_or("", String::as_str)
    );
    let green_effect = effect_factory(green_code);
    reporter_assert!(
        reporter,
        green_effect.is_ok(),
        "{}",
        green_effect.as_ref().err().map_or("", String::as_str)
    );
    let blue_effect = effect_factory(blue_code);
    reporter_assert!(
        reporter,
        blue_effect.is_ok(),
        "{}",
        blue_effect.as_ref().err().map_or("", String::as_str)
    );
    let combine_effect = effect_factory(combine_code);
    reporter_assert!(
        reporter,
        combine_effect.is_ok(),
        "{}",
        combine_effect.as_ref().err().map_or("", String::as_str)
    );

    let red = precompile_factory(red_effect.expect("red effect"), &[]);
    reporter_assert!(reporter, red.is_some());
    let green = precompile_factory(green_effect.expect("green effect"), &[]);
    reporter_assert!(reporter, green.is_some());
    let blue = precompile_factory(blue_effect.expect("blue effect"), &[]);
    reporter_assert!(reporter, blue.is_some());

    let (red, green, blue) = (red?, green?, blue?);
    let combine = precompile_factory(
        combine_effect.expect("combine effect"),
        &[
            vec![Some(wrap(red)), Some(wrap(green))],
            vec![Some(wrap(blue)), None],
        ],
    );
    reporter_assert!(reporter, combine.is_some());
    combine
}

// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L254-L345 (chrome/m156)
fn runtime_effect_test(
    key_context: &KeyContext<'_>,
    render_pass_desc: &RenderPassDesc,
    reporter: &mut Reporter,
) {
    // paintOptions (64 = 4*4*4)
    //  |- combineShader (4)
    //  |       0: redShader  | greenShader
    //  |       1: blueShader | nullptr
    //  |
    //  |- combineColorFilter (4)
    //  |       0: redColorFilter  | greenColorFilter
    //  |       1: blueColorFilter | nullptr
    //  |
    //  |- combineBlender (4)
    //  |       0: redBlender  | greenBlender
    //  |       1: blueBlender | nullptr

    let mut paint_options = PaintOptions::new();

    // shaders
    {
        const RED_S: &str = "
            half4 main(vec2 fragcoord) { return half4(.5, 0, 0, .5); }
        ";
        const GREEN_S: &str = "
            half4 main(vec2 fragcoord) { return half4(0, .5, 0, .5); }
        ";
        const BLUE_S: &str = "
            half4 main(vec2 fragcoord) { return half4(0, 0, .5, .5); }
        ";
        const COMBINE_S: &str = "
            uniform shader first;
            uniform shader second;
            half4 main(vec2 fragcoords) {
                return first.eval(fragcoords) + second.eval(fragcoords);
            }
        ";
        let combination = create_runtime_combos::<PrecompileShader>(
            reporter,
            |code| RuntimeEffect::make_for_shader(code, None),
            PrecompileRuntimeEffects::make_precompile_shader,
            PrecompileBaseHandle::Shader,
            RED_S,
            GREEN_S,
            BLUE_S,
            COMBINE_S,
        );
        paint_options.set_shaders(&combination.into_iter().collect::<Vec<_>>());
    }

    // color filters
    {
        const RED_CF: &str = "
            half4 main(half4 color) { return half4(.5, 0, 0, .5); }
        ";
        const GREEN_CF: &str = "
            half4 main(half4 color) { return half4(0, .5, 0, .5); }
        ";
        const BLUE_CF: &str = "
            half4 main(half4 color) { return half4(0, 0, .5, .5); }
        ";
        const COMBINE_CF: &str = "
            uniform colorFilter first;
            uniform colorFilter second;
            half4 main(half4 color) { return first.eval(color) + second.eval(color); }
        ";
        let combination = create_runtime_combos::<PrecompileColorFilter>(
            reporter,
            |code| RuntimeEffect::make_for_color_filter(code, None),
            PrecompileRuntimeEffects::make_precompile_color_filter,
            PrecompileBaseHandle::ColorFilter,
            RED_CF,
            GREEN_CF,
            BLUE_CF,
            COMBINE_CF,
        );
        paint_options.set_color_filters(&[combination]);
    }

    // blenders
    {
        const RED_B: &str = "
            half4 main(half4 src, half4 dst) { return half4(.5, 0, 0, .5); }
        ";
        const GREEN_B: &str = "
            half4 main(half4 src, half4 dst) { return half4(0, .5, 0, .5); }
        ";
        const BLUE_B: &str = "
            half4 main(half4 src, half4 dst) { return half4(0, 0, .5, .5); }
        ";
        const COMBINE_B: &str = "
            uniform blender first;
            uniform blender second;
            half4 main(half4 src, half4 dst) {
                return first.eval(src, dst) + second.eval(src, dst);
            }
        ";
        let combination = create_runtime_combos(
            reporter,
            |code| RuntimeEffect::make_for_blender(code, None),
            PrecompileRuntimeEffects::make_precompile_blender,
            PrecompileBaseHandle::Blender,
            RED_B,
            GREEN_B,
            BLUE_B,
            COMBINE_B,
        );
        paint_options.set_blenders(&combination.into_iter().collect::<Vec<_>>());
    }

    reporter_assert!(reporter, paint_options.num_combinations() == 64);

    let precompile_ids = collect_precompile_ids(&paint_options, key_context, render_pass_desc);
    assert_count(&precompile_ids, 64);
}

// Exercise all the PrecompileBlenders factories
// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L347-L375 (chrome/m156)
fn blend_subtest(
    key_context: &KeyContext<'_>,
    render_pass_desc: &RenderPassDesc,
    reporter: &mut Reporter,
) {
    // The BlendMode PrecompileBlender only ever has 1 combination
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_blenders(&[PrecompileBlenders::mode(BlendMode::ColorDodge)]);
        run_test(key_context, render_pass_desc, reporter, &paint_options, 1);
    }
    // Specifying the BlendMode PrecompileBlender by SkBlendMode should also only ever
    // yield 1 combination.
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_blend_modes(&[BlendMode::SrcOver]);
        run_test(key_context, render_pass_desc, reporter, &paint_options, 1);
    }
    // The Arithmetic PrecompileBlender only ever has 1 combination
    {
        let mut paint_options = PaintOptions::new();
        let arithmetic = PrecompileBlenders::arithmetic().expect("the arithmetic blender");
        paint_options.set_blenders(&[arithmetic]);
        run_test(key_context, render_pass_desc, reporter, &paint_options, 1);
    }
}

// Exercise all the PrecompileShaders factories
// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L377-L521 (chrome/m156)
#[allow(clippy::too_many_lines)] // mirrors the C++ test, one block per factory
fn shader_subtest(
    key_context: &KeyContext<'_>,
    render_pass_desc: &RenderPassDesc,
    reporter: &mut Reporter,
) {
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::empty()]);
        run_test(key_context, render_pass_desc, reporter, &paint_options, 1);
    }
    // The solid color shader only ever generates one combination. Because it is constant
    // everywhere it can cause other shaders to be elided (e.g., the LocalMatrix shader -
    // see the LocalMatrix test(s) below).
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::color()]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_SOLID_COLOR_COMBOS,
        );
    }
    // In general, the blend shader generates the product of the options in each of its slots.
    // The rules for how many combinations the SkBlendModes yield are:
    //   all Porter-Duff SkBlendModes collapse to one option (see GetPorterDuffBlendConstants))
    //   all HSCL SkBlendModes collapse to another option
    //   all other SkBlendModes produce unique options
    {
        let blend_modes = [
            BlendMode::SrcOut,  // Porter-Duff
            BlendMode::SrcOver, // Porter-Duff
            BlendMode::Hue,     // HSLC
            BlendMode::Color,   // HSLC
            BlendMode::Screen,  // Fixed Screen
            BlendMode::Darken,  // fixed Darken
        ];
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::blend_modes(
            &blend_modes,
            &[PrecompileShaders::color()],
            &[PrecompileShaders::make_fractal_noise()],
        )]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            // Porter-Duff, HSLC, Screen, Darken
            4 * EXPECTED_SOLID_COLOR_COMBOS * EXPECTED_PERLIN_NOISE_COMBOS,
        );
    }
    // The ImageShaders have 24 combinations
    // (6 sampling/tiling x 4 color space xform)
    // The CoordClamp shader doesn't add any additional combinations to its wrapped shader.
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::coord_clamp(&[PrecompileShaders::image(
            ImageShaderFlags::ALL,
            &[],
            &ALL_TILE_MODES,
        )])]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_IMAGE_COMBOS,
        );
    }
    // RawImageShaders only have 10 combinations since they never do cubic filtering and only have
    // two possible color space xform variants.
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::raw_image(
            ImageShaderFlags::EXCLUDE_CUBIC,
            &[],
            &ALL_TILE_MODES,
        )]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_RAW_IMAGE_COMBOS,
        );
    }
    // Each Perlin noise shader only has one combination
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[
            PrecompileShaders::make_fractal_noise(),
            PrecompileShaders::make_turbulence(),
        ]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_PERLIN_NOISE_COMBOS + EXPECTED_PERLIN_NOISE_COMBOS,
        );
    }
    // Each gradient shader generates 3 combinations x 2 opacities
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[
            PrecompileShaders::linear_gradient(GradientShaderFlags::ALL, Interpolation::default()),
            PrecompileShaders::radial_gradient(GradientShaderFlags::ALL, Interpolation::default()),
            PrecompileShaders::two_point_conical_gradient(
                GradientShaderFlags::ALL,
                Interpolation::default(),
            ),
            PrecompileShaders::sweep_gradient(GradientShaderFlags::ALL, Interpolation::default()),
        ]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_GRADIENT_COMBOS * 4,
        );
    }
    // Each picture shader generates 48 combinations:
    //    2 (pictureShader LM) x 24 (imageShader variations)
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::picture()]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_PICTURE_COMBOS,
        );
    }
    // In general, the local matrix shader just generates however many options its wrapped
    // shader generates.
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::local_matrix(
            &[PrecompileShaders::linear_gradient(
                GradientShaderFlags::ALL,
                Interpolation::default(),
            )],
            false,
        )]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_GRADIENT_COMBOS,
        );
    }
    // The ColorFilter shader just creates the cross product of its child options
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::color_filter(
            &[PrecompileShaders::linear_gradient(
                GradientShaderFlags::ALL,
                Interpolation::default(),
            )],
            &[PrecompileColorFilters::blend()],
        )]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_GRADIENT_COMBOS * EXPECTED_BLEND_CF_COMBOS,
        );
    }
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_shaders(&[PrecompileShaders::working_color_space(
            &[PrecompileShaders::linear_gradient(
                GradientShaderFlags::ALL,
                Interpolation::default(),
            )],
            &[ColorSpace::new_srgb_linear()],
            &[],
        )]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_GRADIENT_COMBOS, // only one colorSpace
        );
    }
}

// Exercise all the PrecompileColorFilters factories. The impact of colorfilters on the number
// of combinations is very predictable. Except for the Compose and Lerp color filters, all the
// color filters only ever have one combination. The Compose and Lerp color filters also just
// simply generate the cross product of their children.
// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L523-L592 (chrome/m156)
fn colorfilter_subtest(
    key_context: &KeyContext<'_>,
    render_pass_desc: &RenderPassDesc,
    reporter: &mut Reporter,
) {
    {
        // The compose colorfilter just generates the cross product of its children.
        let expected_num_options = EXPECTED_TABLE_CF_COMBOS
            * (EXPECTED_HIGH_CONTRAST_CF_COMBOS + EXPECTED_LUMA_CF_COMBOS)
            + EXPECTED_LIGHTING_CF_COMBOS
                * (EXPECTED_HIGH_CONTRAST_CF_COMBOS + EXPECTED_LUMA_CF_COMBOS);
        let mut paint_options = PaintOptions::new();
        paint_options.set_color_filters(&[PrecompileColorFilters::compose(
            &[
                Some(PrecompileColorFilters::table()),
                Some(PrecompileColorFilters::lighting()),
            ],
            &[
                PrecompileColorFilters::high_contrast(),
                PrecompileColorFilters::luma(),
            ],
        )]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            expected_num_options,
        );
    }
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_color_filters(&[Some(PrecompileColorFilters::blend())]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_BLEND_CF_COMBOS,
        );
    }
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_color_filters(&[
            Some(PrecompileColorFilters::matrix(true)),
            Some(PrecompileColorFilters::hsla_matrix()),
        ]);
        // HSLAMatrix and Matrix map to the same color filter
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_MATRIX_CF_COMBOS + EXPECTED_MATRIX_CF_COMBOS,
        );
    }
    {
        let mut paint_options = PaintOptions::new();
        paint_options.set_color_filters(&[
            Some(PrecompileColorFilters::linear_to_srgb_gamma()),
            Some(PrecompileColorFilters::srgb_to_linear_gamma()),
        ]);
        // LinearToSRGB and SRGBToLinear both map to the colorspace colorfilter
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            EXPECTED_COLOR_SPACE_CF_COMBOS + EXPECTED_COLOR_SPACE_CF_COMBOS,
        );
    }
    {
        // The lerp colorfilter just generates the cross product of its children.
        let expected_num_options = EXPECTED_MATRIX_CF_COMBOS
            * (EXPECTED_BLEND_CF_COMBOS + EXPECTED_OVERDRAW_CF_COMBOS)
            + EXPECTED_LUMA_CF_COMBOS * (EXPECTED_BLEND_CF_COMBOS + EXPECTED_OVERDRAW_CF_COMBOS);
        let mut paint_options = PaintOptions::new();
        paint_options.set_color_filters(&[PrecompileColorFilters::lerp(
            &[
                Some(PrecompileColorFilters::matrix(true)),
                PrecompileColorFilters::luma(),
            ],
            &[
                Some(PrecompileColorFilters::blend()),
                PrecompileColorFilters::overdraw(),
            ],
        )]);
        run_test(
            key_context,
            render_pass_desc,
            reporter,
            &paint_options,
            expected_num_options,
        );
    }
}

// Port of: tests/graphite/precompile/CombinationBuilderTest.cpp#L594-L625 (chrome/m156)
def_graphite_test_for_all_contexts!(CombinationBuilderTest, |reporter, context| {
    let dict = context.shared_context().shader_code_dictionary();
    let rt_effect_dict = Arc::new(RuntimeEffectDictionary::new());
    let ci = ColorInfo::new(ColorType::RGBA8888, AlphaType::Premul, None);
    let builder = RefCell::new(PaintParamsKeyBuilder::new(dict));
    let gatherer = RefCell::new(PipelineDataGatherer::new(Layout::Metal));
    let key_context = KeyContext::new(
        context.shared_context().caps().clone(),
        &builder,
        &gatherer,
        dict,
        rt_effect_dict,
        &ci,
    );
    let unused_render_pass_desc = RenderPassDesc::default();

    // The default PaintOptions should create a single combination with a solid color shader and
    // kSrcOver blending
    {
        let paint_options = PaintOptions::new();
        run_test(
            &key_context,
            &unused_render_pass_desc,
            reporter,
            &paint_options,
            1,
        );
    }
    blend_subtest(&key_context, &unused_render_pass_desc, reporter);
    shader_subtest(&key_context, &unused_render_pass_desc, reporter);
    colorfilter_subtest(&key_context, &unused_render_pass_desc, reporter);
    no_blend_mode_option_test(&key_context, &unused_render_pass_desc, reporter);
    big_test(&key_context, &unused_render_pass_desc, reporter);
    runtime_effect_test(&key_context, &unused_render_pass_desc, reporter);
});
