// Copyright 2015 Google Inc.
// Copyright 2026 The skia-rust Authors
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.
// Port of: tools/fonts/create_test_font.cpp output (the committed `.inc` files), chrome/m156
//
// `cargo xtask gen-test-fonts`: reads Skia's `tools/fonts/test_font_*.inc` and writes the Rust
// data in `tests/tools/src/fonts/test_font_data/`. The generator is the only writer of that
// directory; CI re-runs it and checks `git diff --exit-code`.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, bail};
use regex::Regex;

/// The `.inc` files that hold the point, verb, unichar and width arrays, with the Rust module
/// each one is written to.
const DATA_FILES: [(&str, &str); 3] = [
    ("test_font_monospace.inc", "monospace"),
    ("test_font_sans_serif.inc", "sans_serif"),
    ("test_font_serif.inc", "serif"),
];

/// The index file (`gTestFonts`, `gSubFonts`, `gDefaultFontIndex`).
const INDEX_FILE: &str = "test_font_index.inc";

/// One array declaration: its C++ name, the Rust element type and the literal tokens.
struct Array {
    name: String,
    kind: ArrayKind,
    values: Vec<String>,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum ArrayKind {
    /// `SkScalar`, written as `f32`.
    Scalar,
    /// `SkFixed`, written as `i32`.
    Fixed,
    /// `SkUnichar` (`int32_t`), written as `i32`.
    Unichar,
    /// `unsigned char`, written as `u8`.
    Byte,
}

/// One `SkFontMetrics` declaration.
struct Metrics {
    name: String,
    values: Vec<String>,
}

/// Entry point of `cargo xtask gen-test-fonts`.
pub fn run(root: &Path) -> Result<()> {
    let input = root
        .join("third_party")
        .join("skia")
        .join("tools")
        .join("fonts");
    if !input.is_dir() {
        bail!(
            "{} is missing; run `cargo xtask skia fetch` first",
            input.display()
        );
    }
    let output = root
        .join("tests")
        .join("tools")
        .join("src")
        .join("fonts")
        .join("test_font_data");
    fs::create_dir_all(&output).with_context(|| format!("creating {}", output.display()))?;

    let mut all_names: Vec<(String, &str)> = Vec::new();
    let mut all_metrics: Vec<(String, &str)> = Vec::new();
    for (file, module) in DATA_FILES {
        let src = read_inc(&input, file)?;
        let arrays = parse_arrays(&src)?;
        let metrics = parse_metrics(&src)?;
        let text = render_module(file, &arrays, &metrics);
        let path = output.join(format!("{module}.rs"));
        write_formatted(&path, &text)?;
        for array in &arrays {
            all_names.push((array.name.clone(), module));
        }
        for metric in &metrics {
            all_metrics.push((metric.name.clone(), module));
        }
    }

    let index = read_inc(&input, INDEX_FILE)?;
    let text = render_index(&index, &all_names, &all_metrics)?;
    write_formatted(&output.join("index.rs"), &text)?;
    let mut mods = String::from(
        "// Generated by `cargo xtask gen-test-fonts` (chrome/m156). Do not edit.\n\n",
    );
    for module in ["index"].into_iter().chain(DATA_FILES.map(|(_, m)| m)) {
        let _ = writeln!(mods, "pub mod {module};");
    }
    write_formatted(&output.join("mod.rs"), &mods)?;
    println!("wrote test font data to {}", output.display());
    Ok(())
}

fn read_inc(dir: &Path, file: &str) -> Result<String> {
    let path = dir.join(file);
    let src = fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    Ok(strip_comments(&src))
}

/// Removes `/* */` and `//` comments. The data arrays have none, but the file headers do.
fn strip_comments(src: &str) -> String {
    let block = Regex::new(r"(?s)/\*.*?\*/").expect("valid regex");
    let line = Regex::new(r"//[^\n]*").expect("valid regex");
    let src = block.replace_all(src, "");
    line.replace_all(&src, "").into_owned()
}

fn parse_arrays(src: &str) -> Result<Vec<Array>> {
    let re =
        Regex::new(r"(?s)const (SkScalar|SkFixed|SkUnichar|unsigned char) (\w+)\[\] = \{(.*?)\};")
            .expect("valid regex");
    let mut arrays = Vec::new();
    for cap in re.captures_iter(src) {
        let kind = match &cap[1] {
            "SkScalar" => ArrayKind::Scalar,
            "SkFixed" => ArrayKind::Fixed,
            "SkUnichar" => ArrayKind::Unichar,
            _ => ArrayKind::Byte,
        };
        arrays.push(Array {
            name: cap[2].to_owned(),
            kind,
            values: tokens(&cap[3]),
        });
    }
    Ok(arrays)
}

fn parse_metrics(src: &str) -> Result<Vec<Metrics>> {
    let re = Regex::new(r"(?s)const SkFontMetrics (\w+) = \{(.*?)\};").expect("valid regex");
    let mut out = Vec::new();
    for cap in re.captures_iter(src) {
        let values = tokens(&cap[2]);
        // fFlags, then the 15 scalars of SkFontMetrics, in declaration order.
        if values.len() != 16 {
            bail!(
                "SkFontMetrics {} has {} fields, expected 16",
                &cap[1],
                values.len()
            );
        }
        out.push(Metrics {
            name: cap[1].to_owned(),
            values,
        });
    }
    Ok(out)
}

fn tokens(body: &str) -> Vec<String> {
    body.split(',')
        .map(str::trim)
        .filter(|t| !t.is_empty())
        .map(str::to_owned)
        .collect()
}

/// Converts a C++ float literal (`0.225098f`) to Rust (`0.225098_f32`). The digits are kept
/// verbatim; both languages round a decimal literal to the nearest `f32`.
fn scalar_literal(token: &str) -> Result<String> {
    // Some metrics are written without the suffix (`0`); C++ converts those to float too.
    let number = token.strip_suffix('f').unwrap_or(token);
    let number = if number.ends_with('.') {
        format!("{number}0")
    } else if number.contains(['.', 'e', 'E']) {
        number.to_owned()
    } else {
        format!("{number}.0")
    };
    if !number.parse::<f64>().is_ok_and(f64::is_finite) {
        bail!("scalar literal {token} is not a finite decimal");
    }
    Ok(format!("{number}_f32"))
}

fn element_type(kind: ArrayKind) -> &'static str {
    match kind {
        ArrayKind::Scalar => "f32",
        ArrayKind::Fixed => "i32",
        ArrayKind::Unichar => "i32",
        ArrayKind::Byte => "u8",
    }
}

fn screaming_snake(name: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = name.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if i > 0 && c.is_ascii_uppercase() {
            let prev = chars[i - 1];
            let next_lower = chars.get(i + 1).is_some_and(char::is_ascii_lowercase);
            if prev.is_ascii_lowercase()
                || prev.is_ascii_digit()
                || (prev.is_ascii_uppercase() && next_lower)
            {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

fn render_module(file: &str, arrays: &[Array], metrics: &[Metrics]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by `cargo xtask gen-test-fonts` from tools/fonts/{file} (chrome/m156)."
    );
    let _ = writeln!(
        out,
        "// Do not edit: the generator is the only writer of this file."
    );
    out.push_str("#![allow(clippy::excessive_precision, clippy::unreadable_literal)] // verbatim from the .inc literals\n\n");
    out.push_str("use skia_rust_core::font_metrics::{Flags, FontMetrics};\n\n");
    for array in arrays {
        let ty = element_type(array.kind);
        let _ = writeln!(
            out,
            "pub const {}: &[{ty}] = &[",
            screaming_snake(&array.name)
        );
        for value in &array.values {
            let literal = if array.kind == ArrayKind::Scalar {
                scalar_literal(value).unwrap_or_else(|e| panic!("{e}"))
            } else {
                value.clone()
            };
            let _ = writeln!(out, "    {literal},");
        }
        out.push_str("];\n\n");
    }
    for metric in metrics {
        let v = &metric.values;
        let _ = writeln!(
            out,
            "pub const {}: FontMetrics = FontMetrics {{",
            screaming_snake(&metric.name)
        );
        let _ = writeln!(out, "    flags: Flags::from_bits_retain({}),", v[0]);
        let fields = [
            "top",
            "ascent",
            "descent",
            "bottom",
            "leading",
            "avg_char_width",
            "max_char_width",
            "x_min",
            "x_max",
            "x_height",
            "cap_height",
            "underline_thickness",
            "underline_position",
            "strikeout_thickness",
            "strikeout_position",
        ];
        for (field, value) in fields.iter().zip(&v[1..]) {
            let _ = writeln!(
                out,
                "    {field}: {},",
                scalar_literal(value).unwrap_or_else(|e| panic!("{e}"))
            );
        }
        out.push_str("};\n\n");
    }
    out
}

/// One `gTestFonts` entry, or one `gSubFonts` entry, after parsing.
struct TestFont {
    points: String,
    verbs: String,
    char_codes: String,
    widths: String,
    metrics: String,
    name: String,
    weight: i32,
    width: i32,
    slant: &'static str,
}

struct SubFontEntry {
    family: String,
    style: String,
    weight: i32,
    width: i32,
    slant: &'static str,
    font: usize,
    file: String,
}

fn slant_variant(name: &str) -> Result<&'static str> {
    Ok(match name {
        "kUpright_Slant" => "Upright",
        "kItalic_Slant" => "Italic",
        "kOblique_Slant" => "Oblique",
        other => bail!("unknown slant {other}"),
    })
}

fn section<'a>(src: &'a str, start: &str) -> Result<&'a str> {
    let begin = src
        .find(start)
        .with_context(|| format!("index section {start} not found"))?;
    let rest = &src[begin..];
    let end = rest
        .find("};")
        .with_context(|| format!("index section {start} is not closed"))?;
    Ok(&rest[start.len()..end])
}

fn render_index(src: &str, names: &[(String, &str)], metrics: &[(String, &str)]) -> Result<String> {
    let module_of = |name: &str| -> Result<&str> {
        names
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, m)| *m)
            .with_context(|| format!("array {name} is not declared in any data file"))
    };
    let metrics_of = |name: &str| -> Result<String> {
        let module = metrics
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, m)| *m)
            .with_context(|| format!("metrics {name} is not declared in any data file"))?;
        Ok(format!("{module}::{}", screaming_snake(name)))
    };
    let array_ref = |name: &str| -> Result<String> {
        Ok(format!("{}::{}", module_of(name)?, screaming_snake(name)))
    };

    let test_font_re = Regex::new(
        r#"(?s)\{\s*(\w+),\s*(\w+),\s*(\w+),\s*(\w+),\s*(\w+),\s*(\w+),\s*"([^"]*)",\s*SkFontStyle\((\d+),\s*(\d+),\s*SkFontStyle::(\w+)\)\s*\}"#,
    )
    .expect("valid regex");
    let mut fonts = Vec::new();
    for cap in test_font_re.captures_iter(section(src, "static SkTestFontData gTestFonts[] = {")?) {
        // The fourth field is `<CharCodes>Count`, which is `std::size` of the array: the Rust
        // slice length replaces it.
        let char_codes = cap[3].to_owned();
        if cap[4] != format!("{char_codes}Count") {
            bail!("char code count {} does not match {char_codes}", &cap[4]);
        }
        fonts.push(TestFont {
            points: cap[1].to_owned(),
            verbs: cap[2].to_owned(),
            char_codes,
            widths: cap[5].to_owned(),
            metrics: cap[6].to_owned(),
            name: cap[7].to_owned(),
            weight: cap[8].parse()?,
            width: cap[9].parse()?,
            slant: slant_variant(&cap[10])?,
        });
    }

    let sub_re = Regex::new(
        r#"(?s)\{\s*"([^"]*)",\s*"([^"]*)",\s*SkFontStyle\((\d+),\s*(\d+),\s*SkFontStyle::(\w+)\),\s*gTestFonts\[(\d+)\],\s*"([^"]*)"\s*\}"#,
    )
    .expect("valid regex");
    let mut subs = Vec::new();
    for cap in sub_re.captures_iter(section(src, "const SubFont gSubFonts[] = {")?) {
        subs.push(SubFontEntry {
            family: cap[1].to_owned(),
            style: cap[2].to_owned(),
            weight: cap[3].parse()?,
            width: cap[4].parse()?,
            slant: slant_variant(&cap[5])?,
            font: cap[6].parse()?,
            file: cap[7].to_owned(),
        });
    }

    let default_re = Regex::new(r"const size_t gDefaultFontIndex = (\d+);").expect("valid regex");
    let default_index: usize = default_re
        .captures(src)
        .context("gDefaultFontIndex not found")?[1]
        .parse()?;

    let mut out = String::new();
    out.push_str("// Generated by `cargo xtask gen-test-fonts` from tools/fonts/test_font_index.inc (chrome/m156).\n");
    out.push_str("// Do not edit: the generator is the only writer of this file.\n\n");
    out.push_str("use skia_rust_core::font_style::Slant;\n\n");
    out.push_str("use super::{monospace, sans_serif, serif};\n");
    out.push_str("use crate::fonts::test_typeface::{SubFont, TestFontData};\n\n");
    let _ = writeln!(
        out,
        "/// `gTestFonts`: the twelve Liberation faces, by index."
    );
    let _ = writeln!(
        out,
        "pub static TEST_FONTS: [TestFontData; {}] = [",
        fonts.len()
    );
    for font in &fonts {
        out.push_str("    TestFontData {\n");
        let _ = writeln!(out, "        points: {},", array_ref(&font.points)?);
        let _ = writeln!(out, "        verbs: {},", array_ref(&font.verbs)?);
        let _ = writeln!(out, "        char_codes: {},", array_ref(&font.char_codes)?);
        let _ = writeln!(out, "        widths: {},", array_ref(&font.widths)?);
        let _ = writeln!(out, "        metrics: &{},", metrics_of(&font.metrics)?);
        let _ = writeln!(out, "        name: {:?},", font.name);
        let _ = writeln!(out, "        weight: {},", font.weight);
        let _ = writeln!(out, "        width: {},", font.width);
        let _ = writeln!(out, "        slant: Slant::{},", font.slant);
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
    let _ = writeln!(
        out,
        "/// `gSubFonts`: every face of every family, in Skia's order."
    );
    let _ = writeln!(out, "pub static SUB_FONTS: [SubFont; {}] = [", subs.len());
    for sub in &subs {
        let _ = writeln!(
            out,
            "    SubFont {{ family: {:?}, style: {:?}, weight: {}, width: {}, slant: Slant::{}, font: {}, file: {:?} }},",
            sub.family, sub.style, sub.weight, sub.width, sub.slant, sub.font, sub.file
        );
    }
    out.push_str("];\n\n");
    let _ = writeln!(out, "/// `gDefaultFontIndex`: an index into [`SUB_FONTS`].");
    let _ = writeln!(
        out,
        "pub const DEFAULT_FONT_INDEX: usize = {default_index};"
    );
    Ok(out)
}

fn write_formatted(path: &Path, text: &str) -> Result<()> {
    fs::write(path, text).with_context(|| format!("writing {}", path.display()))?;
    let status = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(path)
        .status()
        .context("running rustfmt on generated test font data")?;
    if !status.success() {
        bail!("rustfmt failed on {}", path.display());
    }
    Ok(())
}
