//! The test inventory: every Skia test, GM, bench, fuzzer and data-driven test
//! at the pinned commit, with its porting status. See `docs/PLAN.md` §6.1.

use std::collections::{BTreeMap, HashMap};
use std::fmt::Write as _;
use std::path::Path;

use anyhow::{Context, Result, bail, ensure};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use walkdir::WalkDir;

use crate::cpp;
use crate::skia::{self, Pin};
use crate::{verify, verify_gms};

const MANIFEST: &str = "inventory/manifest.toml";

/// Directories of the Skia tree scanned for registration macros.
const SCAN_DIRS: &[&str] = &["tests", "gm", "bench", "fuzz", "modules"];

/// `SkSL` code generators skia-rust ports. Expected outputs for any other
/// generator are excluded.
const SKSL_PORTED_EXTENSIONS: &[&str] = &["wgsl", "skrp", "sksl", "stage"];

/// `tests/sksl/errors/*.glsl` are error-text goldens, scanned as in scope.
const SKSL_ERROR_TEXT_DIR: &str = "tests/sksl/errors/";

#[derive(Debug, Serialize, Deserialize)]
struct Manifest {
    skia: Pin,
    #[serde(default, rename = "test")]
    tests: Vec<Entry>,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(rename_all = "kebab-case")]
enum Kind {
    /// `DEF_TEST` and friends: assertion-based unit tests.
    Unit,
    /// `DEF_GM` and friends: image-producing golden tests.
    Gm,
    /// `DEF_BENCH` and friends.
    Bench,
    /// `DEF_FUZZ`.
    Fuzz,
    /// An expected `SkSL` compiler output in `tests/sksl`.
    SkslGolden,
    /// An image in `resources/images`, decoded by DM's image source.
    DmImage,
    /// A Lottie file in `resources/skottie`, rendered by DM's lottie source.
    DmLottie,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(rename_all = "kebab-case")]
enum Status {
    Todo,
    Ported,
    Failing,
    Passing,
    /// Was ported, but the upstream source changed since.
    Stale,
    Excluded,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct Entry {
    id: String,
    kind: Kind,
    #[serde(rename = "macro", default, skip_serializing_if = "String::is_empty")]
    macro_name: String,
    /// `path#Lstart-Lend` in the Skia tree.
    source: String,
    /// Hand-editable; initialized from a path/keyword heuristic.
    module: String,
    status: Status,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    reason: String,
    /// SHA-256 of the registration span (or whole file for data-driven tests).
    span_hash: String,
}

pub fn sync(root: &Path, allow_pin_mismatch: bool) -> Result<()> {
    let pin = skia::read_pin(root)?;
    let skia_dir = skia::checkout_path(root);
    let head = skia::checkout_commit(root)
        .context("third_party/skia missing; run `cargo xtask skia fetch`")?;
    if head != pin.commit && !allow_pin_mismatch {
        bail!("third_party/skia is at {head}, pin is {}", pin.commit);
    }

    let scanned = scan(&skia_dir)?;
    let manifest_path = root.join(MANIFEST);
    let old: HashMap<String, Entry> = if manifest_path.exists() {
        let text = std::fs::read_to_string(&manifest_path)?;
        let m: Manifest = toml::from_str(&text).context("parsing manifest")?;
        m.tests.into_iter().map(|e| (e.id.clone(), e)).collect()
    } else {
        HashMap::new()
    };

    let (mut added, mut stale) = (0, 0);
    let mut tests = Vec::with_capacity(scanned.len());
    for mut entry in scanned {
        match old.get(&entry.id) {
            Some(prev) => {
                entry.module.clone_from(&prev.module);
                entry.reason.clone_from(&prev.reason);
                entry.status = prev.status;
                let was_ported = matches!(
                    prev.status,
                    Status::Ported | Status::Failing | Status::Passing
                );
                if was_ported && prev.span_hash != entry.span_hash {
                    entry.status = Status::Stale;
                    entry.reason = format!("upstream changed (was {:?})", prev.status);
                    stale += 1;
                }
            }
            None => added += 1,
        }
        tests.push(entry);
    }
    let removed = old.len() + added - tests.len();

    let manifest = Manifest { skia: pin, tests };
    write_manifest(root, &manifest)?;
    println!(
        "{} entries ({added} added, {removed} removed, {stale} marked stale) -> {MANIFEST}",
        manifest.tests.len()
    );
    Ok(())
}

fn read_manifest(root: &Path) -> Result<Manifest> {
    let text = std::fs::read_to_string(root.join(MANIFEST))
        .context("no manifest; run `cargo xtask inventory sync`")?;
    toml::from_str(&text).context("parsing manifest")
}

fn write_manifest(root: &Path, manifest: &Manifest) -> Result<()> {
    let mut text = String::from(
        "# Generated by `cargo xtask inventory sync`. Hand-editable fields: module, status, reason.\n",
    );
    text.push_str(&toml::to_string(manifest)?);
    std::fs::write(root.join(MANIFEST), text)?;
    Ok(())
}

fn status_name(status: Status) -> &'static str {
    match status {
        Status::Todo => "todo",
        Status::Ported => "ported",
        Status::Failing => "failing",
        Status::Passing => "passing",
        Status::Stale => "stale",
        Status::Excluded => "excluded",
    }
}

/// Prints the Rust test path a manifest unit-test id must be ported to.
pub fn module_path(root: &Path, id: &str) -> Result<()> {
    let m = read_manifest(root)?;
    let entry = m
        .tests
        .iter()
        .find(|e| e.id == id)
        .with_context(|| format!("no manifest entry `{id}`"))?;
    ensure!(entry.kind == Kind::Unit, "`{id}` is not a unit test");
    let path = verify::module_path(id).with_context(|| format!("can't map `{id}`"))?;
    println!("{path}");
    Ok(())
}

/// Runs the ported unit tests and checks them against the manifest. With `update`,
/// marks newly passing entries `passing` and failing ported ones `failing`.
pub fn verify(root: &Path, update: bool) -> Result<()> {
    let mut m = read_manifest(root)?;
    let entries = |kind: Kind| -> Vec<(String, String)> {
        m.tests
            .iter()
            .filter(|e| e.kind == kind)
            .map(|e| (e.id.clone(), status_name(e.status).to_owned()))
            .collect()
    };
    let unit_entries = entries(Kind::Unit);
    let gm_entries = entries(Kind::Gm);
    let unit = verify::check(&unit_entries, &verify::run_ported_tests(root)?);
    let gms = verify_gms::check(&gm_entries, &verify_gms::run_gm_verify(root)?);
    if update {
        for report in [&unit, &gms] {
            apply_update(&mut m, report);
        }
        write_manifest(root, &m)?;
    }
    let unit_result = verify::finish(&unit, update, "unit test");
    let gm_result = verify::finish(&gms, update, "GM");
    unit_result.and(gm_result)
}

/// Marks newly passing entries `passing` and failing ported ones `failing`.
fn apply_update(m: &mut Manifest, report: &verify::Report) {
    for e in &mut m.tests {
        if report.newly_passing.iter().any(|(id, _)| *id == e.id) {
            e.status = Status::Passing;
            e.reason.clear();
        } else if report.failing.contains(&e.id) && e.status != Status::Failing {
            e.status = Status::Failing;
            if e.reason.is_empty() {
                let reason = if e.kind == Kind::Gm {
                    "ported GM does not match the goldens"
                } else {
                    "ported test fails"
                };
                reason.clone_into(&mut e.reason);
            }
        }
    }
}

pub fn stats(root: &Path) -> Result<()> {
    let text = std::fs::read_to_string(root.join(MANIFEST))
        .context("no manifest; run `cargo xtask inventory sync`")?;
    let m: Manifest = toml::from_str(&text)?;

    let mut by_kind: BTreeMap<Kind, BTreeMap<Status, usize>> = BTreeMap::new();
    let mut by_module: BTreeMap<&str, BTreeMap<Status, usize>> = BTreeMap::new();
    for e in &m.tests {
        *by_kind
            .entry(e.kind)
            .or_default()
            .entry(e.status)
            .or_default() += 1;
        *by_module
            .entry(&e.module)
            .or_default()
            .entry(e.status)
            .or_default() += 1;
    }

    println!("Skia {} ({})\n", m.skia.branch, m.skia.commit);
    print_table("kind", by_kind.iter().map(|(k, v)| (format!("{k:?}"), v)));
    println!();
    print_table(
        "module",
        by_module.iter().map(|(k, v)| ((*k).to_owned(), v)),
    );
    Ok(())
}

fn print_table<'a>(label: &str, rows: impl Iterator<Item = (String, &'a BTreeMap<Status, usize>)>) {
    println!(
        "{label:<16} {:>7} {:>8} {:>8} {:>8} {:>7}",
        "total", "excluded", "in-scope", "passing", "rate"
    );
    let (mut t_total, mut t_excl, mut t_pass) = (0, 0, 0);
    for (name, counts) in rows {
        let total: usize = counts.values().sum();
        let excl = counts.get(&Status::Excluded).copied().unwrap_or(0);
        let pass = counts.get(&Status::Passing).copied().unwrap_or(0);
        println!(
            "{name:<16} {total:>7} {excl:>8} {:>8} {pass:>8} {:>7}",
            total - excl,
            rate(pass, total - excl)
        );
        t_total += total;
        t_excl += excl;
        t_pass += pass;
    }
    println!(
        "{:<16} {t_total:>7} {t_excl:>8} {:>8} {t_pass:>8} {:>7}",
        "TOTAL",
        t_total - t_excl,
        rate(t_pass, t_total - t_excl)
    );
}

fn rate(pass: usize, of: usize) -> String {
    if of == 0 {
        return "-".to_owned();
    }
    // Integer per-mille avoids float casts; one decimal place is plenty.
    let permille = pass * 1000 / of;
    format!("{}.{}%", permille / 10, permille % 10)
}

/// Scan the Skia tree and produce fresh entries with default hand-edited fields.
fn scan(skia: &Path) -> Result<Vec<Entry>> {
    let macros = MacroTable::build(skia)?;
    let mut entries = Vec::new();
    for dir in SCAN_DIRS {
        for file in WalkDir::new(skia.join(dir)).sort_by_file_name() {
            let file = file?;
            let path = file.path();
            let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
            if !matches!(ext, "cpp" | "mm") {
                continue;
            }
            let rel = rel_path(skia, path);
            let src = read_lossy(path).with_context(|| format!("reading {rel}"))?;
            scan_source(&rel, &src, &macros, &mut entries);
        }
    }
    scan_sksl_goldens(skia, &mut entries)?;
    scan_resources(
        skia,
        "resources/images",
        Kind::DmImage,
        "dm/image",
        "codec",
        &mut entries,
    )?;
    scan_resources(
        skia,
        "resources/skottie",
        Kind::DmLottie,
        "dm/lottie",
        "skottie",
        &mut entries,
    )?;
    entries.sort_by(|a, b| a.id.cmp(&b.id));
    Ok(entries)
}

fn scan_source(rel: &str, src: &str, macros: &MacroTable, out: &mut Vec<Entry>) {
    let macros = macros.scope(src);
    let mut seen: HashMap<String, usize> = HashMap::new();
    for u in cpp::find_macro_uses(src, &|name| macros.is_registration(name)) {
        let kind = macros.kind(&u.name);
        // SKSL_TEST(flags, ctsEnforcement, name, path); everything else names itself first.
        let raw_name = if u.name == "SKSL_TEST" {
            u.args.get(2)
        } else {
            u.args.first()
        };
        let name = normalize_name(raw_name.map_or("", String::as_str));
        let n = seen.entry(name.clone()).or_insert(0);
        *n += 1;
        let id = if *n == 1 {
            format!("{rel}::{name}")
        } else {
            format!("{rel}::{name}#{n}")
        };
        let (status, reason) = match policy_exclusion(&macros.expansion(&u.name), rel) {
            Some(reason) => (Status::Excluded, reason.to_owned()),
            None => (Status::Todo, String::new()),
        };
        out.push(Entry {
            id,
            kind,
            macro_name: u.name.clone(),
            source: format!("{rel}#L{}-L{}", u.line, u.end_line),
            module: guess_module(rel, &u.name, &name, kind),
            status,
            reason,
            span_hash: sha256_hex(normalize_ws(&u.span).as_bytes()),
        });
    }
}

fn scan_sksl_goldens(skia: &Path, out: &mut Vec<Entry>) -> Result<()> {
    for file in WalkDir::new(skia.join("tests/sksl")).sort_by_file_name() {
        let file = file?;
        if !file.file_type().is_file() {
            continue;
        }
        let rel = rel_path(skia, file.path());
        let ext = file
            .path()
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("");
        // Error goldens are compiled with `--glsl` but fail in the front end, before any
        // GLSL generator runs (`gn/sksl_tests.gni#L1059-L1061`), so they are in scope.
        let is_error_text = ext == "glsl" && rel.starts_with(SKSL_ERROR_TEXT_DIR);
        let (status, reason) = if SKSL_PORTED_EXTENSIONS.contains(&ext) || is_error_text {
            (Status::Todo, String::new())
        } else {
            (
                Status::Excluded,
                "SkSL code generator not used by skia-rust (only WGSL, Raster Pipeline, SkSL \
                 and pipeline-stage generators are ported)"
                    .to_owned(),
            )
        };
        out.push(Entry {
            id: rel.clone(),
            kind: Kind::SkslGolden,
            macro_name: String::new(),
            source: rel,
            module: "sksl".to_owned(),
            status,
            reason,
            span_hash: hash_file(file.path())?,
        });
    }
    Ok(())
}

fn scan_resources(
    skia: &Path,
    dir: &str,
    kind: Kind,
    id_prefix: &str,
    module: &str,
    out: &mut Vec<Entry>,
) -> Result<()> {
    for file in WalkDir::new(skia.join(dir)).sort_by_file_name() {
        let file = file?;
        if !file.file_type().is_file() {
            continue;
        }
        let rel = rel_path(skia, file.path());
        let name = rel
            .strip_prefix(dir)
            .unwrap_or(&rel)
            .trim_start_matches('/');
        out.push(Entry {
            id: format!("{id_prefix}/{name}"),
            kind,
            macro_name: String::new(),
            source: rel.clone(),
            module: module.to_owned(),
            status: Status::Todo,
            reason: String::new(),
            span_hash: hash_file(file.path())?,
        });
    }
    Ok(())
}

/// `#define`s from the scanned tree's headers, used to recognize Skia's wrapper
/// macros (`UNIX_ONLY_TEST`, `SHAPER_TEST`, `MAKE_GM`, ...) as registrations.
/// A `.cpp` file's own `#define`s are layered on top by [`MacroScope`].
struct MacroTable {
    bodies: HashMap<String, String>,
}

impl MacroTable {
    fn build(skia: &Path) -> Result<Self> {
        let mut bodies = HashMap::new();
        for dir in SCAN_DIRS {
            for file in WalkDir::new(skia.join(dir)) {
                let file = file?;
                if file.path().extension().and_then(|e| e.to_str()) == Some("h") {
                    merge_defines(&mut bodies, &read_lossy(file.path())?);
                }
            }
        }
        Ok(Self { bodies })
    }

    fn scope(&self, src: &str) -> MacroScope<'_> {
        let mut local = HashMap::new();
        merge_defines(&mut local, src);
        MacroScope {
            global: &self.bodies,
            local,
        }
    }
}

/// Platform-conditional definitions of the same name are merged.
fn merge_defines(into: &mut HashMap<String, String>, src: &str) {
    for (name, body) in cpp::collect_defines(src) {
        let slot: &mut String = into.entry(name).or_default();
        slot.push(' ');
        slot.push_str(&body);
    }
}

struct MacroScope<'a> {
    global: &'a HashMap<String, String>,
    local: HashMap<String, String>,
}

impl MacroScope<'_> {
    fn body(&self, name: &str) -> Option<&str> {
        self.local
            .get(name)
            .or_else(|| self.global.get(name))
            .map(String::as_str)
    }

    fn is_registration(&self, name: &str) -> bool {
        self.resolve(name, 0).is_some()
    }

    /// The registration kind a macro produces, if it registers anything.
    fn resolve(&self, name: &str, depth: usize) -> Option<Kind> {
        let body = self.body(name);
        if body.is_some_and(|b| b.trim().is_empty()) {
            return None; // e.g. `#define DEF_TEST_NOIMPL(name, reporter)`
        }
        if cpp::is_registration_macro(name) {
            return Some(macro_kind(name));
        }
        if depth > 8 {
            return None;
        }
        let found = body?
            .split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
            .find_map(|ident| {
                (ident != name)
                    .then(|| self.resolve(ident, depth + 1))
                    .flatten()
            })?;
        // A wrapper's own name is the better hint when it has one (`SHAPER_BENCH`).
        Some(
            if ["TEST", "GM", "BENCH", "FUZZ"]
                .iter()
                .any(|k| name.contains(k))
            {
                macro_kind(name)
            } else {
                found
            },
        )
    }

    fn kind(&self, name: &str) -> Kind {
        self.resolve(name, 0).unwrap_or(Kind::Unit)
    }

    /// The macro name plus its definition, for policy checks on wrappers.
    fn expansion(&self, name: &str) -> String {
        match self.body(name) {
            Some(body) if !cpp::is_registration_macro(name) => format!("{name} {body}"),
            _ => name.to_owned(),
        }
    }
}

/// Read a source file as text with CRLF normalized to LF, so scanning gives the same
/// result whatever the checkout's `core.autocrlf` is. (With CRLF, a `\` line splice
/// inside a string literal looks like an escaped `\r`, and the literal appears to end
/// at the line break.)
fn read_lossy(path: &Path) -> Result<String> {
    let bytes = std::fs::read(path)?;
    let text = String::from_utf8(bytes)
        .unwrap_or_else(|e| String::from_utf8_lossy(e.as_bytes()).into_owned());
    Ok(text.replace("\r\n", "\n"))
}

fn macro_kind(name: &str) -> Kind {
    if name.contains("BENCH") {
        Kind::Bench
    } else if name.contains("FUZZ") {
        Kind::Fuzz
    } else if name.contains("_GM") {
        Kind::Gm
    } else {
        Kind::Unit
    }
}

/// Exclusions that follow directly from the plan's scope decisions.
fn policy_exclusion(macro_name: &str, rel: &str) -> Option<&'static str> {
    if macro_name == "DEF_TEST_DISABLED" {
        return Some("disabled upstream (DEF_TEST_DISABLED)");
    }
    let graphite = macro_name.contains("GRAPHITE");
    if (macro_name.contains("GANESH") && !graphite) || macro_name.contains("GPU_GM") {
        return Some("Ganesh-only; Graphite is the only GPU backend in scope");
    }
    for (needle, reason) in [
        (
            "METAL",
            "Metal-backend internals; skia-rust's GPU backend is wgpu",
        ),
        (
            "VULKAN",
            "Vulkan-backend internals; skia-rust's GPU backend is wgpu",
        ),
        (
            "_GL_",
            "OpenGL-backend internals; skia-rust's GPU backend is wgpu",
        ),
    ] {
        if macro_name.contains(needle) && !macro_name.contains("DAWN") {
            return Some(reason);
        }
    }
    if Path::new(rel)
        .extension()
        .is_some_and(|e| e.eq_ignore_ascii_case("mm"))
    {
        return Some("Objective-C++ (Apple platform API) test");
    }
    None
}

/// Heuristic module assignment; hand edits in the manifest take precedence.
fn guess_module(rel: &str, macro_name: &str, name: &str, kind: Kind) -> String {
    if let Some(rest) = rel.strip_prefix("modules/") {
        let m = rest.split('/').next().unwrap_or("modules");
        return match m {
            "skparagraph" => "paragraph",
            "skshaper" => "shaper",
            "skunicode" => "unicode",
            other => other,
        }
        .to_owned();
    }
    if macro_name.contains("GRAPHITE") || rel.starts_with("tests/graphite") {
        return "gpu".to_owned();
    }
    let hay = format!("{rel} {name}").to_ascii_lowercase();
    let rules: &[(&str, &[&str])] = &[
        ("pathops", &["pathop", "pathops"]),
        ("sksl", &["sksl", "runtimeeffect", "runtime_effect"]),
        ("pdf", &["pdf"]),
        ("svg", &["svg"]),
        (
            "codec",
            &[
                "codec", "jpeg", "jpg", "png", "webp", "gif", "bmp", "wbmp", "ico", "avif", "jxl",
                "gainmap", "encode", "exif", "yuv",
            ],
        ),
        (
            "text",
            &[
                "font", "typeface", "glyph", "text", "strike", "emoji", "scaler",
            ],
        ),
        ("skcms", &["skcms", "colorspace", "icc"]),
        (
            "effects",
            &[
                "shader", "gradient", "filter", "effect", "blend", "blur", "dash", "mask",
            ],
        ),
    ];
    for (module, needles) in rules {
        if needles.iter().any(|n| hay.contains(n)) {
            return (*module).to_owned();
        }
    }
    match kind {
        Kind::Gm => "raster",
        _ => "core",
    }
    .to_owned()
}

/// `return new FooGM(1, 2);` -> `FooGM(1, 2)`; empty -> `<anonymous>`.
fn normalize_name(raw: &str) -> String {
    let s = raw.trim();
    let s = s.strip_prefix("return").map_or(s, str::trim_start);
    let s = s.strip_prefix("new ").map_or(s, str::trim_start);
    let s = s.trim_end_matches(';').trim();
    if s.is_empty() {
        "<anonymous>".to_owned()
    } else {
        s.to_owned()
    }
}

fn normalize_ws(s: &str) -> String {
    s.lines().map(str::trim_end).collect::<Vec<_>>().join("\n")
}

fn rel_path(base: &Path, path: &Path) -> String {
    path.strip_prefix(base)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

/// Hash a data file. Text files (no NUL bytes) are hashed with CRLF normalized
/// to LF, so hashes don't depend on the checkout's `core.autocrlf` setting.
fn hash_file(path: &Path) -> Result<String> {
    let bytes = std::fs::read(path)?;
    if bytes.contains(&0) {
        return Ok(sha256_hex(&bytes));
    }
    let mut normalized = Vec::with_capacity(bytes.len());
    for (i, &b) in bytes.iter().enumerate() {
        if !(b == b'\r' && bytes.get(i + 1) == Some(&b'\n')) {
            normalized.push(b);
        }
    }
    Ok(sha256_hex(&normalized))
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut out = String::with_capacity(64);
    for b in &digest {
        let _ = write!(out, "{b:02x}");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names() {
        assert_eq!(normalize_name("return new FooGM(1, 2);"), "FooGM(1, 2)");
        assert_eq!(normalize_name("PathTest"), "PathTest");
        assert_eq!(normalize_name(""), "<anonymous>");
    }

    #[test]
    fn exclusions() {
        assert!(policy_exclusion("DEF_GANESH_TEST", "tests/X.cpp").is_some());
        assert!(policy_exclusion("DEF_GANESH_AND_GRAPHITE_TEST", "tests/X.cpp").is_none());
        assert!(
            policy_exclusion("DEF_GRAPHITE_TEST_FOR_DAWN_AND_METAL_CONTEXTS", "t.cpp").is_none()
        );
        assert!(policy_exclusion("DEF_GRAPHITE_TEST_FOR_METAL_CONTEXT", "t.cpp").is_some());
        assert!(policy_exclusion("DEF_TEST", "tests/X.cpp").is_none());
    }

    #[test]
    fn rates() {
        assert_eq!(rate(1, 3), "33.3%");
        assert_eq!(rate(0, 0), "-");
    }
}
