//! Publishing goldens as a GitHub Release (docs/PLAN.md §5.3).
//!
//! `cargo xtask oracle publish` bundles the current pin's goldens:
//! - `hashes-<mNNN>.json`: every tier's result id -> SHA-256, plus each tier's toolchain;
//! - `meta-<mNNN>.json`: every tier's result metadata (size, color type, ...);
//! - `objects-<mNNN>.tar`: the content-addressed objects (`objects/<aa>/<sha>.zst`),
//!
//! uploads them to the release `goldens-<mNNN>` (creating or replacing assets), and
//! writes `inventory/goldens.lock` with the release tag and each asset's SHA-256, so every
//! commit names the exact goldens it is tested against.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, ensure};
use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::skia;

#[derive(Serialize)]
struct Hashes {
    skia_branch: String,
    skia_commit: String,
    tiers: BTreeMap<String, TierHashes>,
}

#[derive(Serialize)]
struct TierHashes {
    toolchain: String,
    results: BTreeMap<String, String>,
}

fn milestone(branch: &str) -> Result<&str> {
    branch
        .rsplit('/')
        .next()
        .filter(|m| m.len() > 1 && m.starts_with('m') && m[1..].bytes().all(|b| b.is_ascii_digit()))
        .with_context(|| format!("can't derive a milestone from branch `{branch}`"))
}

fn sha256_file(path: &Path) -> Result<String> {
    let bytes = std::fs::read(path).with_context(|| format!("reading {}", path.display()))?;
    let mut out = String::with_capacity(64);
    for b in Sha256::digest(&bytes) {
        write!(out, "{b:02x}")?;
    }
    Ok(out)
}

fn run(cmd: &mut Command) -> Result<()> {
    let status = cmd.status().with_context(|| format!("running {cmd:?}"))?;
    ensure!(status.success(), "{cmd:?} failed with {status}");
    Ok(())
}

/// Builds the release bundle in `goldens/<commit>/publish/` and returns the asset paths.
fn bundle(root: &Path) -> Result<(String, Vec<PathBuf>)> {
    let pin = skia::read_pin(root)?;
    let m = milestone(&pin.branch)?.to_owned();
    let pin_dir = root.join("goldens").join(&pin.commit);
    ensure!(
        pin_dir.join("objects").exists(),
        "no goldens at {}",
        pin_dir.display()
    );

    let mut tiers = BTreeMap::new();
    let mut metas: BTreeMap<String, serde_json::Value> = BTreeMap::new();
    for entry in std::fs::read_dir(&pin_dir)? {
        let dir = entry?.path();
        let hashes_path = dir.join("hashes.json");
        if !hashes_path.exists() {
            continue;
        }
        let name = dir
            .file_name()
            .and_then(|n| n.to_str())
            .context("non-UTF-8 tier dir")?
            .to_owned();
        let results: BTreeMap<String, String> =
            serde_json::from_str(&std::fs::read_to_string(&hashes_path)?)?;
        let toolchain = std::fs::read_to_string(dir.join("toolchain.txt")).unwrap_or_default();
        let meta: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("meta.json"))?)?;
        metas.insert(name.clone(), meta);
        tiers.insert(name, TierHashes { toolchain, results });
    }
    ensure!(
        !tiers.is_empty(),
        "no tiers with hashes.json under {}",
        pin_dir.display()
    );

    let out = pin_dir.join("publish");
    std::fs::create_dir_all(&out)?;
    let hashes_path = out.join(format!("hashes-{m}.json"));
    let hashes = Hashes {
        skia_branch: pin.branch.clone(),
        skia_commit: pin.commit.clone(),
        tiers,
    };
    std::fs::write(&hashes_path, serde_json::to_string(&hashes)? + "\n")?;
    let meta_path = out.join(format!("meta-{m}.json"));
    std::fs::write(&meta_path, serde_json::to_string(&metas)? + "\n")?;

    let tar_path = out.join(format!("objects-{m}.tar"));
    // Deterministic order is not needed: consumers verify each object by its hash.
    run(Command::new("tar")
        .arg("-cf")
        .arg(&tar_path)
        .arg("-C")
        .arg(&pin_dir)
        .arg("objects"))?;
    println!("bundled {} tiers -> {}", hashes.tiers.len(), out.display());
    Ok((m, vec![hashes_path, meta_path, tar_path]))
}

/// Bundles the goldens, uploads them to the `goldens-<mNNN>` release, and writes
/// `inventory/goldens.lock`.
pub fn publish(root: &Path, dry_run: bool) -> Result<()> {
    let (m, assets) = bundle(root)?;
    let tag = format!("goldens-{m}");

    let mut lock = format!(
        "# Generated by `cargo xtask oracle publish`. The goldens this commit is tested against.\n\
         release = \"{tag}\"\n\n[assets]\n"
    );
    for asset in &assets {
        let name = asset
            .file_name()
            .and_then(|n| n.to_str())
            .context("asset name")?;
        writeln!(lock, "\"{name}\" = \"{}\"", sha256_file(asset)?)?;
    }
    if dry_run {
        print!("{lock}");
        return Ok(());
    }

    let exists = Command::new("gh")
        .args(["release", "view", &tag])
        .output()
        .is_ok_and(|o| o.status.success());
    if !exists {
        run(Command::new("gh").args([
            "release",
            "create",
            &tag,
            "--title",
            &format!("Oracle goldens for Skia {m}"),
            "--notes",
            "Golden outputs rendered by real Skia (see oracle/README.md). \
             `hashes-*.json` is all CI needs; `objects-*.tar` holds the raw outputs \
             (zstd per object) for diffing. Generated by `cargo xtask oracle publish`.",
            "--latest=false",
        ]))?;
    }
    let mut upload = Command::new("gh");
    upload.args(["release", "upload", &tag, "--clobber"]);
    for asset in &assets {
        upload.arg(asset);
    }
    run(&mut upload)?;
    std::fs::write(root.join("inventory").join("goldens.lock"), lock)?;
    println!("published {tag}; wrote inventory/goldens.lock");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn milestone_from_branch() {
        assert_eq!(milestone("chrome/m156").unwrap(), "m156");
        assert!(milestone("main").is_err());
    }
}
