// Skia side of the legacy blitter tests (task D4): runs the real SkARGB32_*_Blitter,
// SkA8_Blitter / SkA8_Coverage_Blitter, SkBlitter::Choose / ChooseSprite blitters and the
// SkBlitRow procs on deterministic inputs and prints one line per step:
//   <scenario>/<step> <fnv1a-64 of the device>
// With the argument `full` each line also carries the device's pixels (for diffing a mismatch).
// The device is hashed as logical a,r,g,b bytes per pixel (a byte per pixel for A8), so the
// output does not depend on the platform's N32 byte order.
//
// The inputs are generated by the functions below (hash32, R, pm_pixel, ...); the Rust test
// (crates/skia-rust-raster/src/legacy_blitters_tests.rs) generates the same ones and compares
// the lines of crates/skia-rust-raster/src/skia_d4_dump.txt.
//
// Build and run (Windows): oracle/rp-builder/build-d4.ps1, against out/oracle/x64-sse2 with
// SKIA_ORACLE_CPU_CAP=baseline (the SkOpts kernels of the baseline x86 tier).

#include "include/core/SkAlphaType.h"
#include "include/core/SkBlendMode.h"
#include "include/core/SkColor.h"
#include "include/core/SkColorSpace.h"
#include "include/core/SkColorType.h"
#include "include/core/SkGraphics.h"
#include "include/core/SkImageInfo.h"
#include "include/core/SkMatrix.h"
#include "include/core/SkPaint.h"
#include "include/core/SkPixmap.h"
#include "include/core/SkRect.h"
#include "include/core/SkSurfaceProps.h"
#include "src/core/SkArenaAlloc.h"
#include "src/core/SkBlitRow.h"
#include "src/core/SkBlitter.h"
#include "src/core/SkBlitter_A8.h"
#include "src/core/SkColorPriv.h"
#include "src/core/SkCoreBlitters.h"
#include "src/core/SkDrawTypes.h"
#include "src/core/SkMask.h"
#include "src/core/SkOpts.h"
#include "src/core/SkSpriteBlitter.h"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <functional>
#include <memory>
#include <string>
#include <vector>

static bool gFull = false;

// ---- deterministic inputs (mirrored by the Rust test) --------------------------------------

static uint32_t hash32(uint32_t i) {
    i ^= i >> 16;
    i *= 0x7feb352du;
    i ^= i >> 15;
    i *= 0x846ca68bu;
    i ^= i >> 16;
    return i;
}
static uint32_t R(uint32_t seed, uint32_t k) {
    return hash32(seed * 0x9E3779B1u + k * 0x85EBCA77u + 0x165667B1u);
}

struct Px { uint32_t a, r, g, b; };

// A valid premultiplied color (r, g, b <= a).
static Px pm_pixel(uint32_t seed, uint32_t k) {
    uint32_t a = R(seed, 2 * k) & 0xFF;
    uint32_t c = R(seed, 2 * k + 1);
    return {a, (c & 0xFF) * a / 255, ((c >> 8) & 0xFF) * a / 255, ((c >> 16) & 0xFF) * a / 255};
}
static Px opaque_pixel(uint32_t seed, uint32_t k) {
    uint32_t c = R(seed, 2 * k + 1);
    return {255, c & 0xFF, (c >> 8) & 0xFF, (c >> 16) & 0xFF};
}
// Any bytes, premultiplied or not.
static Px raw_pixel(uint32_t seed, uint32_t k) {
    uint32_t a = R(seed, 2 * k);
    uint32_t c = R(seed, 2 * k + 1);
    return {a & 0xFF, c & 0xFF, (c >> 8) & 0xFF, (c >> 16) & 0xFF};
}
static Px sentinel() { return {0xDE, 0xAD, 0xBE, 0xEF}; }
static uint32_t pack(Px p) { return SkPackARGB32(p.a, p.r, p.g, p.b); }
static Px unpack(uint32_t c) {
    return {SkGetPackedA32(c), SkGetPackedR32(c), SkGetPackedG32(c), SkGetPackedB32(c)};
}

enum class Bg { Premul, Opaque, Raw };
static Px bg_pixel(Bg bg, uint32_t k) {
    switch (bg) {
        case Bg::Premul: return pm_pixel(1, k);
        case Bg::Opaque: return opaque_pixel(2, k);
        case Bg::Raw:    return raw_pixel(3, k);
    }
    return {};
}

static const int W = 19;       // device width in pixels
static const int H = 4;        // device height
static const int RB_PX = 21;   // device row stride in pixels (2 pixels of padding)

// ---- hashing -------------------------------------------------------------------------------

struct Fnv {
    uint64_t h = 0xcbf29ce484222325ull;
    void byte(uint8_t b) { h ^= b; h *= 0x100000001b3ull; }
};

static void emit(const std::string& name, const std::vector<uint8_t>& logical) {
    Fnv f;
    for (uint8_t b : logical) f.byte(b);
    printf("%s %016llx", name.c_str(), (unsigned long long)f.h);
    if (gFull) {
        printf(" ");
        for (uint8_t b : logical) printf("%02x", b);
    }
    printf("\n");
}

// ---- devices -------------------------------------------------------------------------------

struct N32Dev {
    int w, h, rbPx;
    std::vector<uint32_t> px;
    SkImageInfo info;
    N32Dev(int w, int h, int rbPx, Bg bg, sk_sp<SkColorSpace> cs = nullptr)
            : w(w), h(h), rbPx(rbPx), px(rbPx * h),
              info(SkImageInfo::MakeN32Premul(w, h, std::move(cs))) {
        for (int y = 0; y < h; ++y)
            for (int x = 0; x < rbPx; ++x)
                px[y * rbPx + x] = pack(x >= w ? sentinel() : bg_pixel(bg, y * rbPx + x));
    }
    SkPixmap pixmap() { return SkPixmap(info, px.data(), rbPx * 4); }
    std::vector<uint8_t> logical() const {
        std::vector<uint8_t> out;
        for (uint32_t c : px) {
            Px p = unpack(c);
            out.push_back(p.a); out.push_back(p.r); out.push_back(p.g); out.push_back(p.b);
        }
        return out;
    }
};

struct A8Dev {
    int w, h, rb;
    std::vector<uint8_t> px;
    SkImageInfo info;
    A8Dev(int w, int h, int rb)
            : w(w), h(h), rb(rb), px(rb * h), info(SkImageInfo::MakeA8(w, h)) {
        for (int y = 0; y < h; ++y)
            for (int x = 0; x < rb; ++x)
                px[y * rb + x] = x >= w ? 0xA5 : (R(4, y * rb + x) & 0xFF);
    }
    SkPixmap pixmap() { return SkPixmap(info, px.data(), rb); }
};

// ---- masks ---------------------------------------------------------------------------------

struct Masks {
    std::vector<uint8_t> a8, bw, lcd, argb;
    SkIRect b;
    int w, h;
    Masks(SkIRect b) : b(b), w(b.width()), h(b.height()) {
        a8.resize(w * h);
        for (int i = 0; i < w * h; ++i) {
            uint8_t v = R(6, i) & 0xFF;
            if (i % 7 == 0) v = 0;
            if (i % 11 == 0) v = 255;
            a8[i] = v;
        }
        int bwRB = (w + 7) >> 3;
        bw.assign(bwRB * h, 0);
        for (int y = 0; y < h; ++y)
            for (int x = 0; x < w; ++x)
                if (R(7, y * w + x) & 1) bw[y * bwRB + (x >> 3)] |= 0x80 >> (x & 7);
        lcd.resize(w * h * 2);
        for (int i = 0; i < w * h; ++i) {
            uint16_t v = R(8, i) & 0xFFFF;
            if (i % 5 == 0) v = 0;
            if (i % 13 == 0) v = 0xFFFF;
            memcpy(&lcd[i * 2], &v, 2);
        }
        argb.resize(w * h * 4);
        for (int i = 0; i < w * h; ++i) {
            uint32_t c = pack(pm_pixel(9, i));
            memcpy(&argb[i * 4], &c, 4);
        }
    }
    SkMask a8Mask() const { return SkMask(a8.data(), b, w, SkMask::kA8_Format); }
    SkMask bwMask() const { return SkMask(bw.data(), b, (w + 7) >> 3, SkMask::kBW_Format); }
    SkMask lcdMask() const { return SkMask(lcd.data(), b, w * 2, SkMask::kLCD16_Format); }
    SkMask argbMask() const { return SkMask(argb.data(), b, w * 4, SkMask::kARGB32_Format); }
};

// ---- the battery of blitter calls ------------------------------------------------------------

struct Step {
    std::string name;
    Bg bg;
    bool a8dev;  // run on the A8 device, not the N32 one
    std::function<void(SkBlitter*)> run;
};

static void antih(SkBlitter* b, int y, std::vector<std::pair<int, int>> runs) {
    std::vector<int16_t> r;
    std::vector<SkAlpha> a;
    int n = 0;
    for (auto [count, alpha] : runs) n += count;
    r.assign(n + 1, 0);
    a.assign(n + 1, 0);
    int i = 0;
    for (auto [count, alpha] : runs) {
        r[i] = count;
        a[i] = alpha;
        i += count;
    }
    b->blitAntiH(0, y, a.data(), r.data());
}

// Steps every blitter supports; `masks` adds the mask formats.
static std::vector<Step> battery(bool n32, bool allMasks) {
    std::vector<Step> s;
    Bg pm = Bg::Premul;
    auto add = [&](const char* name, Bg bg, std::function<void(SkBlitter*)> run) {
        s.push_back({name, bg, !n32, std::move(run)});
    };
    add("h_mid", pm, [](SkBlitter* b) { b->blitH(2, 1, 13); });
    add("h_full", pm, [](SkBlitter* b) { b->blitH(0, 0, 19); b->blitH(0, 3, 1); });
    add("rect", pm, [](SkBlitter* b) { b->blitRect(1, 0, 17, 3); });
    add("rect1", pm, [](SkBlitter* b) { b->blitRect(18, 3, 1, 1); });
    for (int a : {0, 1, 77, 128, 254, 255}) {
        add(("v_" + std::to_string(a)).c_str(), pm, [a](SkBlitter* b) {
            b->blitV(5, 0, 4, a);
            b->blitV(18, 1, 2, a);
        });
    }
    add("antih", pm, [](SkBlitter* b) {
        antih(b, 0, {{3, 0}, {5, 255}, {1, 17}, {4, 128}, {6, 254}});
        antih(b, 1, {{19, 200}});
        antih(b, 2, {{1, 255}, {17, 3}, {1, 255}});
        antih(b, 3, {{2, 1}, {2, 254}, {15, 90}});
    });
    if (n32) {
        int pairs[][2] = {{0, 0}, {1, 254}, {255, 128}, {77, 200}, {255, 255}, {0, 255}};
        int i = 0;
        for (auto& p : pairs) {
            int a0 = p[0], a1 = p[1];
            add(("anti2_" + std::to_string(i++)).c_str(), pm, [a0, a1](SkBlitter* b) {
                b->blitAntiH2(3, 1, a0, a1);
                b->blitAntiV2(12, 0, a0, a1);
            });
        }
    }
    // Masks: (name, bounds, clip)
    struct MaskCase { const char* name; SkIRect bounds; SkIRect clip; };
    static const MaskCase kCases[] = {
        {"full",   {0, 0, 19, 4}, {0, 0, 19, 4}},
        {"sub",    {0, 0, 19, 4}, {3, 1, 16, 3}},
        {"offset", {1, 0, 18, 4}, {1, 0, 18, 4}},
        {"offsub", {1, 0, 18, 4}, {4, 1, 13, 3}},
        {"byte",   {0, 0, 19, 4}, {8, 0, 16, 2}},
        {"onebyte",{0, 0, 19, 4}, {5, 2, 6, 3}},
        {"narrow", {0, 0, 19, 4}, {9, 1, 12, 4}},
    };
    for (const MaskCase& c : kCases) {
        auto m = std::make_shared<Masks>(c.bounds);
        SkIRect clip = c.clip;
        std::string n = c.name;
        add(("mask_a8_" + n).c_str(), pm, [m, clip](SkBlitter* b) { b->blitMask(m->a8Mask(), clip); });
        if (!allMasks) continue;
        add(("mask_bw_" + n).c_str(), pm, [m, clip](SkBlitter* b) { b->blitMask(m->bwMask(), clip); });
        add(("mask_argb_" + n).c_str(), pm, [m, clip](SkBlitter* b) { b->blitMask(m->argbMask(), clip); });
        add(("mask_lcd_" + n).c_str(), Bg::Opaque, [m, clip](SkBlitter* b) { b->blitMask(m->lcdMask(), clip); });
    }
    return s;
}

static void runSteps(const std::string& scenario, const std::vector<Step>& steps,
                     const std::function<void(const Step&)>& runStep) {
    for (const Step& st : steps) {
        (void)scenario;
        runStep(st);
    }
}

static SkPaint paintFor(SkColor c, SkBlendMode mode = SkBlendMode::kSrcOver) {
    SkPaint p;
    p.setColor(c);
    p.setBlendMode(mode);
    return p;
}

// Runs every step of `battery` against the blitter that `make` creates on a fresh N32 device.
static void runN32(const std::string& scenario, bool allMasks,
                   const std::function<SkBlitter*(const SkPixmap&, SkArenaAlloc*)>& make) {
    auto steps = battery(true, allMasks);
    runSteps(scenario, steps, [&](const Step& st) {
        N32Dev dev(W, H, RB_PX, st.bg);
        {
            SkPixmap pm = dev.pixmap();
            SkArenaAlloc alloc(4096);
            SkBlitter* b = make(pm, &alloc);
            if (b) st.run(b);
        }
        emit(scenario + "/" + st.name, dev.logical());
    });
}

static void runA8(const std::string& scenario,
                  const std::function<SkBlitter*(const SkPixmap&, SkArenaAlloc*)>& make) {
    auto steps = battery(false, false);
    // Non-A8 masks use SkBlitter's defaults.
    {
        Masks m({0, 0, 19, 4});
        auto bw = [m](SkBlitter* b) { b->blitMask(m.bwMask(), {3, 1, 16, 3}); };
        steps.push_back({"mask_bw_sub", Bg::Premul, true, bw});
    }
    runSteps(scenario, steps, [&](const Step& st) {
        A8Dev dev(W, H, W + 4);
        {
            SkPixmap pm = dev.pixmap();
            SkArenaAlloc alloc(4096);
            SkBlitter* b = make(pm, &alloc);
            if (b) st.run(b);
        }
        emit(scenario + "/" + st.name, dev.px);
    });
}

static std::string hex8(uint32_t v) {
    char buf[16];
    snprintf(buf, sizeof(buf), "%08x", v);
    return buf;
}

int main(int argc, char** argv) {
    SkGraphics::Init();  // applies SKIA_ORACLE_CPU_CAP
    SkOpts::Init();
    gFull = argc > 1 && strcmp(argv[1], "full") == 0;

    // ---- the ARGB32 blitters, constructed directly ----
    for (SkColor c : {0x80336699u, 0x01FFFFFFu, 0xFE0102FDu, 0xC0804020u, 0x00112233u, 0x7F7F7F7Fu}) {
        runN32("argb32/" + hex8(c), true, [c](const SkPixmap& pm, SkArenaAlloc* a) -> SkBlitter* {
            return a->make<SkARGB32_Blitter>(pm, paintFor(c));
        });
    }
    for (SkColor c : {0xFF336699u, 0xFFFFFFFFu, 0xFF010203u}) {
        runN32("opaque/" + hex8(c), true, [c](const SkPixmap& pm, SkArenaAlloc* a) -> SkBlitter* {
            return a->make<SkARGB32_Opaque_Blitter>(pm, paintFor(c));
        });
    }
    runN32("black", true, [](const SkPixmap& pm, SkArenaAlloc* a) -> SkBlitter* {
        return a->make<SkARGB32_Black_Blitter>(pm, paintFor(SK_ColorBLACK));
    });

    // ---- SkBlitter::Choose on N32 devices (the paints the legacy blitters draw) ----
    struct ChooseCase { const char* name; SkColor color; SkBlendMode mode; };
    static const ChooseCase kChoose[] = {
        {"srcover_translucent", 0x80336699, SkBlendMode::kSrcOver},
        {"srcover_opaque",      0xFF336699, SkBlendMode::kSrcOver},
        {"srcover_black",       0xFF000000, SkBlendMode::kSrcOver},
        {"srcover_alpha0",      0x00336699, SkBlendMode::kSrcOver},
        {"src_opaque",          0xFF336699, SkBlendMode::kSrc},
        {"src_black",           0xFF000000, SkBlendMode::kSrc},
        {"dst",                 0x80336699, SkBlendMode::kDst},
    };
    for (const ChooseCase& cc : kChoose) {
        SkColor color = cc.color;
        SkBlendMode mode = cc.mode;
        runN32(std::string("choose/") + cc.name, false,
               [color, mode](const SkPixmap& pm, SkArenaAlloc* a) -> SkBlitter* {
                   return SkBlitter::Choose(pm, SkMatrix::I(), paintFor(color, mode), a,
                                            SkDrawCoverage::kNo, nullptr, SkSurfaceProps(),
                                            SkRect::MakeIWH(W, H));
               });
    }

    // ---- A8 ----
    for (int alpha : {0xFF, 0x80, 0x33, 0x00}) {
        for (SkBlendMode mode : {SkBlendMode::kSrcOver, SkBlendMode::kSrc}) {
            SkColor color = SkColorSetARGB(alpha, 0x12, 0x34, 0x56);
            std::string name = std::string("a8/") + (mode == SkBlendMode::kSrc ? "src_" : "srcover_") +
                               std::to_string(alpha);
            runA8(name, [color, mode](const SkPixmap& pm, SkArenaAlloc* a) -> SkBlitter* {
                return SkChooseA8Blitter(pm, SkMatrix::I(), paintFor(color, mode), a,
                                         SkDrawCoverage::kNo, nullptr);
            });
        }
    }
    runA8("a8/coverage", [](const SkPixmap& pm, SkArenaAlloc* a) -> SkBlitter* {
        return SkChooseA8Blitter(pm, SkMatrix::I(), paintFor(SK_ColorBLACK), a,
                                 SkDrawCoverage::kYes, nullptr);
    });
    runA8("a8/choose_coverage", [](const SkPixmap& pm, SkArenaAlloc* a) -> SkBlitter* {
        return SkBlitter::Choose(pm, SkMatrix::I(), paintFor(SK_ColorBLACK), a, SkDrawCoverage::kYes,
                                 nullptr, SkSurfaceProps(), SkRect::MakeIWH(W, H));
    });

    // ---- sprites ----
    struct SpriteCase {
        const char* name;
        uint32_t alpha;
        SkBlendMode mode;
        bool opaqueSource;
    };
    static const SpriteCase kSprites[] = {
        {"memcpy_src",          0xFF, SkBlendMode::kSrc,     false},
        {"memcpy_srcover_opaque", 0xFF, SkBlendMode::kSrcOver, true},
        {"d32_srcover",         0xFF, SkBlendMode::kSrcOver, false},
        {"d32_alpha_translucent", 0x80, SkBlendMode::kSrcOver, false},
        {"d32_alpha_opaque",    0x80, SkBlendMode::kSrcOver, true},
        {"d32_alpha_1",         0x01, SkBlendMode::kSrcOver, false},
    };
    for (const SpriteCase& sc : kSprites) {
        struct Call { const char* name; int x, y, w, h; };
        static const Call kCalls[] = {
            {"full", 3, 2, 8, 5}, {"sub", 5, 3, 4, 2}, {"one", 10, 6, 1, 1}, {"row", 3, 4, 8, 1},
        };
        for (const Call& call : kCalls) {
            N32Dev dst(W, 8, RB_PX, Bg::Premul);
            const int SW = 8, SH = 5, SRB_PX = 11;
            std::vector<uint32_t> src(SRB_PX * SH);
            for (int y = 0; y < SH; ++y)
                for (int x = 0; x < SRB_PX; ++x)
                    src[y * SRB_PX + x] = pack(x >= SW ? Px{0xCA, 0xFE, 0xF0, 0x0D}
                                                      : (sc.opaqueSource ? opaque_pixel(5, y * SRB_PX + x)
                                                                         : pm_pixel(5, y * SRB_PX + x)));
            SkImageInfo sinfo = SkImageInfo::MakeN32(SW, SH, sc.opaqueSource ? kOpaque_SkAlphaType
                                                                           : kPremul_SkAlphaType);
            SkPixmap spm(sinfo, src.data(), SRB_PX * 4);
            {
                SkPixmap dpm = dst.pixmap();
                SkArenaAlloc alloc(4096);
                SkPaint p = paintFor(SkColorSetA(0x336699, sc.alpha), sc.mode);
                SkBlitter* b = SkBlitter::ChooseSprite(dpm, p, spm, 3, 2, &alloc, nullptr);
                if (b) b->blitRect(call.x, call.y, call.w, call.h);
                else printf("# %s: no sprite blitter\n", sc.name);
            }
            emit(std::string("sprite/") + sc.name + "/" + call.name, dst.logical());
        }
    }

    // ---- sprites drawn by SkRasterPipelineSpriteBlitter (lowp/highp pipelines: the dump of each
    // CPU tier differs) ----
    struct RpSpriteCase {
        const char* name;
        SkColorType srcCT;
        bool opaqueSource;
        uint32_t alpha;
        SkBlendMode mode;
        bool linearDst;
    };
    static const RpSpriteCase kRpSprites[] = {
        {"plus_opaque",      kN32_SkColorType,     true,  0xFF, SkBlendMode::kPlus,     false},
        {"plus_translucent", kN32_SkColorType,     false, 0x80, SkBlendMode::kPlus,     false},
        {"a8_srcover",       kAlpha_8_SkColorType, false, 0xC0, SkBlendMode::kSrcOver,  false},
        {"srgb_linear",      kN32_SkColorType,     false, 0xFF, SkBlendMode::kSrcOver,  true},
        {"multiply",         kN32_SkColorType,     false, 0xFF, SkBlendMode::kMultiply, false},
    };
    for (const RpSpriteCase& sc : kRpSprites) {
        struct Call { const char* name; int x, y, w, h; };
        static const Call kCalls[] = {{"full", 3, 2, 8, 5}, {"sub", 5, 3, 4, 2}};
        for (const Call& call : kCalls) {
            N32Dev dst(W, 8, RB_PX, Bg::Premul, sc.linearDst ? SkColorSpace::MakeSRGBLinear() : nullptr);
            const int SW = 8, SH = 5;
            std::vector<uint32_t> src32;
            std::vector<uint8_t> src8;
            SkPixmap spm;
            if (sc.srcCT == kAlpha_8_SkColorType) {
                const int SRB = 11;
                src8.resize(SRB * SH);
                for (int y = 0; y < SH; ++y)
                    for (int x = 0; x < SRB; ++x)
                        src8[y * SRB + x] = x >= SW ? 0xCA : (R(5, y * SRB + x) & 0xFF);
                spm = SkPixmap(SkImageInfo::MakeA8(SW, SH), src8.data(), SRB);
            } else {
                const int SRB_PX = 11;
                src32.resize(SRB_PX * SH);
                for (int y = 0; y < SH; ++y)
                    for (int x = 0; x < SRB_PX; ++x)
                        src32[y * SRB_PX + x] = pack(x >= SW ? Px{0xCA, 0xFE, 0xF0, 0x0D}
                                                           : (sc.opaqueSource ? opaque_pixel(5, y * SRB_PX + x)
                                                                              : pm_pixel(5, y * SRB_PX + x)));
                spm = SkPixmap(SkImageInfo::MakeN32(SW, SH, sc.opaqueSource ? kOpaque_SkAlphaType
                                                                            : kPremul_SkAlphaType),
                               src32.data(), SRB_PX * 4);
            }
            {
                SkPixmap dpm = dst.pixmap();
                SkArenaAlloc alloc(4096);
                SkPaint p = paintFor(SkColorSetA(0x336699, sc.alpha), sc.mode);
                SkBlitter* b = SkBlitter::ChooseSprite(dpm, p, spm, 3, 2, &alloc, nullptr);
                if (b) b->blitRect(call.x, call.y, call.w, call.h);
                else printf("# %s: no sprite blitter\n", sc.name);
            }
            emit(std::string("sprite_rp/") + sc.name + "/" + call.name, dst.logical());
        }
    }

    // ---- SkBlitRow ----
    {
        const int N = 23;
        struct RowCase { const char* name; Px (*gen)(uint32_t, uint32_t); };
        static const RowCase kSrcs[] = {{"pm", pm_pixel}, {"raw", raw_pixel}};
        for (const RowCase& rc : kSrcs) {
            for (unsigned flags = 0; flags < 4; ++flags) {
                std::vector<unsigned> alphas;
                if (flags == 0 || flags == 2) alphas = {255};
                else alphas = {0, 1, 77, 128, 254, 255};
                for (unsigned alpha : alphas) {
                    for (int n : {1, 3, 4, 5, 8, 23}) {
                        std::vector<uint32_t> dst(N), src(N);
                        for (int i = 0; i < N; ++i) {
                            dst[i] = pack(raw_pixel(10, i));
                            src[i] = pack(rc.gen(11, i));
                        }
                        SkBlitRow::Factory32(flags)(dst.data(), src.data(), n, alpha);
                        std::vector<uint8_t> out;
                        for (uint32_t c : dst) {
                            Px p = unpack(c);
                            out.push_back(p.a); out.push_back(p.r); out.push_back(p.g); out.push_back(p.b);
                        }
                        emit(std::string("blitrow/") + rc.name + "/f" + std::to_string(flags) + "/a" +
                                     std::to_string(alpha) + "/n" + std::to_string(n),
                             out);
                    }
                }
            }
        }
        for (SkPMColor c : {0x00000000u, 0xFF336699u, 0x80336699u, 0x01010101u, 0xFEFDFCFBu}) {
            // c is given as logical a,r,g,b; pack it.
            SkPMColor pmc = SkPackARGB32((c >> 24) & 0xFF, (c >> 16) & 0xFF, (c >> 8) & 0xFF, c & 0xFF);
            for (int n : {1, 3, 4, 5, 8, 23}) {
                std::vector<uint32_t> dst(N);
                for (int i = 0; i < N; ++i) dst[i] = pack(pm_pixel(12, i));
                SkBlitRow::Color32(dst.data(), n, pmc);
                std::vector<uint8_t> out;
                for (uint32_t d : dst) {
                    Px p = unpack(d);
                    out.push_back(p.a); out.push_back(p.r); out.push_back(p.g); out.push_back(p.b);
                }
                emit("color32/" + hex8(c) + "/n" + std::to_string(n), out);
            }
        }
    }
    return 0;
}
