// Copyright 2026 The skia-rust Authors
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

//! Differential test of the XML tokenizer against expat.
//!
//! `tests/data/expat_corpus.txt` holds documents and the events expat 2.6 produced for them when
//! driven like `SkXMLParser` drives it (element, attribute and buffered-text callbacks, an entity
//! declaration stops the parse). The corpus is generated by a throw-away script that runs the
//! documents through `pyexpat`; the expected events are recorded, not recomputed.
//!
//! Set `XML_EXPAT_CORPUS=<file>` to run another corpus of the same format.

use skia_rust_core::xml::XmlParser;

#[derive(Default)]
struct Recorder(Vec<String>);

fn hex(s: &str) -> String {
    use std::fmt::Write;
    s.bytes().fold(String::new(), |mut o, b| {
        let _ = write!(o, "{b:02x}");
        o
    })
}

impl XmlParser for Recorder {
    fn on_start_element(&mut self, e: &str) -> bool {
        self.0.push(format!("S {}", hex(e)));
        false
    }
    fn on_add_attribute(&mut self, n: &str, v: &str) -> bool {
        self.0.push(format!("A {} {}", hex(n), hex(v)));
        false
    }
    fn on_end_element(&mut self, e: &str) -> bool {
        self.0.push(format!("E {}", hex(e)));
        false
    }
    fn on_text(&mut self, t: &str) -> bool {
        self.0.push(format!("T {}", hex(t)));
        false
    }
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex"))
        .collect()
}

#[test]
fn matches_expat() {
    // The committed corpus is compiled in (no file access on wasm); a path in the environment
    // runs another one.
    let corpus = match std::env::var("XML_EXPAT_CORPUS") {
        Ok(path) => std::fs::read_to_string(path).expect("corpus"),
        Err(_) => include_str!("data/expat_corpus.txt").to_owned(),
    };
    let max_fail: usize = std::env::var("XML_EXPAT_MAX_FAIL")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(20);
    let mut failures = 0;
    let mut total = 0;
    for case in corpus.split("\n\n") {
        let mut lines = case.lines().filter(|l| !l.is_empty());
        let Some(doc_line) = lines.next() else {
            continue;
        };
        let doc = unhex(doc_line.strip_prefix("D ").expect("D line"));
        let ok = lines.next().expect("R line") == "R ok";
        let expected: Vec<String> = lines.map(str::to_owned).collect();
        let mut rec = Recorder::default();
        let got_ok = rec.parse(&doc);
        total += 1;
        if got_ok != ok || rec.0 != expected {
            failures += 1;
            if failures <= max_fail {
                eprintln!(
                    "MISMATCH doc hex {}\n  doc {:?}\n  expat: ok={ok} {expected:?}\n  ours:  ok={got_ok} {:?}",
                    doc_line.trim_start_matches("D "),
                    String::from_utf8_lossy(&doc),
                    rec.0
                );
            }
        }
    }
    assert!(
        failures == 0,
        "{failures} of {total} documents differ from expat"
    );
}
