#!/usr/bin/env python3
"""Runs the built subset_diff driver over corpus.txt and writes expected.txt.

Usage: gen_expected.py <subset_diff binary> <fonts dir> <corpus.txt> <scratch dir> > expected.txt

Line format: `<font> <ttc index> <set name> <length> <sha256>` or `<font> <ttc index> <set name> FAIL`.
"""
import hashlib
import os
import subprocess
import sys

binary, fonts, corpus, scratch = sys.argv[1:5]
os.makedirs(scratch, exist_ok=True)
out = subprocess.run([binary, fonts, corpus, scratch], check=True, capture_output=True, text=True).stdout
print("# Generated by gen_expected.py from the pinned HarfBuzz (9cb1fee5) via subset_diff.c; do not edit.")
for line in out.splitlines():
    font, idx, name, length = line.split()
    if length == "FAIL":
        print(font, idx, name, "FAIL")
        continue
    blob = open(os.path.join(scratch, "%s.%s.%s.bin" % (font, idx, name)), "rb").read()
    assert len(blob) == int(length)
    print(font, idx, name, length, hashlib.sha256(blob).hexdigest())
