#!/usr/bin/env python3
"""Generates corpus.txt: glyph sets to subset for every font in third_party/skia/resources/fonts that
has outlines (glyf, CFF or CFF2) and that Skia's PDF backend could embed (not the bitmap-only,
Type1 or web-font containers).

Usage: gen_corpus.py <skia-resources-fonts-dir> > corpus.txt

Line format: `<font file> <ttc index> <set name> <gid>,<gid>,...`

Sets (all deterministic; random sets use random.Random(seed)):
  single      glyph 1 (or the last glyph when the font has two)
  single+0    glyph 0 and glyph 1 (so Skia's `has(0)` turns on NOTDEF_OUTLINE)
  last        the last glyph only
  ascii       the glyphs the cmap maps U+0020..U+007E to (without glyph 0)
  ascii+0     the same with glyph 0
  rand1..3    seeds 1..3: each glyph 1..N-1 is kept with probability 1/8 (at least one glyph)
  rand1+0..   the same sets with glyph 0 added
  all         glyphs 1..N-1
  all+0       glyphs 0..N-1
"""
import os
import random
import struct
import sys

SKIP_EXT = (".xml", ".pfa", ".pfb", ".woff", ".woff2")


def u16(d, o):
    return struct.unpack(">H", d[o:o + 2])[0]


def u32(d, o):
    return struct.unpack(">I", d[o:o + 4])[0]


def tables(d, off):
    n = u16(d, off + 4)
    t = {}
    for j in range(n):
        r = off + 12 + 16 * j
        t[d[r:r + 4].decode("latin1")] = (u32(d, r + 8), u32(d, r + 12))
    return t


def cmap_lookup(d, tabs, cps):
    """Minimal cmap reader (formats 0, 4, 6, 12) over the first Unicode-capable subtable."""
    if "cmap" not in tabs:
        return {}
    base = tabs["cmap"][0]
    n = u16(d, base + 2)
    best = None
    for i in range(n):
        pid, eid, off = u16(d, base + 4 + 8 * i), u16(d, base + 6 + 8 * i), u32(d, base + 8 + 8 * i)
        fmt = u16(d, base + off)
        rank = None
        if (pid, eid) == (3, 10) or (pid == 0 and eid in (4, 6)):
            rank = 0
        elif (pid, eid) == (3, 1) or pid == 0:
            rank = 1
        elif (pid, eid) == (1, 0):
            rank = 2
        if rank is not None and fmt in (0, 4, 6, 12) and (best is None or rank < best[0]):
            best = (rank, base + off, fmt)
    if best is None:
        return {}
    _, so, fmt = best
    out = {}
    for cp in cps:
        g = 0
        if fmt == 0:
            if cp < 256:
                g = d[so + 6 + cp]
        elif fmt == 6:
            first, cnt = u16(d, so + 6), u16(d, so + 8)
            if first <= cp < first + cnt:
                g = u16(d, so + 10 + 2 * (cp - first))
        elif fmt == 4:
            segx2 = u16(d, so + 6)
            ends = so + 14
            starts = ends + segx2 + 2
            deltas = starts + segx2
            ranges = deltas + segx2
            for s in range(segx2 // 2):
                if cp <= u16(d, ends + 2 * s):
                    if cp >= u16(d, starts + 2 * s):
                        ro = u16(d, ranges + 2 * s)
                        if ro == 0:
                            g = (cp + u16(d, deltas + 2 * s)) & 0xFFFF
                        else:
                            p = ranges + 2 * s + ro + 2 * (cp - u16(d, starts + 2 * s))
                            g = u16(d, p)
                            if g:
                                g = (g + u16(d, deltas + 2 * s)) & 0xFFFF
                    break
        elif fmt == 12:
            ng = u32(d, so + 12)
            for s in range(ng):
                a, b, gg = u32(d, so + 16 + 12 * s), u32(d, so + 20 + 12 * s), u32(d, so + 24 + 12 * s)
                if a <= cp <= b:
                    g = gg + cp - a
                    break
        if g:
            out[cp] = g
    return out


def main():
    fonts = sys.argv[1]
    print("# Generated by gen_corpus.py; do not edit.")
    for name in sorted(os.listdir(fonts)):
        path = os.path.join(fonts, name)
        if os.path.isdir(path) or name.endswith(SKIP_EXT):
            continue
        d = open(path, "rb").read()
        offs = [0]
        if d[:4] == b"ttcf":
            n = u32(d, 8)
            offs = [u32(d, 12 + 4 * i) for i in range(n)]
        for idx, off in enumerate(offs):
            tabs = tables(d, off)
            if not ({"glyf", "CFF ", "CFF2"} & set(tabs)):
                continue
            ng = u16(d, tabs["maxp"][0] + 4)
            if ng < 2:
                continue
            asc = cmap_lookup(d, tabs, range(0x20, 0x7F))
            ascii_gids = sorted(set(asc.values()) - {0})
            sets = [("single", [1]), ("last", [ng - 1]), ("ascii", ascii_gids or [1]),
                    ("all", list(range(1, ng)))]
            for seed in (1, 2, 3):
                r = random.Random(seed)
                g = [i for i in range(1, ng) if r.randrange(8) == 0] or [1 + seed % (ng - 1)]
                sets.append(("rand%d" % seed, g))
            for sname, gids in list(sets):
                sets.append((sname + "+0", [0] + gids))
            for sname, gids in sets:
                print(name, idx, sname, ",".join(str(g) for g in gids))


main()
